import type { Language } from "./i18n";

export interface Lore {
  readonly text: Readonly<Record<Language, string>>;
}

export const LORES: readonly Lore[] = [
  { text: { en: "The Leopard shuttle has the second-fastest warp speed in the game.", zh: "The Leopard shuttle has the second-fastest warp speed in the game.", ja: "The Leopard shuttle has the second-fastest warp speed in the game." } },
  { text: { en: "Interceptors are the fastest ship class in EVE, with the Claw reaching over 800 m/s sub-warp.", zh: "Interceptors are the fastest ship class in EVE, with the Claw reaching over 800 m/s sub-warp.", ja: "Interceptors are the fastest ship class in EVE, with the Claw reaching over 800 m/s sub-warp." } },
  { text: { en: "The Dramiel holding an MWD is faster than any interceptor in raw velocity.", zh: "The Dramiel holding an MWD is faster than any interceptor in raw velocity.", ja: "The Dramiel holding an MWD is faster than any interceptor in raw velocity." } },
  { text: { en: "The fastest sub-warp speed belongs to a command destroyer, the Pontifex, with a max-rolled 50MN microwarpdrive.", zh: "The fastest sub-warp speed belongs to a command destroyer, the Pontifex, with a max-rolled 50MN microwarpdrive.", ja: "The fastest sub-warp speed belongs to a command destroyer, the Pontifex, with a max-rolled 50MN microwarpdrive." } },
  { text: { en: "Covert Ops frigates and Interceptors share the fastest base warp speed at 8.00 AU/s.", zh: "Covert Ops frigates and Interceptors share the fastest base warp speed at 8.00 AU/s.", ja: "Covert Ops frigates and Interceptors share the fastest base warp speed at 8.00 AU/s." } },
  { text: { en: "Titans and Freighters are the slowest ships to warp, at just 1.5 AU/s per second.", zh: "Titans and Freighters are the slowest ships to warp, at just 1.5 AU/s per second.", ja: "Titans and Freighters are the slowest ships to warp, at just 1.5 AU/s per second." } },
  { text: { en: "Shuttles are naturally immune to interdiction probes, warp disruption fields, and mobile warp disruptors.", zh: "Shuttles are naturally immune to interdiction probes, warp disruption fields, and mobile warp disruptors.", ja: "Shuttles are naturally immune to interdiction probes, warp disruption fields, and mobile warp disruptors." } },
  { text: { en: "The Amarr Abaddon and Apocalypse tie for the highest powergrid output among battleships at 21,000 MW.", zh: "The Amarr Abaddon and Apocalypse tie for the highest powergrid output among battleships at 21,000 MW.", ja: "The Amarr Abaddon and Apocalypse tie for the highest powergrid output among battleships at 21,000 MW." } },
  { text: { en: "Not even Abaddon can equip 8 Tachyon Beam Laser without power grid upgrade.", zh: "Not even Abaddon can equip 8 Tachyon Beam Laser without power grid upgrade.", ja: "Not even Abaddon can equip 8 Tachyon Beam Laser without power grid upgrade." } },
  { text: { en: "Blasters have the best tracking speed of any turret type in the game.", zh: "Blasters have the best tracking speed of any turret type in the game.", ja: "Blasters have the best tracking speed of any turret type in the game." } },
  { text: { en: "Artillery has the worst tracking speed of any weapon system, even worse than railguns.", zh: "Artillery has the worst tracking speed of any weapon system, even worse than railguns.", ja: "Artillery has the worst tracking speed of any weapon system, even worse than railguns." } },
  { text: { en: "Pulse lasers have the poorest close-range tracking of all short-range weapons.", zh: "Pulse lasers have the poorest close-range tracking of all short-range weapons.", ja: "Pulse lasers have the poorest close-range tracking of all short-range weapons." } },
  { text: { en: "Beam lasers have the best long-range tracking of any turret system.", zh: "Beam lasers have the best long-range tracking of any turret system.", ja: "Beam lasers have the best long-range tracking of any turret system." } },
  { text: { en: "Small turrets always track faster than their larger-size counterparts.", zh: "Small turrets always track faster than their larger-size counterparts.", ja: "Small turrets always track faster than their larger-size counterparts." } },
  { text: { en: "The Velator corvette started as a Gallente passenger craft before being refitted with weapon hardpoints.", zh: "The Velator corvette started as a Gallente passenger craft before being refitted with weapon hardpoints.", ja: "The Velator corvette started as a Gallente passenger craft before being refitted with weapon hardpoints." } },
  { text: { en: "The first frigates were built by the Caldari to counter Gallente combat drones in the early war.", zh: "The first frigates were built by the Caldari to counter Gallente combat drones in the early war.", ja: "The first frigates were built by the Caldari to counter Gallente combat drones in the early war." } },
  { text: { en: "The Megathron has served the Gallente Federation for nearly two decades in frontier conflicts.", zh: "The Megathron has served the Gallente Federation for nearly two decades in frontier conflicts.", ja: "The Megathron has served the Gallente Federation for nearly two decades in frontier conflicts." } },
  { text: { en: "The Ragnarok, Minmatar Titan, draws its name from Norse mythology's prophesied end of the world.", zh: "The Ragnarok, Minmatar Titan, draws its name from Norse mythology's prophesied end of the world.", ja: "The Ragnarok, Minmatar Titan, draws its name from Norse mythology's prophesied end of the world." } },
  { text: { en: "The Amarr practice the Reclaiming, a religious doctrine of conquering and enslaving other races.", zh: "The Amarr practice the Reclaiming, a religious doctrine of conquering and enslaving other races.", ja: "The Amarr practice the Reclaiming, a religious doctrine of conquering and enslaving other races." } },
  { text: { en: "The Minmatar were enslaved by the Amarr for over four centuries before their Great Rebellion in 23216 AD.", zh: "The Minmatar were enslaved by the Amarr for over four centuries before their Great Rebellion in 23216 AD.", ja: "The Minmatar were enslaved by the Amarr for over four centuries before their Great Rebellion in 23216 AD." } },
  { text: { en: "The Caldari are organized as a corporate oligarchy ruled by the Chief Executive Panel of eight megacorporations.", zh: "The Caldari are organized as a corporate oligarchy ruled by the Chief Executive Panel of eight megacorporations.", ja: "The Caldari are organized as a corporate oligarchy ruled by the Chief Executive Panel of eight megacorporations." } },
  { text: { en: "The Gallente Federation is a democracy built on the ideals of progress, human dignity, and individual freedom.", zh: "The Gallente Federation is a democracy built on the ideals of progress, human dignity, and individual freedom.", ja: "The Gallente Federation is a democracy built on the ideals of progress, human dignity, and individual freedom." } },
  { text: { en: "The Jove are the fifth and most technologically advanced human race, shrouded in mystery and genetic manipulation.", zh: "The Jove are the fifth and most technologically advanced human race, shrouded in mystery and genetic manipulation.", ja: "The Jove are the fifth and most technologically advanced human race, shrouded in mystery and genetic manipulation." } },
  { text: { en: "The Minmatar people are divided into seven major tribes: Sebiestor, Krusual, Brutor, Vherokior, Nefantar, Thukker, and Starkmanir.", zh: "The Minmatar people are divided into seven major tribes: Sebiestor, Krusual, Brutor, Vherokior, Nefantar, Thukker, and Starkmanir.", ja: "The Minmatar people are divided into seven major tribes: Sebiestor, Krusual, Brutor, Vherokior, Nefantar, Thukker, and Starkmanir." } },
  { text: { en: "The Ammatar Mandate is a puppet state of the Amarr Empire, created from the collaborating Nefantar tribe.", zh: "The Ammatar Mandate is a puppet state of the Amarr Empire, created from the collaborating Nefantar tribe.", ja: "The Ammatar Mandate is a puppet state of the Amarr Empire, created from the collaborating Nefantar tribe." } },
  { text: { en: "The EVE Gate was the ancient wormhole that brought humanity to New Eden; it collapsed in 8061 AD.", zh: "The EVE Gate was the ancient wormhole that brought humanity to New Eden; it collapsed in 8061 AD.", ja: "The EVE Gate was the ancient wormhole that brought humanity to New Eden; it collapsed in 8061 AD." } },
  { text: { en: "The Yoiul Conference of YC0 established CONCORD and the universal YC calendar for all five empires.", zh: "The Yoiul Conference of YC0 established CONCORD and the universal YC calendar for all five empires.", ja: "The Yoiul Conference of YC0 established CONCORD and the universal YC calendar for all five empires." } },
  { text: { en: "The Battle of Vak'Atioth was the worst military defeat in Amarr history, crushed by the Jovians.", zh: "The Battle of Vak'Atioth was the worst military defeat in Amarr history, crushed by the Jovians.", ja: "The Battle of Vak'Atioth was the worst military defeat in Amarr history, crushed by the Jovians." } },
  { text: { en: "The first and second largest space battles in New Eden were Iyen-Oursta and Vak'Atioth respectively.", zh: "The first and second largest space battles in New Eden were Iyen-Oursta and Vak'Atioth respectively.", ja: "The first and second largest space battles in New Eden were Iyen-Oursta and Vak'Atioth respectively." } },
  { text: { en: "The Gallente-Caldari War lasted nearly a century before CONCORD brokered a peace treaty.", zh: "The Gallente-Caldari War lasted nearly a century before CONCORD brokered a peace treaty.", ja: "The Gallente-Caldari War lasted nearly a century before CONCORD brokered a peace treaty." } },
  { text: { en: "The Jove gifted the hydrostatic capsule to the Caldari, birthing the immortal capsuleer era.", zh: "The Jove gifted the hydrostatic capsule to the Caldari, birthing the immortal capsuleer era.", ja: "The Jove gifted the hydrostatic capsule to the Caldari, birthing the immortal capsuleer era." } },
  { text: { en: "Sansha Kuvakei was a Caldari tycoon who built an empire of cybernetically controlled slaves in the Stain region.", zh: "Sansha Kuvakei was a Caldari tycoon who built an empire of cybernetically controlled slaves in the Stain region.", ja: "Sansha Kuvakei was a Caldari tycoon who built an empire of cybernetically controlled slaves in the Stain region." } },
  { text: { en: "The Blood Raiders are an Amarr death cult devoted to harvesting blood for their twisted pursuit of immortality.", zh: "The Blood Raiders are an Amarr death cult devoted to harvesting blood for their twisted pursuit of immortality.", ja: "The Blood Raiders are an Amarr death cult devoted to harvesting blood for their twisted pursuit of immortality." } },
  { text: { en: "The Sisters of EVE believe the collapsed EVE Gate holds the key to bringing peace to all of New Eden.", zh: "The Sisters of EVE believe the collapsed EVE Gate holds the key to bringing peace to all of New Eden.", ja: "The Sisters of EVE believe the collapsed EVE Gate holds the key to bringing peace to all of New Eden." } },
  { text: { en: "The Guristas were founded in YC94 by two Caldari Navy deserters: Fatal and The Rabbit.", zh: "The Guristas were founded in YC94 by two Caldari Navy deserters: Fatal and The Rabbit.", ja: "The Guristas were founded in YC94 by two Caldari Navy deserters: Fatal and The Rabbit." } },
  { text: { en: "Mordu's Legion originated from Intaki exiles who fought alongside the Caldari Navy during the great war.", zh: "Mordu's Legion originated from Intaki exiles who fought alongside the Caldari Navy during the great war.", ja: "Mordu's Legion originated from Intaki exiles who fought alongside the Caldari Navy during the great war." } },
] as const;
