import type { ClipboardProvider, ProfileTextCodec, SavedFittings, SettingsStore } from "../../appstate";
import type { ChargeCatalog, FittingCradle, FittingImport, GunFamilies, PresetFittings } from "../../fitting";
import type { HitChance } from "../../sim";
import type { Ships } from "../../ships";
import type { I18n } from "../i18n";
import type { ImageCatalog } from "../icons";
import type { Timer } from "../timer";
import type { UiEvents } from "../events";
import type { Controls } from "./controlsContract";
import type { ChoiceGroup } from "./choiceGroup";
import type { DomControlsHost } from "./domControlsContract";
import type { Els } from "./elementsContract";
import type { EngagementReadout } from "./engagementReadout";
import type { HintRotator } from "./hints";
import type { EwarController } from "./ewar";
import type { ImportController } from "./import";
import type { ConfirmController } from "./confirmController";
import type { FittingPopupController, FittingPreview, FittingPreviewManager, PopupGroup } from "./popup";
import type { PreferencesController } from "./preferencesController";
import type { ProfileController } from "./profileController";
import type { ShareController } from "./share";
import type { EventRouter, HullDatalist, SessionCodec } from "./session";
import type { SidePanel } from "./sidePanel";
import type { TrackingInput } from "./trackingInput";
import type { TurretController, TurretOverrides } from "./turret";

export interface ControlsCradle {
  readonly hitChance: HitChance;
  readonly i18n: I18n;
  readonly itemNames: FittingCradle["itemNames"];
  readonly settingsStore: SettingsStore;
  readonly ships: Ships;
  readonly fittingImport: FittingImport;
  readonly gunFamilies: GunFamilies;
  readonly presetFittings: PresetFittings;
  readonly savedFittings: SavedFittings;
  readonly clipboard: ClipboardProvider;
  readonly timer: Timer;
  readonly chargeCatalog: ChargeCatalog;
  readonly imageCatalog: ImageCatalog;
  readonly uiEvents: UiEvents;
  readonly turretOverrides: TurretOverrides;
  readonly popupGroup: PopupGroup;
  readonly els: Els;
  readonly trackingInput: TrackingInput;
  readonly sigResChoice: ChoiceGroup;
  readonly engagementReadout: EngagementReadout;
  readonly hullDatalist: HullDatalist;
  readonly hintRotator: HintRotator;
  readonly preferencesController: PreferencesController;
  readonly profileController: ProfileController;
  readonly profileTextCodec: ProfileTextCodec;
  readonly turretController: TurretController;
  readonly attackerSide: SidePanel;
  readonly targetSide: SidePanel;
  readonly attackerFittingPreview: FittingPreview;
  readonly targetFittingPreview: FittingPreview;
  readonly previewManager: FittingPreviewManager;
  readonly attackerFittingPopup: FittingPopupController;
  readonly targetFittingPopup: FittingPopupController;
  readonly ewarController: EwarController;
  readonly sessionCodec: SessionCodec;
  readonly importController: ImportController;
  readonly shareController: ShareController;
  readonly confirmController: ConfirmController;
  readonly eventRouter: EventRouter;
  readonly controls: Controls & DomControlsHost;
}
