import type { ClipboardProvider, ProfileTextCodec, SavedFittings, SettingsStore } from "../../appstate";
import type { ChargeCatalog, FittingImport, GunFamilies, PresetFittings } from "../../fitting";
import type { ItemNameCatalog } from "../../gamedata/itemNames";
import type { HitChance } from "../../sim";
import type { Ships } from "../../ships";
import type { I18n } from "../i18n";
import type { ImageCatalog } from "../icons";
import type { Timer } from "../timer";
import type { UiEvents } from "../events";
import type { createControlsEls } from "./elements";
import type { Controls } from "./controlsContract";
import type { ChoiceGroup } from "./choiceGroup";
import type { DomControlsHost } from "./domControlsContract";
import type { EffectiveReadout } from "./effectiveReadout";
import type { EngagementReadout } from "./engagementReadout";
import type { HintRotator } from "./hints";
import type { BoosterController } from "./booster";
import type { EwarController } from "./ewar";
import type { ImportController } from "./import";
import type { ConfirmController } from "./confirmController";
import type { FittingPopupController, FittingPreview, FittingPreviewManager, PopupGroup } from "./popup";
import type { PreferencesController } from "./preferencesController";
import type { ProfileController } from "./profileController";
import type { ShareController } from "./share";
import type { HullDatalist, SessionCodec, SessionControl, SimConfigSource } from "./session";
import type { SidePanel } from "./sidePanel";
import type { TrackingInput } from "./trackingInput";
import type { TurretController, TurretOverrides } from "./turret";
import type { RangeOverlayController, RangeOverlayHost } from "./rangeOverlay";
import type { ProfileChangeTracker } from "./profileChangeTracker";
import type { ProfileEquality } from "../../appstate";

type ControlsElements = ReturnType<typeof createControlsEls>;

export interface ControlsCradle {
  readonly hitChance: HitChance;
  readonly i18n: I18n;
  readonly itemNameCatalog: ItemNameCatalog;
  readonly settingsStore: SettingsStore;
  readonly ships: Ships;
  readonly fittingImport: FittingImport;
  readonly gunFamilies: GunFamilies;
  readonly presetFittings: PresetFittings;
  readonly savedFittings: SavedFittings;
  readonly clipboard: ClipboardProvider;
  readonly timer: Timer;
  readonly chargeCatalog: ChargeCatalog;
  readonly imageCatalog: ImageCatalog;
  readonly uiEvents: UiEvents;
  readonly turretOverrides: TurretOverrides;
  readonly popupGroup: PopupGroup;
  readonly els: ControlsElements;
  readonly trackingInput: TrackingInput;
  readonly sigResChoice: ChoiceGroup;
  readonly engagementReadout: EngagementReadout;
  readonly effectiveReadout: EffectiveReadout;
  readonly hullDatalist: HullDatalist;
  readonly hintRotator: HintRotator;
  readonly preferencesController: PreferencesController;
  readonly profileController: ProfileController;
  readonly profileTextCodec: ProfileTextCodec;
  readonly turretController: TurretController;
  readonly attackerSide: SidePanel;
  readonly targetSide: SidePanel;
  readonly attackerFittingPreview: FittingPreview;
  readonly targetFittingPreview: FittingPreview;
  readonly previewManager: FittingPreviewManager;
  readonly attackerFittingPopup: FittingPopupController;
  readonly targetFittingPopup: FittingPopupController;
  readonly ewarController: EwarController;
  readonly boosterController: BoosterController;
  readonly sessionCodec: SessionCodec;
  readonly simConfigSource: SimConfigSource;
  readonly importController: ImportController;
  readonly shareController: ShareController;
  readonly rangeOverlayController: RangeOverlayController;
  readonly controls: Controls & DomControlsHost & RangeOverlayHost & SessionControl;
  readonly confirmController: ConfirmController;
  readonly profileEquality: ProfileEquality;
  readonly profileChangeTracker: ProfileChangeTracker;
}
