import type { ClipboardProvider, ProfileTextCodec, SavedFittings, SettingsParser, SettingsStore } from "../../appstate";
import type { ChargeCatalog, DroneCatalog, DroneLoadoutResolver, DroneLoadoutValidator, FittingCalculator, FittingDb, FittingImport, FittingOverridesStore, GunFamilies, LauncherClasses, MissileCatalog, PresetFittings } from "../../fitting";
import type { EwarResolver, HitChance, SimValueParser } from "../../sim";
import type { Ships } from "../../ships";
import type { ItemNameCatalog, ItemNameLoader } from "../../gamedata";
import type { I18n } from "../i18n";
import type { ImageCatalog } from "../icons";
import type { Timer } from "../timer";
import type { UiEvents } from "../events";
import type { createControlsEls } from "./elements";
import type { Controls, ViewStore } from "./controlsContract";
import type { DomControlsHost } from "./domControls";
import type { EffectiveReadout } from "./effectiveReadout";
import type { EngagementReadout } from "./engagementReadout";
import type { HintRotator } from "./hints";
import type { BoosterController } from "./booster";
import type { MissileBoosterController } from "./missileBooster";
import type { EwarController } from "./ewar";
import type { DefenseController } from "./defense";
import type { ImportController } from "./import";
import type { ConfirmController } from "./confirm";
import type { FittingPopupController, FittingPreview, FittingPreviewManager, PopupGroup } from "./popup";
import type { PreferencesController } from "./preferences";
import type { ProfileController, ProfileChangeTracker } from "./profile";
import type { ShareController } from "./share";
import type { HullDatalist, SessionCodec, SimConfigSource } from "./session";
import type { SidePanel, WeaponSystemSwitch } from "./sidePanel";
import type { TurretController, TurretOverrides } from "./turret";
import type { LauncherController } from "./launcher";
import type { DroneController } from "./drone";
import type { RangeOverlayController } from "./rangeOverlay";
import type { PortraitsController } from "./portraits";
import type { HoverHintController } from "./hoverHint";
import type { ProfileEquality } from "../../appstate";
import type { Side } from "./side";
import type { PanelConfigurationMemory } from "../panelConfigurationMemory";
import type { DpsHintProvider } from "./dpsHint";
import type { DpsHintRenderer } from "./dpsHint";
import type { AmmoHintProvider } from "./ammoHint";
import type { AmmoHintRenderer } from "./ammoHint";
import type { AppliedDpsHintProvider } from "./appliedDpsHint";
import type { AppliedDpsHintRenderer } from "./appliedDpsHint";

type ControlsElements = ReturnType<typeof createControlsEls>;

export interface ControlsCradle {
  readonly hitChance: HitChance;
  readonly simValueParser: SimValueParser;
  readonly i18n: I18n;
  readonly settingsStore: SettingsStore;
  readonly parser: SettingsParser;
  readonly ships: Ships;
  readonly fittingImport: FittingImport;
  readonly gunFamilies: GunFamilies;
  readonly presetFittings: PresetFittings;
  readonly savedFittings: SavedFittings;
  readonly clipboard: ClipboardProvider;
  readonly timer: Timer;
  readonly now: () => number;
  readonly chargeCatalog: ChargeCatalog;
  readonly imageCatalog: ImageCatalog;
  readonly uiEvents: UiEvents;
  readonly itemNameLoader: ItemNameLoader;
  readonly itemNameCatalog: ItemNameCatalog;
  readonly shipATurretOverrides: TurretOverrides;
  readonly shipBTurretOverrides: TurretOverrides;
  readonly turretOverridesBySide: Record<Side, TurretOverrides>;
  readonly shipAPanelMemory: PanelConfigurationMemory;
  readonly shipBPanelMemory: PanelConfigurationMemory;
  readonly panelMemoryBySide: Record<Side, PanelConfigurationMemory>;
  readonly fittingCalculator: FittingCalculator;
  readonly shipAFittingOverrides: FittingOverridesStore;
  readonly shipBFittingOverrides: FittingOverridesStore;
  readonly fittingOverridesBySide: Record<Side, FittingOverridesStore>;
  readonly popupGroup: PopupGroup;
  readonly els: ControlsElements;
  readonly engagementReadout: EngagementReadout;
  readonly effectiveReadout: EffectiveReadout;
  readonly hullDatalist: HullDatalist;
  readonly hintRotator: HintRotator;
  readonly preferencesController: PreferencesController;
  readonly profileController: ProfileController;
  readonly profileTextCodec: ProfileTextCodec;
  readonly shipATurretController: TurretController;
  readonly shipBTurretController: TurretController;
  readonly turretControllers: Record<Side, TurretController>;
  readonly shipALauncherController: LauncherController;
  readonly shipBLauncherController: LauncherController;
  readonly launcherControllers: Record<Side, LauncherController>;
  readonly shipADroneController: DroneController;
  readonly shipBDroneController: DroneController;
  readonly droneControllers: Record<Side, DroneController>;
  readonly weaponSystemSwitches: Record<Side, WeaponSystemSwitch>;
  readonly fittingDb: FittingDb;
  readonly missileCatalog: MissileCatalog;
  readonly droneCatalog: DroneCatalog;
  readonly droneLoadoutResolver: DroneLoadoutResolver;
  readonly droneLoadoutValidator: DroneLoadoutValidator;
  readonly launcherClasses: LauncherClasses;
  readonly shipASide: SidePanel;
  readonly shipBSide: SidePanel;
  readonly shipAFittingPreview: FittingPreview;
  readonly shipBFittingPreview: FittingPreview;
  readonly previewManager: FittingPreviewManager;
  readonly shipAFittingPopup: FittingPopupController;
  readonly shipBFittingPopup: FittingPopupController;
  readonly ewarController: EwarController;
  readonly defenseController: DefenseController;
  readonly boosterController: BoosterController;
  readonly missileBoosterController: MissileBoosterController;
  readonly portraitsController: PortraitsController;
  readonly ewarResolver: EwarResolver;
  readonly sessionCodec: SessionCodec;
  readonly simConfigSource: SimConfigSource;
  readonly importController: ImportController;
  readonly shareController: ShareController;
  readonly rangeOverlayController: RangeOverlayController;
  readonly controls: Controls & DomControlsHost & ViewStore;
  readonly confirmController: ConfirmController;
  readonly profileEquality: ProfileEquality;
  readonly profileChangeTracker: ProfileChangeTracker;
  readonly hoverHintController: HoverHintController;
  readonly dpsHintRenderer: DpsHintRenderer;
  readonly dpsHintProvider: DpsHintProvider;
  readonly ammoHintRenderer: AmmoHintRenderer;
  readonly ammoHintProvider: AmmoHintProvider;
  readonly viewStore: ViewStore;
  readonly appliedDpsHintRenderer: AppliedDpsHintRenderer;
  readonly appliedDpsHintProvider: AppliedDpsHintProvider;
}
