import {
  el,
  elOf,
  isHtmlButtonElement,
  isHtmlImageElement,
  isHtmlInputElement,
  isHtmlSelectElement,
  isHtmlTextAreaElement,
} from "./controlsDom";

export function createControlsEls() {
  return {
    tracking: elOf("tracking", isHtmlInputElement),
    trackingUnitRad: elOf("tracking-unit-rad", isHtmlButtonElement),
    trackingUnitScore: elOf("tracking-unit-score", isHtmlButtonElement),
    sigRes: elOf("sigRes", isHtmlSelectElement),
    sigResOptions: el("sig-res-options"),
    optimal: elOf("optimal", isHtmlInputElement),
    falloff: elOf("falloff", isHtmlInputElement),
    trackingReadout: el("effective-tracking"),
    optimalReadout: el("effective-optimal"),
    falloffReadout: el("effective-falloff"),
    shipASpeedReadout: el("effective-ship-a-speed"),
    shipBSpeedReadout: el("effective-ship-b-speed"),
    shipAAmmoTrigger: elOf("ship-a-ammo-trigger", isHtmlButtonElement),
    shipAAmmoSummary: el("ship-a-ammo-summary"),
    shipAAmmoSummaryIcon: elOf("ship-a-ammo-summary-icon", isHtmlImageElement),
    shipAAmmoPopup: el("ship-a-ammo-popup"),
    shipAAmmoCargoLabel: el("ship-a-ammo-cargo-label"),
    shipAAmmoCargoList: el("ship-a-ammo-cargo-list"),
    shipAAmmoExpand: elOf("ship-a-ammo-expand", isHtmlButtonElement),
    shipAAmmoAllSection: el("ship-a-ammo-all-section"),
    shipAAmmoAllList: el("ship-a-ammo-all-list"),
    hullOptions: el("hull-options"),
    shipAHull: elOf("ship-a-hull", isHtmlInputElement),
    shipAShipImage: elOf("ship-a-ship-image", isHtmlImageElement),
    shipAFittingTrigger: elOf("ship-a-fitting-trigger", isHtmlButtonElement),
    shipAFittingEye: elOf("ship-a-fitting-eye", isHtmlButtonElement),
    shipAFittingPopup: el("ship-a-fitting-popup"),
    shipAFittingPreview: el("ship-a-fitting-preview"),
    shipAFittingSavedLabel: el("ship-a-fitting-saved-label"),
    shipAFittingSavedList: el("ship-a-fitting-saved-list"),
    shipAFittingPresetLabel: el("ship-a-fitting-preset-label"),
    shipAFittingPresetList: el("ship-a-fitting-preset-list"),
    shipAFittingEmpty: el("ship-a-fitting-empty"),
    shipAHullHint: el("ship-a-hull-hint"),
    shipAFittingName: el("ship-a-fitting-name"),
    shipAImportFitting: elOf("ship-a-import-fitting", isHtmlButtonElement),
    shipAPastePopup: el("ship-a-paste-popup"),
    shipAPasteInput: elOf("ship-a-paste-input", isHtmlTextAreaElement),
    shipAPropulsion: elOf("ship-a-propulsion", isHtmlSelectElement),
    shipAPropulsionOptions: el("ship-a-propulsion-options"),
    shipAPropulsionGear: elOf("ship-a-propulsion-gear", isHtmlButtonElement),
    shipAPropulsionVariants: el("ship-a-propulsion-variants"),
    shipASkills: elOf("ship-a-skills", isHtmlSelectElement),
    shipASkillOptions: el("ship-a-skill-options"),
    shipASkillSummary: el("ship-a-skill-summary"),
    shipASkillTrigger: elOf("ship-a-skill-trigger", isHtmlButtonElement),
    shipASkillPopup: el("ship-a-skill-popup"),
    shipAOverload: elOf("ship-a-overload", isHtmlInputElement),
    shipAOverloadButton: elOf("ship-a-overload-button", isHtmlButtonElement),
    shipAEwarField: el("ship-a-ewar-field"),
    shipAEwarTrigger: elOf("ship-a-ewar-trigger", isHtmlButtonElement),
    shipAEwarPopup: el("ship-a-ewar-popup"),
    shipAEwarSection: el("ship-a-ewar-section"),
    shipAEwarSummary: el("ship-a-ewar-summary"),
    shipABoosterSection: el("ship-a-booster-section"),
    shipABoosterSummary: el("ship-a-booster-summary"),
    shipASpeed: elOf("ship-a-speed", isHtmlInputElement),
    shipAMass: elOf("ship-a-mass", isHtmlInputElement),
    shipAInertia: elOf("ship-a-inertia", isHtmlInputElement),
    shipAAlignTime: el("ship-a-align-time"),
    shipAMode: elOf("ship-a-mode", isHtmlSelectElement),
    shipARange: elOf("ship-a-range", isHtmlInputElement),
    shipAAggressivity: elOf("ship-a-aggressivity", isHtmlInputElement),
    shipAAggressivitySlider: elOf("ship-a-aggressivity-slider", isHtmlInputElement),
    shipAAggressivityValue: el("ship-a-aggressivity-value"),
    initialDistance: elOf("initial-distance", isHtmlInputElement),
    shipBHull: elOf("ship-b-hull", isHtmlInputElement),
    shipBShipImage: elOf("ship-b-ship-image", isHtmlImageElement),
    shipBFittingTrigger: elOf("ship-b-fitting-trigger", isHtmlButtonElement),
    shipBFittingEye: elOf("ship-b-fitting-eye", isHtmlButtonElement),
    shipBFittingPopup: el("ship-b-fitting-popup"),
    shipBFittingPreview: el("ship-b-fitting-preview"),
    shipBFittingSavedLabel: el("ship-b-fitting-saved-label"),
    shipBFittingSavedList: el("ship-b-fitting-saved-list"),
    shipBFittingPresetLabel: el("ship-b-fitting-preset-label"),
    shipBFittingPresetList: el("ship-b-fitting-preset-list"),
    shipBFittingEmpty: el("ship-b-fitting-empty"),
    shipBHullHint: el("ship-b-hull-hint"),
    shipBFittingName: el("ship-b-fitting-name"),
    shipBImportFitting: elOf("ship-b-import-fitting", isHtmlButtonElement),
    shipBPastePopup: el("ship-b-paste-popup"),
    shipBPasteInput: elOf("ship-b-paste-input", isHtmlTextAreaElement),
    shipBPropulsion: elOf("ship-b-propulsion", isHtmlSelectElement),
    shipBPropulsionOptions: el("ship-b-propulsion-options"),
    shipBPropulsionGear: elOf("ship-b-propulsion-gear", isHtmlButtonElement),
    shipBPropulsionVariants: el("ship-b-propulsion-variants"),
    shipBSkills: elOf("ship-b-skills", isHtmlSelectElement),
    shipBSkillOptions: el("ship-b-skill-options"),
    shipBSkillSummary: el("ship-b-skill-summary"),
    shipBSkillTrigger: elOf("ship-b-skill-trigger", isHtmlButtonElement),
    shipBSkillPopup: el("ship-b-skill-popup"),
    shipBOverload: elOf("ship-b-overload", isHtmlInputElement),
    shipBOverloadButton: elOf("ship-b-overload-button", isHtmlButtonElement),
    shipBEwarField: el("ship-b-ewar-field"),
    shipBEwarTrigger: elOf("ship-b-ewar-trigger", isHtmlButtonElement),
    shipBEwarPopup: el("ship-b-ewar-popup"),
    shipBEwarSection: el("ship-b-ewar-section"),
    shipBEwarSummary: el("ship-b-ewar-summary"),
    shipBBoosterSection: el("ship-b-booster-section"),
    shipBBoosterSummary: el("ship-b-booster-summary"),
    shipBSpeed: elOf("ship-b-speed", isHtmlInputElement),
    shipBMass: elOf("ship-b-mass", isHtmlInputElement),
    shipBInertia: elOf("ship-b-inertia", isHtmlInputElement),
    shipBAlignTime: el("ship-b-align-time"),
    shipBMode: elOf("ship-b-mode", isHtmlSelectElement),
    shipBRange: elOf("ship-b-range", isHtmlInputElement),
    shipBAggressivity: elOf("ship-b-aggressivity", isHtmlInputElement),
    shipBAggressivitySlider: elOf("ship-b-aggressivity-slider", isHtmlInputElement),
    shipBAggressivityValue: el("ship-b-aggressivity-value"),
    shipBSig: elOf("ship-b-sig", isHtmlInputElement),
    simSpeed: elOf("sim-speed", isHtmlSelectElement),
    profileSave: elOf("profile-save", isHtmlButtonElement),
    profileSelectTrigger: elOf("profile-select-trigger", isHtmlButtonElement),
    profileSelectLabel: el("profile-select-label"),
    profilePopup: el("profile-popup"),
    profileDelete: elOf("profile-delete", isHtmlButtonElement),
    profileNew: elOf("profile-new", isHtmlButtonElement),
    newProfilePopup: el("new-profile-popup"),
    newProfileName: elOf("new-profile-name", isHtmlInputElement),
    newProfileConfirm: elOf("new-profile-confirm", isHtmlButtonElement),
    newProfileCancel: elOf("new-profile-cancel", isHtmlButtonElement),
    confirmPopup: el("confirm-popup"),
    confirmMessage: el("confirm-message"),
    confirmOk: elOf("confirm-ok", isHtmlButtonElement),
    confirmCancel: elOf("confirm-cancel", isHtmlButtonElement),
    shareLink: elOf("share-link", isHtmlButtonElement),
    sharePopup: el("share-popup"),
    shareCopyUrl: elOf("share-copy-url", isHtmlButtonElement),
    shareCopyText: elOf("share-copy-text", isHtmlButtonElement),
    importProfile: elOf("import-profile", isHtmlButtonElement),
    importSidePopup: el("import-side-popup"),
    importSideShipA: elOf("import-side-ship-a", isHtmlButtonElement),
    importSideShipB: elOf("import-side-ship-b", isHtmlButtonElement),
    shareStatus: el("share-status"),
    langEn: elOf("lang-en", isHtmlButtonElement),
    langZh: elOf("lang-zh", isHtmlButtonElement),
    langJa: elOf("lang-ja", isHtmlButtonElement),
    play: elOf("play", isHtmlButtonElement),
    reset: elOf("reset", isHtmlButtonElement),
    gridBrightnessSlider: elOf("grid-brightness-slider", isHtmlInputElement),
    gridBrightnessValue: el("grid-brightness-value"),
    canvasSettingsTrigger: elOf("canvas-settings-trigger", isHtmlButtonElement),
    canvasSettingsPopup: el("canvas-settings-popup"),
    zoomSlider: elOf("zoom-slider", isHtmlInputElement),
    zoomValue: el("zoom-value"),
    autoZoomCheckbox: elOf("auto-zoom", isHtmlInputElement),
    slideHints: el("slide-hints"),
    resDistance: el("res-distance"),
    resTransversal: el("res-transversal"),
    resAngular: el("res-angular"),
    resRadial: el("res-radial"),
    resTrackPen: el("res-track-pen"),
    resRangePen: el("res-range-pen"),
    resHit: el("res-hit"),
    rangeOverlayLegend: el("range-overlay-legend"),
    shipAPortrait: el("ship-a-portrait"),
    shipBPortrait: el("ship-b-portrait"),
  };
}
