import {
  el,
  elOf,
  isHtmlButtonElement,
  isHtmlImageElement,
  isHtmlInputElement,
  isHtmlSelectElement,
  isHtmlTextAreaElement,
} from "./controlsDom";

import type { Els } from "./elementsContract";
export function createControlsEls(): Els {
  return {
    tracking: elOf("tracking", isHtmlInputElement),
    trackingUnitRad: elOf("tracking-unit-rad", isHtmlButtonElement),
    trackingUnitScore: elOf("tracking-unit-score", isHtmlButtonElement),
    sigRes: elOf("sigRes", isHtmlSelectElement),
    sigResOptions: el("sig-res-options"),
    optimal: elOf("optimal", isHtmlInputElement),
    falloff: elOf("falloff", isHtmlInputElement),
    attackerAmmoTrigger: elOf("attacker-ammo-trigger", isHtmlButtonElement),
    attackerAmmoSummary: el("attacker-ammo-summary"),
    attackerAmmoSummaryIcon: elOf("attacker-ammo-summary-icon", isHtmlImageElement),
    attackerAmmoPopup: el("attacker-ammo-popup"),
    attackerAmmoCargoLabel: el("attacker-ammo-cargo-label"),
    attackerAmmoCargoList: el("attacker-ammo-cargo-list"),
    attackerAmmoExpand: elOf("attacker-ammo-expand", isHtmlButtonElement),
    attackerAmmoAllSection: el("attacker-ammo-all-section"),
    attackerAmmoAllList: el("attacker-ammo-all-list"),
    hullOptions: el("hull-options"),
    attackerHull: elOf("attacker-hull", isHtmlInputElement),
    attackerShipImage: elOf("attacker-ship-image", isHtmlImageElement),
    attackerFittingTrigger: elOf("attacker-fitting-trigger", isHtmlButtonElement),
    attackerFittingEye: elOf("attacker-fitting-eye", isHtmlButtonElement),
    attackerFittingPopup: el("attacker-fitting-popup"),
    attackerFittingPreview: el("attacker-fitting-preview"),
    attackerFittingSavedLabel: el("attacker-fitting-saved-label"),
    attackerFittingSavedList: el("attacker-fitting-saved-list"),
    attackerFittingPresetLabel: el("attacker-fitting-preset-label"),
    attackerFittingPresetList: el("attacker-fitting-preset-list"),
    attackerFittingEmpty: el("attacker-fitting-empty"),
    attackerHullHint: el("attacker-hull-hint"),
    attackerFittingName: el("attacker-fitting-name"),
    attackerImportFitting: elOf("attacker-import-fitting", isHtmlButtonElement),
    attackerPastePopup: el("attacker-paste-popup"),
    attackerPasteInput: elOf("attacker-paste-input", isHtmlTextAreaElement),
    attackerPropulsion: elOf("attacker-propulsion", isHtmlSelectElement),
    attackerPropulsionOptions: el("attacker-propulsion-options"),
    attackerPropulsionGear: elOf("attacker-propulsion-gear", isHtmlButtonElement),
    attackerPropulsionVariants: el("attacker-propulsion-variants"),
    attackerSkills: elOf("attacker-skills", isHtmlSelectElement),
    attackerSkillOptions: el("attacker-skill-options"),
    attackerSkillSummary: el("attacker-skill-summary"),
    attackerSkillTrigger: elOf("attacker-skill-trigger", isHtmlButtonElement),
    attackerSkillPopup: el("attacker-skill-popup"),
    attackerOverload: elOf("attacker-overload", isHtmlInputElement),
    attackerOverloadButton: elOf("attacker-overload-button", isHtmlButtonElement),
    attackerEwarTrigger: elOf("attacker-ewar-trigger", isHtmlButtonElement),
    attackerEwarPopup: el("attacker-ewar-popup"),
    attackerEwarSummary: el("attacker-ewar-summary"),
    attackerSpeed: elOf("attacker-speed", isHtmlInputElement),
    attackerMass: elOf("attacker-mass", isHtmlInputElement),
    attackerInertia: elOf("attacker-inertia", isHtmlInputElement),
    attackerAlignTime: el("attacker-align-time"),
    attackerMode: elOf("attacker-mode", isHtmlSelectElement),
    attackerRange: elOf("attacker-range", isHtmlInputElement),
    maneuverAggressivity: elOf("maneuver-aggressivity", isHtmlInputElement),
    maneuverAggressivitySlider: elOf("maneuver-aggressivity-slider", isHtmlInputElement),
    maneuverAggressivityValue: el("maneuver-aggressivity-value"),
    initialDistance: elOf("initial-distance", isHtmlInputElement),
    targetHull: elOf("target-hull", isHtmlInputElement),
    targetShipImage: elOf("target-ship-image", isHtmlImageElement),
    targetFittingTrigger: elOf("target-fitting-trigger", isHtmlButtonElement),
    targetFittingEye: elOf("target-fitting-eye", isHtmlButtonElement),
    targetFittingPopup: el("target-fitting-popup"),
    targetFittingPreview: el("target-fitting-preview"),
    targetFittingSavedLabel: el("target-fitting-saved-label"),
    targetFittingSavedList: el("target-fitting-saved-list"),
    targetFittingPresetLabel: el("target-fitting-preset-label"),
    targetFittingPresetList: el("target-fitting-preset-list"),
    targetFittingEmpty: el("target-fitting-empty"),
    targetHullHint: el("target-hull-hint"),
    targetFittingName: el("target-fitting-name"),
    targetImportFitting: elOf("target-import-fitting", isHtmlButtonElement),
    targetPastePopup: el("target-paste-popup"),
    targetPasteInput: elOf("target-paste-input", isHtmlTextAreaElement),
    targetPropulsion: elOf("target-propulsion", isHtmlSelectElement),
    targetPropulsionOptions: el("target-propulsion-options"),
    targetPropulsionGear: elOf("target-propulsion-gear", isHtmlButtonElement),
    targetPropulsionVariants: el("target-propulsion-variants"),
    targetSkills: elOf("target-skills", isHtmlSelectElement),
    targetSkillOptions: el("target-skill-options"),
    targetSkillSummary: el("target-skill-summary"),
    targetSkillTrigger: elOf("target-skill-trigger", isHtmlButtonElement),
    targetSkillPopup: el("target-skill-popup"),
    targetOverload: elOf("target-overload", isHtmlInputElement),
    targetOverloadButton: elOf("target-overload-button", isHtmlButtonElement),
    targetEwarTrigger: elOf("target-ewar-trigger", isHtmlButtonElement),
    targetEwarPopup: el("target-ewar-popup"),
    targetEwarSummary: el("target-ewar-summary"),
    targetSpeed: elOf("target-speed", isHtmlInputElement),
    targetMass: elOf("target-mass", isHtmlInputElement),
    targetInertia: elOf("target-inertia", isHtmlInputElement),
    targetAlignTime: el("target-align-time"),
    targetMode: elOf("target-mode", isHtmlSelectElement),
    targetRange: elOf("target-range", isHtmlInputElement),
    targetSig: elOf("target-sig", isHtmlInputElement),
    simSpeed: elOf("sim-speed", isHtmlSelectElement),
    profileSave: elOf("profile-save", isHtmlButtonElement),
    profileSelect: elOf("profile-select", isHtmlSelectElement),
    profileDelete: elOf("profile-delete", isHtmlButtonElement),
    profileNew: elOf("profile-new", isHtmlButtonElement),
    newProfilePopup: el("new-profile-popup"),
    newProfileName: elOf("new-profile-name", isHtmlInputElement),
    newProfileConfirm: elOf("new-profile-confirm", isHtmlButtonElement),
    newProfileCancel: elOf("new-profile-cancel", isHtmlButtonElement),
    confirmPopup: el("confirm-popup"),
    confirmMessage: el("confirm-message"),
    confirmOk: elOf("confirm-ok", isHtmlButtonElement),
    confirmCancel: elOf("confirm-cancel", isHtmlButtonElement),
    shareLink: elOf("share-link", isHtmlButtonElement),
    sharePopup: el("share-popup"),
    shareCopyUrl: elOf("share-copy-url", isHtmlButtonElement),
    shareCopyText: elOf("share-copy-text", isHtmlButtonElement),
    importProfile: elOf("import-profile", isHtmlButtonElement),
    importSidePopup: el("import-side-popup"),
    importSideAttacker: elOf("import-side-attacker", isHtmlButtonElement),
    importSideTarget: elOf("import-side-target", isHtmlButtonElement),
    shareStatus: el("share-status"),
    langEn: elOf("lang-en", isHtmlButtonElement),
    langZh: elOf("lang-zh", isHtmlButtonElement),
    langJa: elOf("lang-ja", isHtmlButtonElement),
    play: elOf("play", isHtmlButtonElement),
    reset: elOf("reset", isHtmlButtonElement),
    gridBrightnessSlider: elOf("grid-brightness-slider", isHtmlInputElement),
    gridBrightnessValue: el("grid-brightness-value"),
    slideHints: el("slide-hints"),
    resDistance: el("res-distance"),
    resTransversal: el("res-transversal"),
    resAngular: el("res-angular"),
    resRadial: el("res-radial"),
    resTrackPen: el("res-track-pen"),
    resRangePen: el("res-range-pen"),
    resHit: el("res-hit"),
  };
}
