import type {
  ChargeStats,
  DisruptionScriptStats,
  DroneSizeClass,
  DroneStats,
  FittingDbData,
  FittingModuleStats,
  FittingPropulsionStats,
  HullBonus,
  HullBonusAttribute,
  LauncherStats,
  MissileGuidanceComputerStats,
  MissileGuidanceEnhancerStats,
  MissileScriptStats,
  MissileStats,
  OmnidirectionalTrackingEnhancerStats,
  OmnidirectionalTrackingLinkStats,
  SensorBoosterScriptStats,
  SensorBoosterStats,
  SensorDampenerScriptStats,
  SensorDampenerStats,
  SignalAmplifierStats,
  SkillBonus,
  SkillBonusType,
  StasisGrapplerStats,
  StasisWebStats,
  TargetPainterStats,
  TrackingComputerStats,
  TrackingDisruptorStats,
  TurretScriptStats,
  TurretStats,
  TurretWeaponGroup,
  WarpScramblerStats,
} from "./types";
import {
  CHARGES,
  COMBAT_DRONES,
  DISRUPTION_SCRIPTS,
  DRONES,
  FITTING_MODULES,
  HULL_BONUSES,
  LAUNCHERS,
  MISSILES,
  MISSILE_GUIDANCE_COMPUTERS,
  MISSILE_GUIDANCE_ENHANCERS,
  MISSILE_SCRIPTS,
  OMNIDIRECTIONAL_TRACKING_ENHANCERS,
  OMNIDIRECTIONAL_TRACKING_LINKS,
  SCRIPTS,
  SENSOR_BOOSTER_SCRIPTS,
  SENSOR_BOOSTERS,
  SENSOR_DAMPENER_SCRIPTS,
  SENSOR_DAMPENERS,
  SIGNAL_AMPLIFIERS,
  SKILL_BONUSES,
  STASIS_GRAPPLERS,
  STASIS_WEBS,
  TARGET_PAINTERS,
  TRACKING_COMPUTERS,
  TRACKING_DISRUPTORS,
  TURRETS,
  WARP_SCRAMBLERS,
} from "./generated/fittingDb.data";

export type {
  ChargeStats,
  DisruptionScriptStats,
  DroneSizeClass,
  DroneStats,
  FittingModuleStats,
  FittingPropulsionStats,
  HullBonus,
  HullBonusAttribute,
  LauncherStats,
  MissileGuidanceComputerStats,
  MissileGuidanceEnhancerStats,
  MissileScriptStats,
  MissileStats,
  OmnidirectionalTrackingEnhancerStats,
  OmnidirectionalTrackingLinkStats,
  SensorBoosterScriptStats,
  SensorBoosterStats,
  SensorDampenerScriptStats,
  SensorDampenerStats,
  SignalAmplifierStats,
  SkillBonus,
  SkillBonusType,
  StasisGrapplerStats,
  StasisWebStats,
  TargetPainterStats,
  TrackingComputerStats,
  TrackingDisruptorStats,
  TurretScriptStats,
  TurretStats,
  TurretWeaponGroup,
  WarpScramblerStats,
} from "./types";

export type { FittingDbData, FittingDb } from "./types";

export const FITTING_DB: FittingDbData = {
  modules: FITTING_MODULES,
  turrets: TURRETS,
  charges: CHARGES,
  launchers: LAUNCHERS,
  missiles: MISSILES,
  scripts: SCRIPTS,
  stasisWebs: STASIS_WEBS,
  stasisGrapplers: STASIS_GRAPPLERS,
  trackingComputers: TRACKING_COMPUTERS,
  trackingDisruptors: TRACKING_DISRUPTORS,
  warpScramblers: WARP_SCRAMBLERS,
  disruptionScripts: DISRUPTION_SCRIPTS,
  targetPainters: TARGET_PAINTERS,
  missileGuidanceComputers: MISSILE_GUIDANCE_COMPUTERS,
  missileGuidanceEnhancers: MISSILE_GUIDANCE_ENHANCERS,
  missileScripts: MISSILE_SCRIPTS,
  omnidirectionalTrackingLinks: OMNIDIRECTIONAL_TRACKING_LINKS,
  omnidirectionalTrackingEnhancers: OMNIDIRECTIONAL_TRACKING_ENHANCERS,
  sensorDampeners: SENSOR_DAMPENERS,
  sensorBoosters: SENSOR_BOOSTERS,
  signalAmplifiers: SIGNAL_AMPLIFIERS,
  sensorBoosterScripts: SENSOR_BOOSTER_SCRIPTS,
  sensorDampenerScripts: SENSOR_DAMPENER_SCRIPTS,
  hullBonuses: HULL_BONUSES,
  skillBonuses: SKILL_BONUSES,
  drones: DRONES,
  combatDrones: COMBAT_DRONES,
};
