import type { TypeId } from "../ids";

export type ModuleSlot = "high" | "mid" | "low" | "rig";

export const MODULE_SLOTS_BY_NAME: Readonly<Record<string, ModuleSlot>> = {
  "'Abatis' 100mm Steel Plates": "low",
  "'Arquebus' Heavy Beam Laser I": "high",
  "'Bailey' 1600mm Steel Plates": "low",
  "'Ballista' Tachyon Beam Laser I": "high",
  "'Barbican' 800mm Steel Plates": "low",
  "'Basic' Inertial Stabilizers": "low",
  "'Basic' Nanofiber Internal Structure": "low",
  "'Basic' Overdrive Injector System": "low",
  "'Basic' Reinforced Bulkheads": "low",
  "'Basic' Tracking Enhancer": "low",
  "'Bastion' 400mm Steel Plates": "low",
  "'Catapult' Mega Beam Laser I": "high",
  "'Chainmail' 200mm Steel Plates": "low",
  "'Citadella' 100mm Steel Plates": "low",
  "'Corporate' Light Electron Blaster I": "high",
  "'Crossbow' Focused Medium Beam Laser I": "high",
  "'Dealer' Light Ion Blaster I": "high",
  "'Delineative' Warp Scrambler": "mid",
  "'Felon' Ion Blaster Cannon I": "high",
  "'Gauntlet' Small Focused Beam Laser I": "high",
  "'Halberd' Mega Pulse Laser I": "high",
  "'Hooligan' Heavy Ion Blaster I": "high",
  "'Hustler' Heavy Neutron Blaster I": "high",
  "'Investor' Tracking Disruptor I": "mid",
  "'Joust' Heavy Pulse Laser I": "high",
  "'Longbow' Small Focused Pulse Laser I": "high",
  "'Mace' Dual Light Beam Laser I": "high",
  "'Marketeer' Tracking Computer": "mid",
  "'Racket' Light Neutron Blaster I": "high",
  "'Slither' Heavy Electron Blaster I": "high",
  "'Swindler' Electron Blaster Cannon I": "high",
  "'Underhand' Neutron Blaster Cannon I": "high",
  "10000MN Abyssal Afterburner": "mid",
  "10000MN Afterburner I": "mid",
  "10000MN Afterburner II": "mid",
  "10000MN Monopropellant Enduring Afterburner": "mid",
  "10000MN Y-S8 Compact Afterburner": "mid",
  "100MN Abyssal Afterburner": "mid",
  "100MN Afterburner I": "mid",
  "100MN Afterburner II": "mid",
  "100MN Analog Booster Afterburner": "mid",
  "100MN Monopropellant Enduring Afterburner": "mid",
  "100MN Y-S8 Compact Afterburner": "mid",
  "100mm Crystalline Carbonide Restrained Plates": "low",
  "100mm Rolled Tungsten Compact Plates": "low",
  "100mm Steel Plates I": "low",
  "100mm Steel Plates II": "low",
  "10MN Abyssal Afterburner": "mid",
  "10MN Afterburner I": "mid",
  "10MN Afterburner II": "mid",
  "10MN Analog Booster Afterburner": "mid",
  "10MN Monopropellant Enduring Afterburner": "mid",
  "10MN Y-S8 Compact Afterburner": "mid",
  "1200mm Artillery Cannon I": "high",
  "1200mm Artillery Cannon II": "high",
  "1200mm Heavy 'Jolt' Artillery I": "high",
  "1200mm Heavy 'Scout' Artillery I": "high",
  "1200mm Heavy Carbine Howitzer I": "high",
  "1200mm Heavy Gallium Cannon": "high",
  "1200mm Heavy Prototype Siege Cannon": "high",
  "125mm 'Scout' Accelerator Cannon": "high",
  "125mm Carbide Railgun I": "high",
  "125mm Compressed Coil Gun I": "high",
  "125mm Gatling AutoCannon I": "high",
  "125mm Gatling AutoCannon II": "high",
  "125mm Light 'Scout' Autocannon I": "high",
  "125mm Light Carbine Repeating Cannon I": "high",
  "125mm Light Gallium Machine Gun": "high",
  "125mm Light Prototype Automatic Cannon": "high",
  "125mm Prototype Gauss Gun": "high",
  "125mm Railgun I": "high",
  "125mm Railgun II": "high",
  "1400mm 'Jolt' Artillery I": "high",
  "1400mm 'Scout' Artillery I": "high",
  "1400mm Carbine Howitzer I": "high",
  "1400mm Gallium Cannon": "high",
  "1400mm Howitzer Artillery I": "high",
  "1400mm Howitzer Artillery II": "high",
  "1400mm Prototype Siege Cannon": "high",
  "150mm 'Musket' Railgun": "high",
  "150mm 'Scout' Accelerator Cannon": "high",
  "150mm Carbide Railgun I": "high",
  "150mm Compressed Coil Gun I": "high",
  "150mm Light 'Scout' Autocannon I": "high",
  "150mm Light AutoCannon I": "high",
  "150mm Light AutoCannon II": "high",
  "150mm Light Carbine Repeating Cannon I": "high",
  "150mm Light Gallium Machine Gun": "high",
  "150mm Light Prototype Automatic Cannon": "high",
  "150mm Prototype Gauss Gun": "high",
  "150mm Railgun I": "high",
  "150mm Railgun II": "high",
  "1600mm Crystalline Carbonide Restrained Plates": "low",
  "1600mm Rolled Tungsten Compact Plates": "low",
  "1600mm Steel Plates I": "low",
  "1600mm Steel Plates II": "low",
  "1MN Abyssal Afterburner": "mid",
  "1MN Afterburner I": "mid",
  "1MN Afterburner II": "mid",
  "1MN Analog Booster Afterburner": "mid",
  "1MN Civilian Afterburner": "mid",
  "1MN Monopropellant Enduring Afterburner": "mid",
  "1MN Y-S8 Compact Afterburner": "mid",
  "200mm 'Scout' Accelerator Cannon": "high",
  "200mm AutoCannon I": "high",
  "200mm AutoCannon II": "high",
  "200mm Carbide Railgun I": "high",
  "200mm Compressed Coil Gun I": "high",
  "200mm Crystalline Carbonide Restrained Plates": "low",
  "200mm Light 'Jolt' Autocannon I": "high",
  "200mm Light 'Scout' Autocannon I": "high",
  "200mm Light Carbine Repeating Cannon I": "high",
  "200mm Light Gallium Machine Gun": "high",
  "200mm Light Prototype Automatic Cannon": "high",
  "200mm Prototype Gauss Gun": "high",
  "200mm Railgun I": "high",
  "200mm Railgun II": "high",
  "200mm Rolled Tungsten Compact Plates": "low",
  "200mm Steel Plates I": "low",
  "200mm Steel Plates II": "low",
  "220mm Medium 'Scout' Autocannon I": "high",
  "220mm Medium Carbine Repeating Cannon I": "high",
  "220mm Medium Gallium Machine Gun": "high",
  "220mm Medium Prototype Automatic Cannon": "high",
  "220mm Vulcan AutoCannon I": "high",
  "220mm Vulcan AutoCannon II": "high",
  "25000mm Crystalline Carbonide Restrained Plates": "low",
  "25000mm Rolled Tungsten Compact Plates": "low",
  "25000mm Steel Plates I": "low",
  "25000mm Steel Plates II": "low",
  "250mm 'Flintlock' Railgun": "high",
  "250mm 'Scout' Accelerator Cannon": "high",
  "250mm Carbide Railgun I": "high",
  "250mm Compressed Coil Gun I": "high",
  "250mm Light 'Jolt' Artillery I": "high",
  "250mm Light 'Scout' Artillery I": "high",
  "250mm Light Artillery Cannon I": "high",
  "250mm Light Artillery Cannon II": "high",
  "250mm Light Carbine Howitzer I": "high",
  "250mm Light Gallium Cannon": "high",
  "250mm Light Prototype Siege Cannon": "high",
  "250mm Prototype Gauss Gun": "high",
  "250mm Railgun I": "high",
  "250mm Railgun II": "high",
  "280mm 'Jolt' Artillery I": "high",
  "280mm 'Scout' Artillery I": "high",
  "280mm Carbine Howitzer I": "high",
  "280mm Gallium Cannon": "high",
  "280mm Howitzer Artillery I": "high",
  "280mm Howitzer Artillery II": "high",
  "280mm Prototype Siege Cannon": "high",
  "350mm 'Scout' Accelerator Cannon": "high",
  "350mm Carbide Railgun I": "high",
  "350mm Compressed Coil Gun I": "high",
  "350mm Prototype Gauss Gun": "high",
  "350mm Railgun I": "high",
  "350mm Railgun II": "high",
  "400mm Crystalline Carbonide Restrained Plates": "low",
  "400mm Rolled Tungsten Compact Plates": "low",
  "400mm Steel Plates I": "low",
  "400mm Steel Plates II": "low",
  "425mm 'Popper' Railgun": "high",
  "425mm 'Scout' Accelerator Cannon": "high",
  "425mm AutoCannon I": "high",
  "425mm AutoCannon II": "high",
  "425mm Carbide Railgun I": "high",
  "425mm Compressed Coil Gun I": "high",
  "425mm Medium 'Jolt' Autocannon I": "high",
  "425mm Medium 'Scout' Autocannon I": "high",
  "425mm Medium Carbine Repeating Cannon I": "high",
  "425mm Medium Gallium Machine Gun": "high",
  "425mm Medium Prototype Automatic Cannon": "high",
  "425mm Prototype Gauss Gun": "high",
  "425mm Railgun I": "high",
  "425mm Railgun II": "high",
  "50000MN Abyssal Microwarpdrive": "mid",
  "50000MN Cold-Gas Enduring Microwarpdrive": "mid",
  "50000MN Microwarpdrive I": "mid",
  "50000MN Microwarpdrive II": "mid",
  "50000MN Quad LiF Restrained Microwarpdrive": "mid",
  "50000MN Y-T8 Compact Microwarpdrive": "mid",
  "500MN Abyssal Microwarpdrive": "mid",
  "500MN Cold-Gas Enduring Microwarpdrive": "mid",
  "500MN Digital Booster Microwarpdrive": "mid",
  "500MN Microwarpdrive I": "mid",
  "500MN Microwarpdrive II": "mid",
  "500MN Quad LiF Restrained Microwarpdrive": "mid",
  "500MN Y-T8 Compact Microwarpdrive": "mid",
  "50MN Abyssal Microwarpdrive": "mid",
  "50MN Cold-Gas Enduring Microwarpdrive": "mid",
  "50MN Digital Booster Microwarpdrive": "mid",
  "50MN Microwarpdrive I": "mid",
  "50MN Microwarpdrive II": "mid",
  "50MN Quad LiF Restrained Microwarpdrive": "mid",
  "50MN Y-T8 Compact Microwarpdrive": "mid",
  "5MN Abyssal Microwarpdrive": "mid",
  "5MN Cold-Gas Enduring Microwarpdrive": "mid",
  "5MN Digital Booster Microwarpdrive": "mid",
  "5MN Microwarpdrive I": "mid",
  "5MN Microwarpdrive II": "mid",
  "5MN Quad LiF Restrained Microwarpdrive": "mid",
  "5MN Y-T8 Compact Microwarpdrive": "mid",
  "650mm Artillery Cannon I": "high",
  "650mm Artillery Cannon II": "high",
  "650mm Medium 'Jolt' Artillery I": "high",
  "650mm Medium 'Scout' Artillery I": "high",
  "650mm Medium Carbine Howitzer I": "high",
  "650mm Medium Gallium Cannon": "high",
  "650mm Medium Prototype Siege Cannon": "high",
  "720mm 'Jolt' Artillery I": "high",
  "720mm 'Scout' Artillery I": "high",
  "720mm Carbine Howitzer I": "high",
  "720mm Gallium Cannon": "high",
  "720mm Howitzer Artillery I": "high",
  "720mm Howitzer Artillery II": "high",
  "720mm Prototype Siege Cannon": "high",
  "75mm 'Scout' Accelerator Cannon": "high",
  "75mm Carbide Railgun I": "high",
  "75mm Compressed Coil Gun I": "high",
  "75mm Gatling Rail I": "high",
  "75mm Gatling Rail II": "high",
  "75mm Prototype Gauss Gun": "high",
  "800mm Crystalline Carbonide Restrained Plates": "low",
  "800mm Heavy 'Jolt' Repeating Cannon I": "high",
  "800mm Heavy 'Scout' Repeating Cannon I": "high",
  "800mm Heavy Carbine Repeating Cannon I": "high",
  "800mm Heavy Gallium Repeating Cannon": "high",
  "800mm Heavy Prototype Automatic Cannon": "high",
  "800mm Repeating Cannon I": "high",
  "800mm Repeating Cannon II": "high",
  "800mm Rolled Tungsten Compact Plates": "low",
  "800mm Steel Plates I": "low",
  "800mm Steel Plates II": "low",
  "Afocal Precise Dual Giga Beam Laser": "high",
  "Afocal Precise Dual Giga Pulse Laser": "high",
  "Afocal Precise Quad Mega Pulse Laser": "high",
  "Ahremen's Modified Dual Heavy Pulse Laser": "high",
  "Ahremen's Modified Mega Pulse Laser": "high",
  "Ammatar Navy Dual Heavy Beam Laser": "high",
  "Ammatar Navy Dual Heavy Pulse Laser": "high",
  "Ammatar Navy Dual Light Beam Laser": "high",
  "Ammatar Navy Dual Light Pulse Laser": "high",
  "Ammatar Navy Focused Medium Beam Laser": "high",
  "Ammatar Navy Focused Medium Pulse Laser": "high",
  "Ammatar Navy Gatling Pulse Laser": "high",
  "Ammatar Navy Heavy Beam Laser": "high",
  "Ammatar Navy Heavy Pulse Laser": "high",
  "Ammatar Navy Mega Beam Laser": "high",
  "Ammatar Navy Mega Pulse Laser": "high",
  "Ammatar Navy Quad Beam Laser": "high",
  "Ammatar Navy Small Focused Beam Laser": "high",
  "Ammatar Navy Small Focused Pulse Laser": "high",
  "Ammatar Navy Tachyon Beam Laser": "high",
  "Ample Gallium Quad 800mm Repeating Cannon": "high",
  "Anode Electron Particle Cannon I": "high",
  "Anode Ion Particle Cannon I": "high",
  "Anode Light Electron Particle Cannon I": "high",
  "Anode Light Ion Particle Cannon I": "high",
  "Anode Light Neutron Particle Cannon I": "high",
  "Anode Mega Electron Particle Cannon I": "high",
  "Anode Mega Ion Particle Cannon I": "high",
  "Anode Mega Neutron Particle Cannon I": "high",
  "Anode Neutron Particle Cannon I": "high",
  "Anode Scoped Dual Giga Beam Laser": "high",
  "Anode Scoped Dual Giga Pulse Laser": "high",
  "Anode Scoped Ion Siege Blaster": "high",
  "Anode Scoped Quad Mega Pulse Laser": "high",
  "Anode Scoped Triple Neutron Blaster Cannon": "high",
  "Asine's Modified 1MN Afterburner": "mid",
  "Asine's Modified 5MN Microwarpdrive": "mid",
  "Asine's Modified Light Neutron Blaster": "high",
  "Baker Nunn Enduring Tracking Disruptor I": "mid",
  "Balmer Series Compact Tracking Disruptor I": "mid",
  "Brokara's Modified Dual Heavy Pulse Laser": "high",
  "Brokara's Modified Mega Pulse Laser": "high",
  "Brynn's Modified 100MN Afterburner": "mid",
  "Brynn's Modified 350mm Railgun": "high",
  "Brynn's Modified 425mm Railgun": "high",
  "Brynn's Modified 500MN Microwarpdrive": "mid",
  "Brynn's Modified Dual 250mm Railgun": "high",
  "Brynn's Modified Tracking Computer": "mid",
  "CONCORD 25000mm Steel Plates": "low",
  "CONCORD Capital Shield Extender": "mid",
  "CONCORD Dual 1000mm Railgun": "high",
  "CONCORD Dual Giga Beam Laser": "high",
  "CONCORD Dual Giga Pulse Laser": "high",
  "CONCORD Hexa 2500mm Repeating Cannon": "high",
  "CONCORD Ion Siege Blaster": "high",
  "CONCORD Quad 3500mm Siege Artillery": "high",
  "Caldari Navy 125mm Railgun": "high",
  "Caldari Navy 150mm Railgun": "high",
  "Caldari Navy 200mm Railgun": "high",
  "Caldari Navy 250mm Railgun": "high",
  "Caldari Navy 350mm Railgun": "high",
  "Caldari Navy 425mm Railgun": "high",
  "Caldari Navy 75mm Railgun": "high",
  "Caldari Navy Dual 150mm Railgun": "high",
  "Caldari Navy Dual 250mm Railgun": "high",
  "Caldari Navy Large Shield Extender": "mid",
  "Caldari Navy Medium Shield Extender": "mid",
  "Caldari Navy Small Shield Extender": "mid",
  "Caldari Navy Stasis Webifier": "mid",
  "Caldari Navy Warp Scrambler": "mid",
  "Capital Auxiliary Thrusters I": "rig",
  "Capital Auxiliary Thrusters II": "rig",
  "Capital Azeotropic Restrained Shield Extender": "mid",
  "Capital Core Defense Capacitor Safeguard I": "rig",
  "Capital Core Defense Capacitor Safeguard II": "rig",
  "Capital Core Defense Charge Economizer I": "rig",
  "Capital Core Defense Charge Economizer II": "rig",
  "Capital Core Defense Field Extender I": "rig",
  "Capital Core Defense Field Extender II": "rig",
  "Capital Core Defense Field Purger I": "rig",
  "Capital Core Defense Field Purger II": "rig",
  "Capital Core Defense Operational Solidifier I": "rig",
  "Capital Core Defense Operational Solidifier II": "rig",
  "Capital EM Armor Reinforcer I": "rig",
  "Capital EM Armor Reinforcer II": "rig",
  "Capital EM Shield Reinforcer I": "rig",
  "Capital EM Shield Reinforcer II": "rig",
  "Capital Energy Ambit Extension I": "rig",
  "Capital Energy Ambit Extension II": "rig",
  "Capital Energy Locus Coordinator I": "rig",
  "Capital Energy Locus Coordinator II": "rig",
  "Capital Energy Metastasis Adjuster I": "rig",
  "Capital Energy Metastasis Adjuster II": "rig",
  "Capital Explosive Armor Reinforcer I": "rig",
  "Capital Explosive Armor Reinforcer II": "rig",
  "Capital Explosive Shield Reinforcer I": "rig",
  "Capital Explosive Shield Reinforcer II": "rig",
  "Capital F-S9 Regolith Compact Shield Extender": "mid",
  "Capital Higgs Anchor I": "rig",
  "Capital Hybrid Ambit Extension I": "rig",
  "Capital Hybrid Ambit Extension II": "rig",
  "Capital Hybrid Locus Coordinator I": "rig",
  "Capital Hybrid Locus Coordinator II": "rig",
  "Capital Hybrid Metastasis Adjuster I": "rig",
  "Capital Hybrid Metastasis Adjuster II": "rig",
  "Capital Hyperspatial Velocity Optimizer I": "rig",
  "Capital Hyperspatial Velocity Optimizer II": "rig",
  "Capital Kinetic Armor Reinforcer I": "rig",
  "Capital Kinetic Armor Reinforcer II": "rig",
  "Capital Kinetic Shield Reinforcer I": "rig",
  "Capital Kinetic Shield Reinforcer II": "rig",
  "Capital Low Friction Nozzle Joints I": "rig",
  "Capital Low Friction Nozzle Joints II": "rig",
  "Capital Polycarbon Engine Housing I": "rig",
  "Capital Polycarbon Engine Housing II": "rig",
  "Capital Projectile Ambit Extension I": "rig",
  "Capital Projectile Ambit Extension II": "rig",
  "Capital Projectile Locus Coordinator I": "rig",
  "Capital Projectile Locus Coordinator II": "rig",
  "Capital Projectile Metastasis Adjuster I": "rig",
  "Capital Projectile Metastasis Adjuster II": "rig",
  "Capital Remote Repair Augmentor I": "rig",
  "Capital Remote Repair Augmentor II": "rig",
  "Capital Shield Extender I": "mid",
  "Capital Shield Extender II": "mid",
  "Capital Thermal Armor Reinforcer I": "rig",
  "Capital Thermal Armor Reinforcer II": "rig",
  "Capital Thermal Shield Reinforcer I": "rig",
  "Capital Thermal Shield Reinforcer II": "rig",
  "Capital Trimark Armor Pump I": "rig",
  "Capital Trimark Armor Pump II": "rig",
  "Capital Warp Core Optimizer I": "rig",
  "Capital Warp Core Optimizer II": "rig",
  "Carbide Compact Dual 1000mm Railgun": "high",
  "Carbide Compact Quad 3500mm Siege Artillery": "high",
  "Carbine Compact Hexa 2500mm Repeating Cannon": "high",
  "Chelm's Modified Dual Heavy Beam Laser": "high",
  "Chelm's Modified Mega Beam Laser": "high",
  "Chelm's Modified Tachyon Beam Laser": "high",
  "Civilian Stasis Webifier": "mid",
  "Compact Carbine Quad 800mm Repeating Cannon": "high",
  "Compressed Enduring Dual 1000mm Railgun": "high",
  "Core A-Type 100MN Afterburner": "mid",
  "Core A-Type 500MN Microwarpdrive": "mid",
  "Core B-Type 100MN Afterburner": "mid",
  "Core B-Type 500MN Microwarpdrive": "mid",
  "Core C-Type 100MN Afterburner": "mid",
  "Core C-Type 500MN Microwarpdrive": "mid",
  "Core X-Type 100MN Afterburner": "mid",
  "Core X-Type 500MN Microwarpdrive": "mid",
  "Coreli A-Type 1MN Afterburner": "mid",
  "Coreli A-Type 5MN Microwarpdrive": "mid",
  "Coreli B-Type 1MN Afterburner": "mid",
  "Coreli B-Type 5MN Microwarpdrive": "mid",
  "Coreli C-Type 1MN Afterburner": "mid",
  "Coreli C-Type 5MN Microwarpdrive": "mid",
  "Corelum A-Type 10MN Afterburner": "mid",
  "Corelum A-Type 50MN Microwarpdrive": "mid",
  "Corelum B-Type 10MN Afterburner": "mid",
  "Corelum B-Type 50MN Microwarpdrive": "mid",
  "Corelum C-Type 10MN Afterburner": "mid",
  "Corelum C-Type 50MN Microwarpdrive": "mid",
  "Cormack's Modified 100MN Afterburner": "mid",
  "Cormack's Modified 500MN Microwarpdrive": "mid",
  "Cormack's Modified Electron Blaster Cannon": "high",
  "Cormack's Modified Ion Blaster Cannon": "high",
  "Cormack's Modified Neutron Blaster Cannon": "high",
  "Cormack's Modified Tracking Computer": "mid",
  "DDO Scoped Tracking Disruptor I": "mid",
  "Dark Blood 25000mm Steel Plates": "low",
  "Dark Blood Dual Giga Beam Laser": "high",
  "Dark Blood Dual Giga Pulse Laser": "high",
  "Dark Blood Dual Heavy Beam Laser": "high",
  "Dark Blood Dual Heavy Pulse Laser": "high",
  "Dark Blood Dual Light Beam Laser": "high",
  "Dark Blood Dual Light Pulse Laser": "high",
  "Dark Blood Focused Medium Beam Laser": "high",
  "Dark Blood Focused Medium Pulse Laser": "high",
  "Dark Blood Gatling Pulse Laser": "high",
  "Dark Blood Heavy Beam Laser": "high",
  "Dark Blood Heavy Pulse Laser": "high",
  "Dark Blood Mega Beam Laser": "high",
  "Dark Blood Mega Pulse Laser": "high",
  "Dark Blood Quad Beam Laser": "high",
  "Dark Blood Quad Mega Pulse Laser": "high",
  "Dark Blood Small Focused Beam Laser": "high",
  "Dark Blood Small Focused Pulse Laser": "high",
  "Dark Blood Stasis Webifier": "mid",
  "Dark Blood Tachyon Beam Laser": "high",
  "Dark Blood Warp Scrambler": "mid",
  "Domination 10000MN Afterburner": "mid",
  "Domination 100MN Afterburner": "mid",
  "Domination 10MN Afterburner": "mid",
  "Domination 1200mm Artillery": "high",
  "Domination 125mm Autocannon": "high",
  "Domination 1400mm Howitzer Artillery": "high",
  "Domination 150mm Autocannon": "high",
  "Domination 1MN Afterburner": "mid",
  "Domination 200mm Autocannon": "high",
  "Domination 220mm Autocannon": "high",
  "Domination 250mm Artillery": "high",
  "Domination 280mm Howitzer Artillery": "high",
  "Domination 425mm Autocannon": "high",
  "Domination 50000MN Microwarpdrive": "mid",
  "Domination 500MN Microwarpdrive": "mid",
  "Domination 50MN Microwarpdrive": "mid",
  "Domination 5MN Microwarpdrive": "mid",
  "Domination 650mm Artillery": "high",
  "Domination 720mm Howitzer Artillery": "high",
  "Domination 800mm Repeating Cannon": "high",
  "Domination Capital Shield Extender": "mid",
  "Domination Dual 180mm Autocannon": "high",
  "Domination Dual 425mm Autocannon": "high",
  "Domination Dual 650mm Repeating Cannon": "high",
  "Domination Heavy Stasis Grappler": "mid",
  "Domination Heavy Warp Scrambler": "mid",
  "Domination Hexa 2500mm Repeating Cannon": "high",
  "Domination Inertial Stabilizers": "low",
  "Domination Nanofiber Structure": "low",
  "Domination Overdrive Injector": "low",
  "Domination Quad 3500mm Siege Artillery": "high",
  "Domination Quad 800mm Repeating Cannon": "high",
  "Domination Stasis Webifier": "mid",
  "Domination Tracking Enhancer": "low",
  "Domination Warp Scrambler": "mid",
  "Draclira's Modified Dual Heavy Beam Laser": "high",
  "Draclira's Modified Mega Beam Laser": "high",
  "Draclira's Modified Tachyon Beam Laser": "high",
  "Dread Guristas 125mm Railgun": "high",
  "Dread Guristas 150mm Railgun": "high",
  "Dread Guristas 200mm Railgun": "high",
  "Dread Guristas 250mm Railgun": "high",
  "Dread Guristas 350mm Railgun": "high",
  "Dread Guristas 425mm Railgun": "high",
  "Dread Guristas 75mm Railgun": "high",
  "Dread Guristas Capital Shield Extender": "mid",
  "Dread Guristas Dual 150mm Railgun": "high",
  "Dread Guristas Dual 250mm Railgun": "high",
  "Dread Guristas Stasis Webifier": "mid",
  "Dread Guristas Warp Scrambler": "mid",
  "Dual 1000mm Railgun I": "high",
  "Dual 1000mm Railgun II": "high",
  "Dual 150mm 'Scout' Accelerator Cannon": "high",
  "Dual 150mm Carbide Railgun I": "high",
  "Dual 150mm Compressed Coil Gun I": "high",
  "Dual 150mm Prototype Gauss Gun": "high",
  "Dual 150mm Railgun I": "high",
  "Dual 150mm Railgun II": "high",
  "Dual 180mm 'Scout' Autocannon I": "high",
  "Dual 180mm AutoCannon I": "high",
  "Dual 180mm AutoCannon II": "high",
  "Dual 180mm Carbine Repeating Cannon I": "high",
  "Dual 180mm Gallium Machine Gun": "high",
  "Dual 180mm Prototype Automatic Cannon": "high",
  "Dual 250mm 'Scout' Accelerator Cannon": "high",
  "Dual 250mm Carbide Railgun I": "high",
  "Dual 250mm Compressed Coil Gun I": "high",
  "Dual 250mm Prototype Gauss Gun": "high",
  "Dual 250mm Railgun I": "high",
  "Dual 250mm Railgun II": "high",
  "Dual 425mm 'Scout' Autocannon I": "high",
  "Dual 425mm AutoCannon I": "high",
  "Dual 425mm AutoCannon II": "high",
  "Dual 425mm Carbine Repeating Cannon I": "high",
  "Dual 425mm Gallium Machine Gun": "high",
  "Dual 425mm Prototype Automatic Cannon": "high",
  "Dual 650mm 'Scout' Repeating Cannon I": "high",
  "Dual 650mm Carbine Repeating Cannon I": "high",
  "Dual 650mm Gallium Repeating Cannon": "high",
  "Dual 650mm Prototype Automatic Cannon": "high",
  "Dual 650mm Repeating Cannon I": "high",
  "Dual 650mm Repeating Cannon II": "high",
  "Dual Afocal Heavy Laser I": "high",
  "Dual Afocal Light Laser I": "high",
  "Dual Afocal Pulse Laser I": "high",
  "Dual Anode Heavy Particle Stream I": "high",
  "Dual Anode Light Particle Stream I": "high",
  "Dual Anode Pulse Particle Stream I": "high",
  "Dual Giga Beam Laser I": "high",
  "Dual Giga Beam Laser II": "high",
  "Dual Giga Pulse Laser I": "high",
  "Dual Giga Pulse Laser II": "high",
  "Dual Heavy Afocal Pulse Laser I": "high",
  "Dual Heavy Anode Pulse Particle Stream I": "high",
  "Dual Heavy Beam Laser I": "high",
  "Dual Heavy Beam Laser II": "high",
  "Dual Heavy Modal Pulse Laser I": "high",
  "Dual Heavy Modulated Pulse Energy Beam I": "high",
  "Dual Heavy Pulse Laser I": "high",
  "Dual Heavy Pulse Laser II": "high",
  "Dual Light Beam Laser I": "high",
  "Dual Light Beam Laser II": "high",
  "Dual Light Pulse Laser I": "high",
  "Dual Light Pulse Laser II": "high",
  "Dual Modal Heavy Laser I": "high",
  "Dual Modal Light Laser I": "high",
  "Dual Modal Pulse Laser I": "high",
  "Dual Modulated Heavy Energy Beam I": "high",
  "Dual Modulated Light Energy Beam I": "high",
  "Dual Modulated Pulse Energy Beam I": "high",
  "Electron Blaster Cannon I": "high",
  "Electron Blaster Cannon II": "high",
  "Estamel's Modified 350mm Railgun": "high",
  "Estamel's Modified 425mm Railgun": "high",
  "Estamel's Modified Dual 250mm Railgun": "high",
  "F-12 Enduring Tracking Computer": "mid",
  "Faint Epsilon Scoped Warp Scrambler": "mid",
  "Federation Navy 100MN Afterburner": "mid",
  "Federation Navy 100mm Steel Plates": "low",
  "Federation Navy 10MN Afterburner": "mid",
  "Federation Navy 125mm Railgun": "high",
  "Federation Navy 150mm Railgun": "high",
  "Federation Navy 1600mm Steel Plates": "low",
  "Federation Navy 1MN Afterburner": "mid",
  "Federation Navy 200mm Railgun": "high",
  "Federation Navy 200mm Steel Plates": "low",
  "Federation Navy 250mm Railgun": "high",
  "Federation Navy 350mm Railgun": "high",
  "Federation Navy 400mm Steel Plates": "low",
  "Federation Navy 425mm Railgun": "high",
  "Federation Navy 500MN Microwarpdrive": "mid",
  "Federation Navy 50MN Microwarpdrive": "mid",
  "Federation Navy 5MN Microwarpdrive": "mid",
  "Federation Navy 75mm Railgun": "high",
  "Federation Navy 800mm Steel Plates": "low",
  "Federation Navy Dual 150mm Railgun": "high",
  "Federation Navy Dual 250mm Railgun": "high",
  "Federation Navy Electron Blaster Cannon": "high",
  "Federation Navy Heavy Electron Blaster": "high",
  "Federation Navy Heavy Ion Blaster": "high",
  "Federation Navy Heavy Neutron Blaster": "high",
  "Federation Navy Ion Blaster Cannon": "high",
  "Federation Navy Light Electron Blaster": "high",
  "Federation Navy Light Ion Blaster": "high",
  "Federation Navy Light Neutron Blaster": "high",
  "Federation Navy Neutron Blaster Cannon": "high",
  "Federation Navy Stasis Webifier": "mid",
  "Federation Navy Tracking Computer": "mid",
  "Federation Navy Warp Scrambler": "mid",
  "Fleeting Compact Stasis Webifier": "mid",
  "Focused Afocal Medium Laser I": "high",
  "Focused Afocal Pulse Laser I": "high",
  "Focused Anode Medium Particle Stream I": "high",
  "Focused Anode Pulse Particle Stream I": "high",
  "Focused Medium Beam Laser I": "high",
  "Focused Medium Beam Laser II": "high",
  "Focused Medium Pulse Laser I": "high",
  "Focused Medium Pulse Laser II": "high",
  "Focused Modal Medium Laser I": "high",
  "Focused Modal Pulse Laser I": "high",
  "Focused Modulated Medium Energy Beam I": "high",
  "Focused Modulated Pulse Energy Beam I": "high",
  "Fourier Compact Tracking Enhancer": "low",
  "Gallium Ample Hexa 2500mm Repeating Cannon": "high",
  "Gallium Ample Quad 3500mm Siege Artillery": "high",
  "Gara's Modified 10MN Afterburner": "mid",
  "Gara's Modified 50MN Microwarpdrive": "mid",
  "Gara's Modified Heavy Neutron Blaster": "high",
  "Gatling Afocal Laser I": "high",
  "Gatling Anode Particle Stream I": "high",
  "Gatling Modal Laser I": "high",
  "Gatling Modulated Energy Beam I": "high",
  "Gatling Pulse Laser I": "high",
  "Gatling Pulse Laser II": "high",
  "Gist A-Type 100MN Afterburner": "mid",
  "Gist A-Type 500MN Microwarpdrive": "mid",
  "Gist B-Type 100MN Afterburner": "mid",
  "Gist B-Type 500MN Microwarpdrive": "mid",
  "Gist C-Type 100MN Afterburner": "mid",
  "Gist C-Type 500MN Microwarpdrive": "mid",
  "Gist X-Type 100MN Afterburner": "mid",
  "Gist X-Type 500MN Microwarpdrive": "mid",
  "Gistii A-Type 1MN Afterburner": "mid",
  "Gistii A-Type 5MN Microwarpdrive": "mid",
  "Gistii B-Type 1MN Afterburner": "mid",
  "Gistii B-Type 5MN Microwarpdrive": "mid",
  "Gistii C-Type 1MN Afterburner": "mid",
  "Gistii C-Type 5MN Microwarpdrive": "mid",
  "Gistum A-Type 10MN Afterburner": "mid",
  "Gistum A-Type 50MN Microwarpdrive": "mid",
  "Gistum B-Type 10MN Afterburner": "mid",
  "Gistum B-Type 50MN Microwarpdrive": "mid",
  "Gistum C-Type 10MN Afterburner": "mid",
  "Gistum C-Type 50MN Microwarpdrive": "mid",
  "Gotan's Modified 100MN Afterburner": "mid",
  "Gotan's Modified 500MN Microwarpdrive": "mid",
  "Gotan's Modified 800mm Repeating Cannon": "high",
  "Gotan's Modified Dual 425mm AutoCannon": "high",
  "Gotan's Modified Dual 650mm Repeating Cannon": "high",
  "Gotan's Modified Heavy Warp Scrambler": "mid",
  "Gotan's Modified Stasis Webifier": "mid",
  "Gotan's Modified Tracking Enhancer": "low",
  "Hakim's Modified 100MN Afterburner": "mid",
  "Hakim's Modified 1200mm Artillery Cannon": "high",
  "Hakim's Modified 1400mm Howitzer Artillery": "high",
  "Hakim's Modified 500MN Microwarpdrive": "mid",
  "Hakim's Modified Heavy Warp Scrambler": "mid",
  "Hakim's Modified Stasis Webifier": "mid",
  "Hakim's Modified Tracking Enhancer": "low",
  "Heavy Afocal Laser I": "high",
  "Heavy Afocal Pulse Laser I": "high",
  "Heavy Anode Particle Stream I": "high",
  "Heavy Anode Pulse Particle Stream I": "high",
  "Heavy Beam Laser I": "high",
  "Heavy Beam Laser II": "high",
  "Heavy Electron Blaster I": "high",
  "Heavy Electron Blaster II": "high",
  "Heavy Faint Epsilon Scoped Warp Scrambler": "mid",
  "Heavy Gunnar Compact Stasis Grappler": "mid",
  "Heavy Initiated Compact Warp Scrambler": "mid",
  "Heavy Ion Blaster I": "high",
  "Heavy Ion Blaster II": "high",
  "Heavy J5b Enduring Warp Scrambler": "mid",
  "Heavy Jigoro Enduring Stasis Grappler": "mid",
  "Heavy Karelin Scoped Stasis Grappler": "mid",
  "Heavy Modal Laser I": "high",
  "Heavy Modal Pulse Laser I": "high",
  "Heavy Modulated Energy Beam I": "high",
  "Heavy Modulated Pulse Energy Beam I": "high",
  "Heavy Neutron Blaster I": "high",
  "Heavy Neutron Blaster II": "high",
  "Heavy Pulse Laser I": "high",
  "Heavy Pulse Laser II": "high",
  "Heavy Stasis Grappler I": "mid",
  "Heavy Stasis Grappler II": "mid",
  "Heavy Warp Scrambler I": "mid",
  "Heavy Warp Scrambler II": "mid",
  "Hexa 2500mm Repeating Cannon I": "high",
  "Hexa 2500mm Repeating Cannon II": "high",
  "Imperial Navy 'Atonement' Tracking Enhancer": "low",
  "Imperial Navy 100mm Steel Plates": "low",
  "Imperial Navy 1600mm Steel Plates": "low",
  "Imperial Navy 200mm Steel Plates": "low",
  "Imperial Navy 400mm Steel Plates": "low",
  "Imperial Navy 800mm Steel Plates": "low",
  "Imperial Navy Dual Heavy Beam Laser": "high",
  "Imperial Navy Dual Heavy Pulse Laser": "high",
  "Imperial Navy Dual Light Beam Laser": "high",
  "Imperial Navy Dual Light Pulse Laser": "high",
  "Imperial Navy Focused Medium Beam Laser": "high",
  "Imperial Navy Focused Medium Pulse Laser": "high",
  "Imperial Navy Gatling Pulse Laser": "high",
  "Imperial Navy Heavy Beam Laser": "high",
  "Imperial Navy Heavy Pulse Laser": "high",
  "Imperial Navy Mega Beam Laser": "high",
  "Imperial Navy Mega Pulse Laser": "high",
  "Imperial Navy Quad Beam Laser": "high",
  "Imperial Navy Small Focused Beam Laser": "high",
  "Imperial Navy Small Focused Pulse Laser": "high",
  "Imperial Navy Tachyon Beam Laser": "high",
  "Inertial Stabilizers I": "low",
  "Inertial Stabilizers II": "low",
  "Initiated Compact Warp Scrambler": "mid",
  "Ion Blaster Cannon I": "high",
  "Ion Blaster Cannon II": "high",
  "Ion Siege Blaster I": "high",
  "Ion Siege Blaster II": "high",
  "J5b Enduring Warp Scrambler": "mid",
  "Kaikka's Modified 350mm Railgun": "high",
  "Kaikka's Modified 425mm Railgun": "high",
  "Kaikka's Modified Dual 250mm Railgun": "high",
  "Khanid Navy Stasis Webifier": "mid",
  "Khanid Navy Warp Scrambler": "mid",
  "Large 'Sheriff' Shield Extender": "mid",
  "Large Auxiliary Thrusters I": "rig",
  "Large Auxiliary Thrusters II": "rig",
  "Large Azeotropic Restrained Shield Extender": "mid",
  "Large Core Defense Capacitor Safeguard I": "rig",
  "Large Core Defense Capacitor Safeguard II": "rig",
  "Large Core Defense Charge Economizer I": "rig",
  "Large Core Defense Charge Economizer II": "rig",
  "Large Core Defense Field Extender I": "rig",
  "Large Core Defense Field Extender II": "rig",
  "Large Core Defense Field Purger I": "rig",
  "Large Core Defense Field Purger II": "rig",
  "Large Core Defense Operational Solidifier I": "rig",
  "Large Core Defense Operational Solidifier II": "rig",
  "Large EM Armor Reinforcer I": "rig",
  "Large EM Armor Reinforcer II": "rig",
  "Large EM Shield Reinforcer I": "rig",
  "Large EM Shield Reinforcer II": "rig",
  "Large Energy Ambit Extension I": "rig",
  "Large Energy Ambit Extension II": "rig",
  "Large Energy Locus Coordinator I": "rig",
  "Large Energy Locus Coordinator II": "rig",
  "Large Energy Metastasis Adjuster I": "rig",
  "Large Energy Metastasis Adjuster II": "rig",
  "Large Explosive Armor Reinforcer I": "rig",
  "Large Explosive Armor Reinforcer II": "rig",
  "Large Explosive Shield Reinforcer I": "rig",
  "Large Explosive Shield Reinforcer II": "rig",
  "Large F-S9 Regolith Compact Shield Extender": "mid",
  "Large Higgs Anchor I": "rig",
  "Large Hybrid Ambit Extension I": "rig",
  "Large Hybrid Ambit Extension II": "rig",
  "Large Hybrid Locus Coordinator I": "rig",
  "Large Hybrid Locus Coordinator II": "rig",
  "Large Hybrid Metastasis Adjuster I": "rig",
  "Large Hybrid Metastasis Adjuster II": "rig",
  "Large Hyperspatial Velocity Optimizer I": "rig",
  "Large Hyperspatial Velocity Optimizer II": "rig",
  "Large Kinetic Armor Reinforcer I": "rig",
  "Large Kinetic Armor Reinforcer II": "rig",
  "Large Kinetic Shield Reinforcer I": "rig",
  "Large Kinetic Shield Reinforcer II": "rig",
  "Large Low Friction Nozzle Joints I": "rig",
  "Large Low Friction Nozzle Joints II": "rig",
  "Large Polycarbon Engine Housing I": "rig",
  "Large Polycarbon Engine Housing II": "rig",
  "Large Projectile Ambit Extension I": "rig",
  "Large Projectile Ambit Extension II": "rig",
  "Large Projectile Locus Coordinator I": "rig",
  "Large Projectile Locus Coordinator II": "rig",
  "Large Projectile Metastasis Adjuster I": "rig",
  "Large Projectile Metastasis Adjuster II": "rig",
  "Large Remote Repair Augmentor I": "rig",
  "Large Remote Repair Augmentor II": "rig",
  "Large Shield Extender I": "mid",
  "Large Shield Extender II": "mid",
  "Large Thermal Armor Reinforcer I": "rig",
  "Large Thermal Armor Reinforcer II": "rig",
  "Large Thermal Shield Reinforcer I": "rig",
  "Large Thermal Shield Reinforcer II": "rig",
  "Large Trimark Armor Pump I": "rig",
  "Large Trimark Armor Pump II": "rig",
  "Large Warp Core Optimizer I": "rig",
  "Large Warp Core Optimizer II": "rig",
  "Light Electron Blaster I": "high",
  "Light Electron Blaster II": "high",
  "Light Ion Blaster I": "high",
  "Light Ion Blaster II": "high",
  "Light Neutron Blaster I": "high",
  "Light Neutron Blaster II": "high",
  "Limited Electron Blaster Cannon I": "high",
  "Limited Electron Blaster I": "high",
  "Limited Ion Blaster I": "high",
  "Limited Light Electron Blaster I": "high",
  "Limited Light Ion Blaster I": "high",
  "Limited Light Neutron Blaster I": "high",
  "Limited Mega Ion Blaster I": "high",
  "Limited Mega Neutron Blaster I": "high",
  "Limited Neutron Blaster I": "high",
  "Limited Precise Ion Siege Blaster": "high",
  "Limited Precise Triple Neutron Blaster Cannon": "high",
  "Lorharyth’s Modified Inertial Stabilizer": "low",
  "Makra's Modified Small Focused Pulse Laser": "high",
  "Mark I Compact Reinforced Bulkheads": "low",
  "Medium 'Canyon' Shield Extender": "mid",
  "Medium Auxiliary Thrusters I": "rig",
  "Medium Auxiliary Thrusters II": "rig",
  "Medium Azeotropic Restrained Shield Extender": "mid",
  "Medium Core Defense Capacitor Safeguard I": "rig",
  "Medium Core Defense Capacitor Safeguard II": "rig",
  "Medium Core Defense Charge Economizer I": "rig",
  "Medium Core Defense Charge Economizer II": "rig",
  "Medium Core Defense Field Extender I": "rig",
  "Medium Core Defense Field Extender II": "rig",
  "Medium Core Defense Field Purger I": "rig",
  "Medium Core Defense Field Purger II": "rig",
  "Medium Core Defense Operational Solidifier I": "rig",
  "Medium Core Defense Operational Solidifier II": "rig",
  "Medium EM Armor Reinforcer I": "rig",
  "Medium EM Armor Reinforcer II": "rig",
  "Medium EM Shield Reinforcer I": "rig",
  "Medium EM Shield Reinforcer II": "rig",
  "Medium Energy Ambit Extension I": "rig",
  "Medium Energy Ambit Extension II": "rig",
  "Medium Energy Locus Coordinator I": "rig",
  "Medium Energy Locus Coordinator II": "rig",
  "Medium Energy Metastasis Adjuster I": "rig",
  "Medium Energy Metastasis Adjuster II": "rig",
  "Medium Explosive Armor Reinforcer I": "rig",
  "Medium Explosive Armor Reinforcer II": "rig",
  "Medium Explosive Shield Reinforcer I": "rig",
  "Medium Explosive Shield Reinforcer II": "rig",
  "Medium F-S9 Regolith Compact Shield Extender": "mid",
  "Medium Higgs Anchor I": "rig",
  "Medium Hybrid Ambit Extension I": "rig",
  "Medium Hybrid Ambit Extension II": "rig",
  "Medium Hybrid Locus Coordinator I": "rig",
  "Medium Hybrid Locus Coordinator II": "rig",
  "Medium Hybrid Metastasis Adjuster I": "rig",
  "Medium Hybrid Metastasis Adjuster II": "rig",
  "Medium Hyperspatial Velocity Optimizer I": "rig",
  "Medium Hyperspatial Velocity Optimizer II": "rig",
  "Medium Kinetic Armor Reinforcer I": "rig",
  "Medium Kinetic Armor Reinforcer II": "rig",
  "Medium Kinetic Shield Reinforcer I": "rig",
  "Medium Kinetic Shield Reinforcer II": "rig",
  "Medium Low Friction Nozzle Joints I": "rig",
  "Medium Low Friction Nozzle Joints II": "rig",
  "Medium Polycarbon Engine Housing I": "rig",
  "Medium Polycarbon Engine Housing II": "rig",
  "Medium Projectile Ambit Extension I": "rig",
  "Medium Projectile Ambit Extension II": "rig",
  "Medium Projectile Locus Coordinator I": "rig",
  "Medium Projectile Locus Coordinator II": "rig",
  "Medium Projectile Metastasis Adjuster I": "rig",
  "Medium Projectile Metastasis Adjuster II": "rig",
  "Medium Remote Repair Augmentor I": "rig",
  "Medium Remote Repair Augmentor II": "rig",
  "Medium Shield Extender I": "mid",
  "Medium Shield Extender II": "mid",
  "Medium Thermal Armor Reinforcer I": "rig",
  "Medium Thermal Armor Reinforcer II": "rig",
  "Medium Thermal Shield Reinforcer I": "rig",
  "Medium Thermal Shield Reinforcer II": "rig",
  "Medium Trimark Armor Pump I": "rig",
  "Medium Trimark Armor Pump II": "rig",
  "Medium Warp Core Optimizer I": "rig",
  "Medium Warp Core Optimizer II": "rig",
  "Mega Afocal Laser I": "high",
  "Mega Afocal Pulse Laser I": "high",
  "Mega Anode Particle Stream I": "high",
  "Mega Anode Pulse Particle Stream I": "high",
  "Mega Beam Laser I": "high",
  "Mega Beam Laser II": "high",
  "Mega Modal Laser I": "high",
  "Mega Modal Pulse Laser I": "high",
  "Mega Modulated Energy Beam I": "high",
  "Mega Modulated Pulse Energy Beam I": "high",
  "Mega Pulse Laser I": "high",
  "Mega Pulse Laser II": "high",
  "Mizuro's Modified 100MN Afterburner": "mid",
  "Mizuro's Modified 500MN Microwarpdrive": "mid",
  "Mizuro's Modified 800mm Repeating Cannon": "high",
  "Mizuro's Modified Dual 425mm AutoCannon": "high",
  "Mizuro's Modified Dual 650mm Repeating Cannon": "high",
  "Mizuro's Modified Heavy Warp Scrambler": "mid",
  "Mizuro's Modified Stasis Webifier": "mid",
  "Mizuro's Modified Tracking Enhancer": "low",
  "Modal Electron Particle Accelerator I": "high",
  "Modal Enduring Dual Giga Beam Laser": "high",
  "Modal Enduring Dual Giga Pulse Laser": "high",
  "Modal Enduring Ion Siege Blaster": "high",
  "Modal Enduring Quad Mega Pulse Laser": "high",
  "Modal Enduring Triple Neutron Blaster Cannon": "high",
  "Modal Ion Particle Accelerator I": "high",
  "Modal Light Electron Particle Accelerator I": "high",
  "Modal Light Ion Particle Accelerator I": "high",
  "Modal Light Neutron Particle Accelerator I": "high",
  "Modal Mega Electron Particle Accelerator I": "high",
  "Modal Mega Ion Particle Accelerator I": "high",
  "Modal Mega Neutron Particle Accelerator I": "high",
  "Modal Neutron Particle Accelerator I": "high",
  "Modulated Compact Dual Giga Beam Laser": "high",
  "Modulated Compact Dual Giga Pulse Laser": "high",
  "Modulated Compact Quad Mega Pulse Laser": "high",
  "Nanofiber Internal Structure I": "low",
  "Nanofiber Internal Structure II": "low",
  "Neutron Blaster Cannon I": "high",
  "Neutron Blaster Cannon II": "high",
  "Nija's Modified 10MN Afterburner": "mid",
  "Nija's Modified Heavy Pulse Laser": "high",
  "ORE Reinforced Bulkheads": "low",
  "Optical Compact Tracking Computer": "mid",
  "Overdrive Injector System I": "low",
  "Overdrive Injector System II": "low",
  "Polarized 200mm AutoCannon": "high",
  "Polarized 425mm AutoCannon": "high",
  "Polarized 800mm Repeating Cannon": "high",
  "Polarized Heavy Neutron Blaster": "high",
  "Polarized Heavy Pulse Laser": "high",
  "Polarized Light Neutron Blaster": "high",
  "Polarized Mega Pulse Laser": "high",
  "Polarized Neutron Blaster Cannon": "high",
  "Polarized Small Focused Pulse Laser": "high",
  "Prototype Precise Dual 1000mm Railgun": "high",
  "Prototype Precise Hexa 2500mm Repeating Cannon": "high",
  "Prototype Precise Quad 3500mm Siege Artillery": "high",
  "Prototype Precise Quad 800mm Repeating Cannon": "high",
  "Quad 3500mm Siege Artillery I": "high",
  "Quad 3500mm Siege Artillery II": "high",
  "Quad 800mm Repeating Cannon I": "high",
  "Quad 800mm Repeating Cannon II": "high",
  "Quad Afocal Light Laser I": "high",
  "Quad Anode Light Particle Stream I": "high",
  "Quad Light Beam Laser I": "high",
  "Quad Light Beam Laser II": "high",
  "Quad Mega Pulse Laser I": "high",
  "Quad Mega Pulse Laser II": "high",
  "Quad Modal Light Laser I": "high",
  "Quad Modulated Light Energy Beam I": "high",
  "Ramaku's Modified 1MN Afterburner": "mid",
  "Ramaku's Modified 200mm AutoCannon": "high",
  "Ramaku's Modified 5MN Microwarpdrive": "mid",
  "Raysere's Modified Dual Heavy Beam Laser": "high",
  "Raysere's Modified Mega Beam Laser": "high",
  "Raysere's Modified Tachyon Beam Laser": "high",
  "Regulated Compact Ion Siege Blaster": "high",
  "Regulated Compact Triple Neutron Blaster Cannon": "high",
  "Regulated Electron Phase Cannon I": "high",
  "Regulated Ion Phase Cannon I": "high",
  "Regulated Light Electron Phase Cannon I": "high",
  "Regulated Light Ion Phase Cannon I": "high",
  "Regulated Light Neutron Phase Cannon I": "high",
  "Regulated Mega Electron Phase Cannon I": "high",
  "Regulated Mega Ion Phase Cannon I": "high",
  "Regulated Mega Neutron Phase Cannon I": "high",
  "Regulated Neutron Phase Cannon I": "high",
  "Reinforced Bulkheads I": "low",
  "Reinforced Bulkheads II": "low",
  "Republic Fleet 100MN Afterburner": "mid",
  "Republic Fleet 10MN Afterburner": "mid",
  "Republic Fleet 1200mm Artillery": "high",
  "Republic Fleet 125mm Autocannon": "high",
  "Republic Fleet 1400mm Howitzer Artillery": "high",
  "Republic Fleet 150mm Autocannon": "high",
  "Republic Fleet 1MN Afterburner": "mid",
  "Republic Fleet 200mm Autocannon": "high",
  "Republic Fleet 220mm Autocannon": "high",
  "Republic Fleet 250mm Artillery": "high",
  "Republic Fleet 280mm Howitzer Artillery": "high",
  "Republic Fleet 425mm Autocannon": "high",
  "Republic Fleet 500MN Microwarpdrive": "mid",
  "Republic Fleet 50MN Microwarpdrive": "mid",
  "Republic Fleet 5MN Microwarpdrive": "mid",
  "Republic Fleet 650mm Artillery": "high",
  "Republic Fleet 720mm Howitzer Artillery": "high",
  "Republic Fleet 800mm Repeating Cannon": "high",
  "Republic Fleet Dual 180mm Autocannon": "high",
  "Republic Fleet Dual 425mm Autocannon": "high",
  "Republic Fleet Dual 650mm Repeating Cannon": "high",
  "Republic Fleet Large Shield Extender": "mid",
  "Republic Fleet Medium Shield Extender": "mid",
  "Republic Fleet Nanofiber Structure": "low",
  "Republic Fleet Overdrive Injector": "low",
  "Republic Fleet Small Shield Extender": "mid",
  "Republic Fleet Stasis Webifier": "mid",
  "Republic Fleet Tracking Enhancer": "low",
  "Republic Fleet Warp Scrambler": "mid",
  "Roden’s Modified Nanofiber Internal Structure": "low",
  "Ryhad's Modified Heavy Pulse Laser": "high",
  "Scout Scoped Dual 1000mm Railgun": "high",
  "Scout Scoped Hexa 2500mm Repeating Cannon": "high",
  "Scout Scoped Quad 3500mm Siege Artillery": "high",
  "Scout Scoped Quad 800mm Repeating Cannon": "high",
  "Selynne's Modified Dual Heavy Beam Laser": "high",
  "Selynne's Modified Mega Beam Laser": "high",
  "Selynne's Modified Tachyon Beam Laser": "high",
  "Setele's Modified 100MN Afterburner": "mid",
  "Setele's Modified 350mm Railgun": "high",
  "Setele's Modified 425mm Railgun": "high",
  "Setele's Modified 500MN Microwarpdrive": "mid",
  "Setele's Modified Dual 250mm Railgun": "high",
  "Setele's Modified Tracking Computer": "mid",
  "Shadow Serpentis 10000MN Afterburner": "mid",
  "Shadow Serpentis 100MN Afterburner": "mid",
  "Shadow Serpentis 10MN Afterburner": "mid",
  "Shadow Serpentis 125mm Railgun": "high",
  "Shadow Serpentis 150mm Railgun": "high",
  "Shadow Serpentis 1MN Afterburner": "mid",
  "Shadow Serpentis 200mm Railgun": "high",
  "Shadow Serpentis 25000mm Steel Plates": "low",
  "Shadow Serpentis 250mm Railgun": "high",
  "Shadow Serpentis 350mm Railgun": "high",
  "Shadow Serpentis 425mm Railgun": "high",
  "Shadow Serpentis 50000MN Microwarpdrive": "mid",
  "Shadow Serpentis 500MN Microwarpdrive": "mid",
  "Shadow Serpentis 50MN Microwarpdrive": "mid",
  "Shadow Serpentis 5MN Microwarpdrive": "mid",
  "Shadow Serpentis 75mm Railgun": "high",
  "Shadow Serpentis Dual 1000mm Railgun": "high",
  "Shadow Serpentis Dual 150mm Railgun": "high",
  "Shadow Serpentis Dual 250mm Railgun": "high",
  "Shadow Serpentis Electron Blaster Cannon": "high",
  "Shadow Serpentis Heavy Electron Blaster": "high",
  "Shadow Serpentis Heavy Ion Blaster": "high",
  "Shadow Serpentis Heavy Neutron Blaster": "high",
  "Shadow Serpentis Heavy Stasis Grappler": "mid",
  "Shadow Serpentis Heavy Warp Scrambler": "mid",
  "Shadow Serpentis Inertial Stabilizers": "low",
  "Shadow Serpentis Ion Blaster Cannon": "high",
  "Shadow Serpentis Ion Siege Blaster": "high",
  "Shadow Serpentis Light Electron Blaster": "high",
  "Shadow Serpentis Light Ion Blaster": "high",
  "Shadow Serpentis Light Neutron Blaster": "high",
  "Shadow Serpentis Neutron Blaster Cannon": "high",
  "Shadow Serpentis Stasis Webifier": "mid",
  "Shadow Serpentis Tracking Computer": "mid",
  "Shadow Serpentis Triple Neutron Blaster Cannon": "high",
  "Shadow Serpentis Warp Scrambler": "mid",
  "Sila's Modified 10MN Afterburner": "mid",
  "Sila's Modified 425mm Autocannon": "high",
  "Sila's Modified 50MN Microwarpdrive": "mid",
  "Small 'Wolf' Shield Extender": "mid",
  "Small Auxiliary Thrusters I": "rig",
  "Small Auxiliary Thrusters II": "rig",
  "Small Core Defense Capacitor Safeguard I": "rig",
  "Small Core Defense Capacitor Safeguard II": "rig",
  "Small Core Defense Charge Economizer I": "rig",
  "Small Core Defense Charge Economizer II": "rig",
  "Small Core Defense Field Extender I": "rig",
  "Small Core Defense Field Extender II": "rig",
  "Small Core Defense Field Purger I": "rig",
  "Small Core Defense Field Purger II": "rig",
  "Small Core Defense Operational Solidifier I": "rig",
  "Small Core Defense Operational Solidifier II": "rig",
  "Small EM Armor Reinforcer I": "rig",
  "Small EM Armor Reinforcer II": "rig",
  "Small EM Shield Reinforcer I": "rig",
  "Small EM Shield Reinforcer II": "rig",
  "Small Energy Ambit Extension I": "rig",
  "Small Energy Ambit Extension II": "rig",
  "Small Energy Locus Coordinator I": "rig",
  "Small Energy Locus Coordinator II": "rig",
  "Small Energy Metastasis Adjuster I": "rig",
  "Small Energy Metastasis Adjuster II": "rig",
  "Small Explosive Armor Reinforcer I": "rig",
  "Small Explosive Armor Reinforcer II": "rig",
  "Small Explosive Shield Reinforcer I": "rig",
  "Small Explosive Shield Reinforcer II": "rig",
  "Small F-S9 Regolith Compact Shield Extender": "mid",
  "Small Focused Afocal Laser I": "high",
  "Small Focused Afocal Pulse Laser I": "high",
  "Small Focused Anode Particle Stream I": "high",
  "Small Focused Anode Pulse Particle Stream I": "high",
  "Small Focused Beam Laser I": "high",
  "Small Focused Beam Laser II": "high",
  "Small Focused Modal Laser I": "high",
  "Small Focused Modal Pulse Laser I": "high",
  "Small Focused Modulated Energy Beam I": "high",
  "Small Focused Modulated Pulse Energy Beam I": "high",
  "Small Focused Pulse Laser I": "high",
  "Small Focused Pulse Laser II": "high",
  "Small Higgs Anchor I": "rig",
  "Small Hybrid Ambit Extension I": "rig",
  "Small Hybrid Ambit Extension II": "rig",
  "Small Hybrid Locus Coordinator I": "rig",
  "Small Hybrid Locus Coordinator II": "rig",
  "Small Hybrid Metastasis Adjuster I": "rig",
  "Small Hybrid Metastasis Adjuster II": "rig",
  "Small Hyperspatial Velocity Optimizer I": "rig",
  "Small Hyperspatial Velocity Optimizer II": "rig",
  "Small Kinetic Armor Reinforcer I": "rig",
  "Small Kinetic Armor Reinforcer II": "rig",
  "Small Kinetic Shield Reinforcer I": "rig",
  "Small Kinetic Shield Reinforcer II": "rig",
  "Small Low Friction Nozzle Joints I": "rig",
  "Small Low Friction Nozzle Joints II": "rig",
  "Small Polycarbon Engine Housing I": "rig",
  "Small Polycarbon Engine Housing II": "rig",
  "Small Projectile Ambit Extension I": "rig",
  "Small Projectile Ambit Extension II": "rig",
  "Small Projectile Locus Coordinator I": "rig",
  "Small Projectile Locus Coordinator II": "rig",
  "Small Projectile Metastasis Adjuster I": "rig",
  "Small Projectile Metastasis Adjuster II": "rig",
  "Small Remote Repair Augmentor I": "rig",
  "Small Remote Repair Augmentor II": "rig",
  "Small Shield Extender I": "mid",
  "Small Shield Extender II": "mid",
  "Small Thermal Armor Reinforcer I": "rig",
  "Small Thermal Armor Reinforcer II": "rig",
  "Small Thermal Shield Reinforcer I": "rig",
  "Small Thermal Shield Reinforcer II": "rig",
  "Small Trimark Armor Pump I": "rig",
  "Small Trimark Armor Pump II": "rig",
  "Small Warp Core Optimizer I": "rig",
  "Small Warp Core Optimizer II": "rig",
  "Stasis Webifier I": "mid",
  "Stasis Webifier II": "mid",
  "Strategos' Modified Heavy Stasis Grappler": "mid",
  "Syndicate 100mm Steel Plates": "low",
  "Syndicate 1600mm Steel Plates": "low",
  "Syndicate 200mm Steel Plates": "low",
  "Syndicate 400mm Steel Plates": "low",
  "Syndicate 800mm Steel Plates": "low",
  "Syndicate Reinforced Bulkheads": "low",
  "Synthetic Hull Conversion Inertial Stabilizers": "low",
  "Synthetic Hull Conversion Nanofiber Structure": "low",
  "Synthetic Hull Conversion Overdrive Injector": "low",
  "Synthetic Hull Conversion Reinforced Bulkheads": "low",
  "Tachyon Afocal Laser I": "high",
  "Tachyon Anode Particle Stream I": "high",
  "Tachyon Beam Laser I": "high",
  "Tachyon Beam Laser II": "high",
  "Tachyon Modal Laser I": "high",
  "Tachyon Modulated Energy Beam I": "high",
  "Tairei's Modified Dual Heavy Pulse Laser": "high",
  "Tairei's Modified Mega Pulse Laser": "high",
  "Thukker Large Shield Extender": "mid",
  "Thukker Medium Shield Extender": "mid",
  "Tobias' Modified 100MN Afterburner": "mid",
  "Tobias' Modified 1200mm Artillery Cannon": "high",
  "Tobias' Modified 1400mm Howitzer Artillery": "high",
  "Tobias' Modified 500MN Microwarpdrive": "mid",
  "Tobias' Modified Heavy Warp Scrambler": "mid",
  "Tobias' Modified Stasis Webifier": "mid",
  "Tobias' Modified Tracking Enhancer": "low",
  "Tracking Computer I": "mid",
  "Tracking Computer II": "mid",
  "Tracking Disruptor I": "mid",
  "Tracking Disruptor II": "mid",
  "Tracking Enhancer I": "low",
  "Tracking Enhancer II": "low",
  "Triple Neutron Blaster Cannon I": "high",
  "Triple Neutron Blaster Cannon II": "high",
  "True Sansha 10MN Afterburner": "mid",
  "True Sansha 1MN Afterburner": "mid",
  "True Sansha Capital Shield Extender": "mid",
  "True Sansha Dual Giga Beam Laser": "high",
  "True Sansha Dual Giga Pulse Laser": "high",
  "True Sansha Dual Heavy Beam Laser": "high",
  "True Sansha Dual Heavy Pulse Laser": "high",
  "True Sansha Dual Light Beam Laser": "high",
  "True Sansha Dual Light Pulse Laser": "high",
  "True Sansha Focused Medium Beam Laser": "high",
  "True Sansha Focused Medium Pulse Laser": "high",
  "True Sansha Gatling Pulse Laser": "high",
  "True Sansha Heavy Beam Laser": "high",
  "True Sansha Heavy Pulse Laser": "high",
  "True Sansha Mega Beam Laser": "high",
  "True Sansha Mega Pulse Laser": "high",
  "True Sansha Quad Beam Laser": "high",
  "True Sansha Quad Mega Pulse Laser": "high",
  "True Sansha Small Focused Beam Laser": "high",
  "True Sansha Small Focused Pulse Laser": "high",
  "True Sansha Stasis Webifier": "mid",
  "True Sansha Tachyon Beam Laser": "high",
  "True Sansha Warp Scrambler": "mid",
  "Tuvan's Modified 100MN Afterburner": "mid",
  "Tuvan's Modified 500MN Microwarpdrive": "mid",
  "Tuvan's Modified Electron Blaster Cannon": "high",
  "Tuvan's Modified Ion Blaster Cannon": "high",
  "Tuvan's Modified Neutron Blaster Cannon": "high",
  "Tuvan's Modified Tracking Computer": "mid",
  "Type-D Restrained Inertial Stabilizers": "low",
  "Type-D Restrained Nanofiber Structure": "low",
  "Type-D Restrained Overdrive Injector": "low",
  "Type-D Restrained Reinforced Bulkheads": "low",
  "Usaras' Modified 1MN Afterburner": "mid",
  "Usaras' Modified Small Focused Pulse Laser": "high",
  "Vepas' Modified 350mm Railgun": "high",
  "Vepas' Modified 425mm Railgun": "high",
  "Vepas' Modified Dual 250mm Railgun": "high",
  "Vizan's Modified Dual Heavy Pulse Laser": "high",
  "Vizan's Modified Mega Pulse Laser": "high",
  "Warp Scrambler I": "mid",
  "Warp Scrambler II": "mid",
  "X5 Enduring Stasis Webifier": "mid",
} as const;

export const MODULE_SLOTS_BY_ID: Readonly<Record<TypeId, ModuleSlot>> = {
  ["377" as TypeId]: "mid",
  ["380" as TypeId]: "mid",
  ["434" as TypeId]: "mid",
  ["438" as TypeId]: "mid",
  ["439" as TypeId]: "mid",
  ["440" as TypeId]: "mid",
  ["447" as TypeId]: "mid",
  ["448" as TypeId]: "mid",
  ["450" as TypeId]: "high",
  ["451" as TypeId]: "high",
  ["452" as TypeId]: "high",
  ["453" as TypeId]: "high",
  ["454" as TypeId]: "high",
  ["455" as TypeId]: "high",
  ["456" as TypeId]: "high",
  ["457" as TypeId]: "high",
  ["458" as TypeId]: "high",
  ["459" as TypeId]: "high",
  ["460" as TypeId]: "high",
  ["461" as TypeId]: "high",
  ["462" as TypeId]: "high",
  ["463" as TypeId]: "high",
  ["464" as TypeId]: "high",
  ["484" as TypeId]: "high",
  ["485" as TypeId]: "high",
  ["486" as TypeId]: "high",
  ["487" as TypeId]: "high",
  ["488" as TypeId]: "high",
  ["489" as TypeId]: "high",
  ["490" as TypeId]: "high",
  ["491" as TypeId]: "high",
  ["492" as TypeId]: "high",
  ["493" as TypeId]: "high",
  ["494" as TypeId]: "high",
  ["495" as TypeId]: "high",
  ["496" as TypeId]: "high",
  ["497" as TypeId]: "high",
  ["498" as TypeId]: "high",
  ["526" as TypeId]: "mid",
  ["527" as TypeId]: "mid",
  ["561" as TypeId]: "high",
  ["562" as TypeId]: "high",
  ["563" as TypeId]: "high",
  ["564" as TypeId]: "high",
  ["565" as TypeId]: "high",
  ["566" as TypeId]: "high",
  ["567" as TypeId]: "high",
  ["568" as TypeId]: "high",
  ["569" as TypeId]: "high",
  ["570" as TypeId]: "high",
  ["571" as TypeId]: "high",
  ["572" as TypeId]: "high",
  ["573" as TypeId]: "high",
  ["574" as TypeId]: "high",
  ["575" as TypeId]: "high",
  ["1192" as TypeId]: "low",
  ["1236" as TypeId]: "low",
  ["1240" as TypeId]: "low",
  ["1242" as TypeId]: "low",
  ["1244" as TypeId]: "low",
  ["1333" as TypeId]: "low",
  ["1335" as TypeId]: "low",
  ["1401" as TypeId]: "low",
  ["1403" as TypeId]: "low",
  ["1405" as TypeId]: "low",
  ["1951" as TypeId]: "low",
  ["1977" as TypeId]: "mid",
  ["1978" as TypeId]: "mid",
  ["1998" as TypeId]: "low",
  ["1999" as TypeId]: "low",
  ["2108" as TypeId]: "mid",
  ["2109" as TypeId]: "mid",
  ["2603" as TypeId]: "low",
  ["2605" as TypeId]: "low",
  ["2865" as TypeId]: "high",
  ["2873" as TypeId]: "high",
  ["2881" as TypeId]: "high",
  ["2889" as TypeId]: "high",
  ["2897" as TypeId]: "high",
  ["2905" as TypeId]: "high",
  ["2913" as TypeId]: "high",
  ["2921" as TypeId]: "high",
  ["2929" as TypeId]: "high",
  ["2937" as TypeId]: "high",
  ["2945" as TypeId]: "high",
  ["2953" as TypeId]: "high",
  ["2961" as TypeId]: "high",
  ["2969" as TypeId]: "high",
  ["2977" as TypeId]: "high",
  ["2985" as TypeId]: "high",
  ["2993" as TypeId]: "high",
  ["3001" as TypeId]: "high",
  ["3009" as TypeId]: "high",
  ["3017" as TypeId]: "high",
  ["3025" as TypeId]: "high",
  ["3033" as TypeId]: "high",
  ["3041" as TypeId]: "high",
  ["3049" as TypeId]: "high",
  ["3057" as TypeId]: "high",
  ["3065" as TypeId]: "high",
  ["3074" as TypeId]: "high",
  ["3082" as TypeId]: "high",
  ["3090" as TypeId]: "high",
  ["3098" as TypeId]: "high",
  ["3106" as TypeId]: "high",
  ["3114" as TypeId]: "high",
  ["3122" as TypeId]: "high",
  ["3130" as TypeId]: "high",
  ["3138" as TypeId]: "high",
  ["3146" as TypeId]: "high",
  ["3154" as TypeId]: "high",
  ["3162" as TypeId]: "high",
  ["3170" as TypeId]: "high",
  ["3178" as TypeId]: "high",
  ["3186" as TypeId]: "high",
  ["3285" as TypeId]: "high",
  ["3512" as TypeId]: "high",
  ["3520" as TypeId]: "high",
  ["3546" as TypeId]: "high",
  ["3550" as TypeId]: "high",
  ["3559" as TypeId]: "high",
  ["3561" as TypeId]: "high",
  ["3571" as TypeId]: "high",
  ["3573" as TypeId]: "high",
  ["3829" as TypeId]: "mid",
  ["3831" as TypeId]: "mid",
  ["3839" as TypeId]: "mid",
  ["3841" as TypeId]: "mid",
  ["4025" as TypeId]: "mid",
  ["4027" as TypeId]: "mid",
  ["4147" as TypeId]: "high",
  ["5175" as TypeId]: "high",
  ["5177" as TypeId]: "high",
  ["5179" as TypeId]: "high",
  ["5181" as TypeId]: "high",
  ["5215" as TypeId]: "high",
  ["5217" as TypeId]: "high",
  ["5219" as TypeId]: "high",
  ["5221" as TypeId]: "high",
  ["5319" as TypeId]: "mid",
  ["5320" as TypeId]: "mid",
  ["5322" as TypeId]: "mid",
  ["5439" as TypeId]: "mid",
  ["5443" as TypeId]: "mid",
  ["5445" as TypeId]: "mid",
  ["5533" as TypeId]: "low",
  ["5599" as TypeId]: "low",
  ["5631" as TypeId]: "low",
  ["5647" as TypeId]: "low",
  ["5649" as TypeId]: "low",
  ["5945" as TypeId]: "mid",
  ["5955" as TypeId]: "mid",
  ["5971" as TypeId]: "mid",
  ["5973" as TypeId]: "mid",
  ["5975" as TypeId]: "mid",
  ["6001" as TypeId]: "mid",
  ["6003" as TypeId]: "mid",
  ["6005" as TypeId]: "mid",
  ["6173" as TypeId]: "mid",
  ["6176" as TypeId]: "mid",
  ["6325" as TypeId]: "low",
  ["6631" as TypeId]: "high",
  ["6633" as TypeId]: "high",
  ["6635" as TypeId]: "high",
  ["6637" as TypeId]: "high",
  ["6671" as TypeId]: "high",
  ["6673" as TypeId]: "high",
  ["6675" as TypeId]: "high",
  ["6677" as TypeId]: "high",
  ["6715" as TypeId]: "high",
  ["6717" as TypeId]: "high",
  ["6719" as TypeId]: "high",
  ["6721" as TypeId]: "high",
  ["6757" as TypeId]: "high",
  ["6759" as TypeId]: "high",
  ["6761" as TypeId]: "high",
  ["6763" as TypeId]: "high",
  ["6805" as TypeId]: "high",
  ["6807" as TypeId]: "high",
  ["6809" as TypeId]: "high",
  ["6811" as TypeId]: "high",
  ["6859" as TypeId]: "high",
  ["6861" as TypeId]: "high",
  ["6863" as TypeId]: "high",
  ["6865" as TypeId]: "high",
  ["6919" as TypeId]: "high",
  ["6921" as TypeId]: "high",
  ["6923" as TypeId]: "high",
  ["6925" as TypeId]: "high",
  ["6959" as TypeId]: "high",
  ["6961" as TypeId]: "high",
  ["6963" as TypeId]: "high",
  ["6965" as TypeId]: "high",
  ["6999" as TypeId]: "high",
  ["7001" as TypeId]: "high",
  ["7003" as TypeId]: "high",
  ["7005" as TypeId]: "high",
  ["7043" as TypeId]: "high",
  ["7045" as TypeId]: "high",
  ["7047" as TypeId]: "high",
  ["7049" as TypeId]: "high",
  ["7083" as TypeId]: "high",
  ["7085" as TypeId]: "high",
  ["7087" as TypeId]: "high",
  ["7089" as TypeId]: "high",
  ["7123" as TypeId]: "high",
  ["7125" as TypeId]: "high",
  ["7127" as TypeId]: "high",
  ["7131" as TypeId]: "high",
  ["7167" as TypeId]: "high",
  ["7169" as TypeId]: "high",
  ["7171" as TypeId]: "high",
  ["7173" as TypeId]: "high",
  ["7247" as TypeId]: "high",
  ["7249" as TypeId]: "high",
  ["7251" as TypeId]: "high",
  ["7253" as TypeId]: "high",
  ["7287" as TypeId]: "high",
  ["7289" as TypeId]: "high",
  ["7291" as TypeId]: "high",
  ["7293" as TypeId]: "high",
  ["7327" as TypeId]: "high",
  ["7329" as TypeId]: "high",
  ["7331" as TypeId]: "high",
  ["7333" as TypeId]: "high",
  ["7367" as TypeId]: "high",
  ["7369" as TypeId]: "high",
  ["7371" as TypeId]: "high",
  ["7373" as TypeId]: "high",
  ["7407" as TypeId]: "high",
  ["7409" as TypeId]: "high",
  ["7411" as TypeId]: "high",
  ["7413" as TypeId]: "high",
  ["7447" as TypeId]: "high",
  ["7449" as TypeId]: "high",
  ["7451" as TypeId]: "high",
  ["7453" as TypeId]: "high",
  ["7487" as TypeId]: "high",
  ["7489" as TypeId]: "high",
  ["7491" as TypeId]: "high",
  ["7493" as TypeId]: "high",
  ["7535" as TypeId]: "high",
  ["7537" as TypeId]: "high",
  ["7539" as TypeId]: "high",
  ["7541" as TypeId]: "high",
  ["7579" as TypeId]: "high",
  ["7581" as TypeId]: "high",
  ["7583" as TypeId]: "high",
  ["7585" as TypeId]: "high",
  ["7619" as TypeId]: "high",
  ["7621" as TypeId]: "high",
  ["7623" as TypeId]: "high",
  ["7625" as TypeId]: "high",
  ["7663" as TypeId]: "high",
  ["7665" as TypeId]: "high",
  ["7667" as TypeId]: "high",
  ["7669" as TypeId]: "high",
  ["7703" as TypeId]: "high",
  ["7705" as TypeId]: "high",
  ["7707" as TypeId]: "high",
  ["7709" as TypeId]: "high",
  ["7743" as TypeId]: "high",
  ["7745" as TypeId]: "high",
  ["7747" as TypeId]: "high",
  ["7749" as TypeId]: "high",
  ["7783" as TypeId]: "high",
  ["7785" as TypeId]: "high",
  ["7787" as TypeId]: "high",
  ["7789" as TypeId]: "high",
  ["7827" as TypeId]: "high",
  ["7829" as TypeId]: "high",
  ["7831" as TypeId]: "high",
  ["7833" as TypeId]: "high",
  ["8419" as TypeId]: "mid",
  ["8433" as TypeId]: "mid",
  ["8517" as TypeId]: "mid",
  ["8521" as TypeId]: "mid",
  ["8529" as TypeId]: "mid",
  ["8759" as TypeId]: "high",
  ["8785" as TypeId]: "high",
  ["8787" as TypeId]: "high",
  ["8789" as TypeId]: "high",
  ["8815" as TypeId]: "high",
  ["8817" as TypeId]: "high",
  ["8819" as TypeId]: "high",
  ["8821" as TypeId]: "high",
  ["8863" as TypeId]: "high",
  ["8865" as TypeId]: "high",
  ["8867" as TypeId]: "high",
  ["8869" as TypeId]: "high",
  ["8903" as TypeId]: "high",
  ["8905" as TypeId]: "high",
  ["8907" as TypeId]: "high",
  ["8909" as TypeId]: "high",
  ["9071" as TypeId]: "high",
  ["9073" as TypeId]: "high",
  ["9091" as TypeId]: "high",
  ["9093" as TypeId]: "high",
  ["9127" as TypeId]: "high",
  ["9129" as TypeId]: "high",
  ["9131" as TypeId]: "high",
  ["9133" as TypeId]: "high",
  ["9135" as TypeId]: "high",
  ["9137" as TypeId]: "high",
  ["9139" as TypeId]: "high",
  ["9141" as TypeId]: "high",
  ["9207" as TypeId]: "high",
  ["9209" as TypeId]: "high",
  ["9211" as TypeId]: "high",
  ["9213" as TypeId]: "high",
  ["9247" as TypeId]: "high",
  ["9249" as TypeId]: "high",
  ["9251" as TypeId]: "high",
  ["9253" as TypeId]: "high",
  ["9287" as TypeId]: "high",
  ["9289" as TypeId]: "high",
  ["9291" as TypeId]: "high",
  ["9293" as TypeId]: "high",
  ["9327" as TypeId]: "high",
  ["9329" as TypeId]: "high",
  ["9331" as TypeId]: "high",
  ["9333" as TypeId]: "high",
  ["9367" as TypeId]: "high",
  ["9369" as TypeId]: "high",
  ["9371" as TypeId]: "high",
  ["9377" as TypeId]: "high",
  ["9411" as TypeId]: "high",
  ["9413" as TypeId]: "high",
  ["9415" as TypeId]: "high",
  ["9417" as TypeId]: "high",
  ["9451" as TypeId]: "high",
  ["9453" as TypeId]: "high",
  ["9455" as TypeId]: "high",
  ["9457" as TypeId]: "high",
  ["9491" as TypeId]: "high",
  ["9493" as TypeId]: "high",
  ["9495" as TypeId]: "high",
  ["9497" as TypeId]: "high",
  ["10678" as TypeId]: "high",
  ["10680" as TypeId]: "high",
  ["10688" as TypeId]: "high",
  ["10690" as TypeId]: "high",
  ["10692" as TypeId]: "high",
  ["10694" as TypeId]: "high",
  ["11279" as TypeId]: "low",
  ["11293" as TypeId]: "low",
  ["11295" as TypeId]: "low",
  ["11297" as TypeId]: "low",
  ["11299" as TypeId]: "low",
  ["11309" as TypeId]: "low",
  ["11311" as TypeId]: "low",
  ["11317" as TypeId]: "low",
  ["11319" as TypeId]: "low",
  ["11325" as TypeId]: "low",
  ["11327" as TypeId]: "low",
  ["11341" as TypeId]: "low",
  ["11343" as TypeId]: "low",
  ["11349" as TypeId]: "low",
  ["11351" as TypeId]: "low",
  ["12052" as TypeId]: "mid",
  ["12054" as TypeId]: "mid",
  ["12056" as TypeId]: "mid",
  ["12058" as TypeId]: "mid",
  ["12066" as TypeId]: "mid",
  ["12068" as TypeId]: "mid",
  ["12076" as TypeId]: "mid",
  ["12084" as TypeId]: "mid",
  ["12344" as TypeId]: "high",
  ["12346" as TypeId]: "high",
  ["12354" as TypeId]: "high",
  ["12356" as TypeId]: "high",
  ["13773" as TypeId]: "high",
  ["13774" as TypeId]: "high",
  ["13775" as TypeId]: "high",
  ["13776" as TypeId]: "high",
  ["13777" as TypeId]: "high",
  ["13778" as TypeId]: "high",
  ["13779" as TypeId]: "high",
  ["13781" as TypeId]: "high",
  ["13782" as TypeId]: "high",
  ["13783" as TypeId]: "high",
  ["13784" as TypeId]: "high",
  ["13785" as TypeId]: "high",
  ["13786" as TypeId]: "high",
  ["13787" as TypeId]: "high",
  ["13788" as TypeId]: "high",
  ["13791" as TypeId]: "high",
  ["13793" as TypeId]: "high",
  ["13795" as TypeId]: "high",
  ["13797" as TypeId]: "high",
  ["13799" as TypeId]: "high",
  ["13801" as TypeId]: "high",
  ["13803" as TypeId]: "high",
  ["13805" as TypeId]: "high",
  ["13807" as TypeId]: "high",
  ["13809" as TypeId]: "high",
  ["13811" as TypeId]: "high",
  ["13813" as TypeId]: "high",
  ["13815" as TypeId]: "high",
  ["13817" as TypeId]: "high",
  ["13819" as TypeId]: "high",
  ["13820" as TypeId]: "high",
  ["13821" as TypeId]: "high",
  ["13822" as TypeId]: "high",
  ["13823" as TypeId]: "high",
  ["13824" as TypeId]: "high",
  ["13825" as TypeId]: "high",
  ["13826" as TypeId]: "high",
  ["13827" as TypeId]: "high",
  ["13828" as TypeId]: "high",
  ["13829" as TypeId]: "high",
  ["13830" as TypeId]: "high",
  ["13831" as TypeId]: "high",
  ["13832" as TypeId]: "high",
  ["13833" as TypeId]: "high",
  ["13834" as TypeId]: "high",
  ["13864" as TypeId]: "high",
  ["13865" as TypeId]: "high",
  ["13866" as TypeId]: "high",
  ["13867" as TypeId]: "high",
  ["13868" as TypeId]: "high",
  ["13870" as TypeId]: "high",
  ["13872" as TypeId]: "high",
  ["13873" as TypeId]: "high",
  ["13874" as TypeId]: "high",
  ["13876" as TypeId]: "high",
  ["13878" as TypeId]: "high",
  ["13879" as TypeId]: "high",
  ["13880" as TypeId]: "high",
  ["13881" as TypeId]: "high",
  ["13882" as TypeId]: "high",
  ["13883" as TypeId]: "high",
  ["13884" as TypeId]: "high",
  ["13885" as TypeId]: "high",
  ["13886" as TypeId]: "high",
  ["13887" as TypeId]: "high",
  ["13888" as TypeId]: "high",
  ["13889" as TypeId]: "high",
  ["13890" as TypeId]: "high",
  ["13891" as TypeId]: "high",
  ["13892" as TypeId]: "high",
  ["13893" as TypeId]: "high",
  ["13894" as TypeId]: "high",
  ["14100" as TypeId]: "low",
  ["14102" as TypeId]: "mid",
  ["14104" as TypeId]: "mid",
  ["14106" as TypeId]: "mid",
  ["14108" as TypeId]: "mid",
  ["14110" as TypeId]: "mid",
  ["14112" as TypeId]: "mid",
  ["14114" as TypeId]: "mid",
  ["14116" as TypeId]: "mid",
  ["14118" as TypeId]: "mid",
  ["14120" as TypeId]: "mid",
  ["14122" as TypeId]: "mid",
  ["14124" as TypeId]: "mid",
  ["14126" as TypeId]: "low",
  ["14127" as TypeId]: "low",
  ["14238" as TypeId]: "mid",
  ["14252" as TypeId]: "mid",
  ["14254" as TypeId]: "mid",
  ["14256" as TypeId]: "mid",
  ["14258" as TypeId]: "mid",
  ["14260" as TypeId]: "mid",
  ["14262" as TypeId]: "mid",
  ["14264" as TypeId]: "mid",
  ["14266" as TypeId]: "mid",
  ["14268" as TypeId]: "mid",
  ["14270" as TypeId]: "mid",
  ["14272" as TypeId]: "high",
  ["14274" as TypeId]: "high",
  ["14276" as TypeId]: "high",
  ["14278" as TypeId]: "high",
  ["14280" as TypeId]: "high",
  ["14282" as TypeId]: "high",
  ["14284" as TypeId]: "high",
  ["14286" as TypeId]: "high",
  ["14375" as TypeId]: "high",
  ["14377" as TypeId]: "high",
  ["14379" as TypeId]: "high",
  ["14381" as TypeId]: "high",
  ["14383" as TypeId]: "high",
  ["14385" as TypeId]: "high",
  ["14387" as TypeId]: "high",
  ["14389" as TypeId]: "high",
  ["14391" as TypeId]: "high",
  ["14393" as TypeId]: "high",
  ["14395" as TypeId]: "high",
  ["14397" as TypeId]: "high",
  ["14399" as TypeId]: "high",
  ["14401" as TypeId]: "high",
  ["14403" as TypeId]: "high",
  ["14405" as TypeId]: "high",
  ["14407" as TypeId]: "high",
  ["14409" as TypeId]: "high",
  ["14411" as TypeId]: "high",
  ["14413" as TypeId]: "high",
  ["14415" as TypeId]: "high",
  ["14417" as TypeId]: "high",
  ["14419" as TypeId]: "high",
  ["14421" as TypeId]: "high",
  ["14423" as TypeId]: "high",
  ["14425" as TypeId]: "high",
  ["14427" as TypeId]: "high",
  ["14429" as TypeId]: "high",
  ["14431" as TypeId]: "high",
  ["14433" as TypeId]: "high",
  ["14435" as TypeId]: "high",
  ["14437" as TypeId]: "high",
  ["14439" as TypeId]: "high",
  ["14441" as TypeId]: "high",
  ["14443" as TypeId]: "high",
  ["14445" as TypeId]: "high",
  ["14447" as TypeId]: "high",
  ["14449" as TypeId]: "high",
  ["14451" as TypeId]: "high",
  ["14453" as TypeId]: "high",
  ["14455" as TypeId]: "high",
  ["14457" as TypeId]: "high",
  ["14459" as TypeId]: "high",
  ["14461" as TypeId]: "high",
  ["14463" as TypeId]: "high",
  ["14465" as TypeId]: "high",
  ["14467" as TypeId]: "high",
  ["14469" as TypeId]: "high",
  ["14471" as TypeId]: "high",
  ["14473" as TypeId]: "high",
  ["14475" as TypeId]: "high",
  ["14484" as TypeId]: "mid",
  ["14486" as TypeId]: "mid",
  ["14488" as TypeId]: "mid",
  ["14490" as TypeId]: "mid",
  ["14492" as TypeId]: "mid",
  ["14494" as TypeId]: "mid",
  ["14496" as TypeId]: "mid",
  ["14498" as TypeId]: "mid",
  ["14500" as TypeId]: "mid",
  ["14502" as TypeId]: "mid",
  ["14504" as TypeId]: "mid",
  ["14506" as TypeId]: "mid",
  ["14508" as TypeId]: "mid",
  ["14510" as TypeId]: "mid",
  ["14512" as TypeId]: "mid",
  ["14514" as TypeId]: "mid",
  ["14640" as TypeId]: "low",
  ["14642" as TypeId]: "low",
  ["14644" as TypeId]: "low",
  ["14646" as TypeId]: "low",
  ["14648" as TypeId]: "mid",
  ["14650" as TypeId]: "mid",
  ["14652" as TypeId]: "mid",
  ["14654" as TypeId]: "mid",
  ["14664" as TypeId]: "mid",
  ["14666" as TypeId]: "mid",
  ["14668" as TypeId]: "mid",
  ["14670" as TypeId]: "mid",
  ["15284" as TypeId]: "mid",
  ["15286" as TypeId]: "mid",
  ["15288" as TypeId]: "mid",
  ["15290" as TypeId]: "mid",
  ["15747" as TypeId]: "mid",
  ["15749" as TypeId]: "mid",
  ["15751" as TypeId]: "mid",
  ["15753" as TypeId]: "mid",
  ["15755" as TypeId]: "mid",
  ["15757" as TypeId]: "mid",
  ["15759" as TypeId]: "mid",
  ["15761" as TypeId]: "mid",
  ["15764" as TypeId]: "mid",
  ["15766" as TypeId]: "mid",
  ["15768" as TypeId]: "mid",
  ["15770" as TypeId]: "mid",
  ["15792" as TypeId]: "mid",
  ["15812" as TypeId]: "low",
  ["15813" as TypeId]: "low",
  ["15814" as TypeId]: "high",
  ["15815" as TypeId]: "high",
  ["15816" as TypeId]: "high",
  ["15817" as TypeId]: "high",
  ["15818" as TypeId]: "high",
  ["15820" as TypeId]: "high",
  ["15821" as TypeId]: "high",
  ["15823" as TypeId]: "high",
  ["15824" as TypeId]: "high",
  ["15825" as TypeId]: "high",
  ["15826" as TypeId]: "high",
  ["15827" as TypeId]: "high",
  ["15828" as TypeId]: "high",
  ["15829" as TypeId]: "high",
  ["15830" as TypeId]: "high",
  ["15831" as TypeId]: "high",
  ["15832" as TypeId]: "high",
  ["15833" as TypeId]: "high",
  ["15834" as TypeId]: "high",
  ["15835" as TypeId]: "high",
  ["15836" as TypeId]: "high",
  ["15837" as TypeId]: "high",
  ["15838" as TypeId]: "high",
  ["15840" as TypeId]: "high",
  ["15841" as TypeId]: "high",
  ["15843" as TypeId]: "high",
  ["15844" as TypeId]: "high",
  ["15845" as TypeId]: "high",
  ["15846" as TypeId]: "high",
  ["15847" as TypeId]: "high",
  ["15848" as TypeId]: "high",
  ["15849" as TypeId]: "high",
  ["15850" as TypeId]: "high",
  ["15851" as TypeId]: "high",
  ["15852" as TypeId]: "high",
  ["15853" as TypeId]: "high",
  ["15854" as TypeId]: "high",
  ["15855" as TypeId]: "high",
  ["15856" as TypeId]: "high",
  ["15857" as TypeId]: "high",
  ["15858" as TypeId]: "high",
  ["15859" as TypeId]: "high",
  ["15860" as TypeId]: "high",
  ["15861" as TypeId]: "high",
  ["15862" as TypeId]: "high",
  ["15863" as TypeId]: "high",
  ["15864" as TypeId]: "high",
  ["15865" as TypeId]: "high",
  ["15866" as TypeId]: "high",
  ["15867" as TypeId]: "high",
  ["15868" as TypeId]: "high",
  ["15869" as TypeId]: "high",
  ["15870" as TypeId]: "high",
  ["15871" as TypeId]: "high",
  ["15872" as TypeId]: "high",
  ["15873" as TypeId]: "high",
  ["15874" as TypeId]: "high",
  ["15887" as TypeId]: "mid",
  ["15893" as TypeId]: "mid",
  ["15965" as TypeId]: "low",
  ["16046" as TypeId]: "high",
  ["16047" as TypeId]: "high",
  ["16048" as TypeId]: "high",
  ["16049" as TypeId]: "high",
  ["16050" as TypeId]: "high",
  ["16051" as TypeId]: "high",
  ["16052" as TypeId]: "high",
  ["16053" as TypeId]: "high",
  ["16054" as TypeId]: "high",
  ["16055" as TypeId]: "high",
  ["16056" as TypeId]: "high",
  ["16057" as TypeId]: "high",
  ["16058" as TypeId]: "high",
  ["16059" as TypeId]: "high",
  ["16060" as TypeId]: "high",
  ["17500" as TypeId]: "mid",
  ["17559" as TypeId]: "mid",
  ["18658" as TypeId]: "mid",
  ["18660" as TypeId]: "mid",
  ["18662" as TypeId]: "mid",
  ["18664" as TypeId]: "mid",
  ["18666" as TypeId]: "mid",
  ["18668" as TypeId]: "mid",
  ["18670" as TypeId]: "mid",
  ["18672" as TypeId]: "mid",
  ["18674" as TypeId]: "mid",
  ["18676" as TypeId]: "mid",
  ["18680" as TypeId]: "mid",
  ["18682" as TypeId]: "mid",
  ["18684" as TypeId]: "mid",
  ["18686" as TypeId]: "mid",
  ["18688" as TypeId]: "mid",
  ["18690" as TypeId]: "mid",
  ["18692" as TypeId]: "mid",
  ["18694" as TypeId]: "mid",
  ["18696" as TypeId]: "mid",
  ["18698" as TypeId]: "mid",
  ["19313" as TypeId]: "mid",
  ["19315" as TypeId]: "mid",
  ["19317" as TypeId]: "mid",
  ["19319" as TypeId]: "mid",
  ["19321" as TypeId]: "mid",
  ["19323" as TypeId]: "mid",
  ["19325" as TypeId]: "mid",
  ["19327" as TypeId]: "mid",
  ["19329" as TypeId]: "mid",
  ["19335" as TypeId]: "mid",
  ["19337" as TypeId]: "mid",
  ["19339" as TypeId]: "mid",
  ["19341" as TypeId]: "mid",
  ["19343" as TypeId]: "mid",
  ["19345" as TypeId]: "mid",
  ["19347" as TypeId]: "mid",
  ["19349" as TypeId]: "mid",
  ["19351" as TypeId]: "mid",
  ["19353" as TypeId]: "mid",
  ["19359" as TypeId]: "mid",
  ["20345" as TypeId]: "low",
  ["20347" as TypeId]: "low",
  ["20349" as TypeId]: "low",
  ["20351" as TypeId]: "low",
  ["20353" as TypeId]: "low",
  ["20444" as TypeId]: "high",
  ["20446" as TypeId]: "high",
  ["20448" as TypeId]: "high",
  ["20450" as TypeId]: "high",
  ["20452" as TypeId]: "high",
  ["20454" as TypeId]: "high",
  ["20587" as TypeId]: "high",
  ["20589" as TypeId]: "high",
  ["20591" as TypeId]: "high",
  ["20625" as TypeId]: "mid",
  ["20629" as TypeId]: "mid",
  ["20631" as TypeId]: "mid",
  ["21470" as TypeId]: "mid",
  ["21472" as TypeId]: "mid",
  ["21474" as TypeId]: "mid",
  ["21476" as TypeId]: "mid",
  ["21478" as TypeId]: "mid",
  ["21480" as TypeId]: "mid",
  ["21491" as TypeId]: "low",
  ["21496" as TypeId]: "low",
  ["21498" as TypeId]: "low",
  ["21500" as TypeId]: "low",
  ["21512" as TypeId]: "mid",
  ["21545" as TypeId]: "high",
  ["21547" as TypeId]: "high",
  ["21549" as TypeId]: "high",
  ["21551" as TypeId]: "high",
  ["21553" as TypeId]: "high",
  ["21555" as TypeId]: "high",
  ["21557" as TypeId]: "high",
  ["21559" as TypeId]: "high",
  ["21561" as TypeId]: "high",
  ["21857" as TypeId]: "mid",
  ["22899" as TypeId]: "high",
  ["22901" as TypeId]: "high",
  ["22903" as TypeId]: "high",
  ["22905" as TypeId]: "high",
  ["22907" as TypeId]: "high",
  ["22909" as TypeId]: "high",
  ["22911" as TypeId]: "high",
  ["22913" as TypeId]: "high",
  ["22915" as TypeId]: "high",
  ["22929" as TypeId]: "mid",
  ["22933" as TypeId]: "mid",
  ["23783" as TypeId]: "low",
  ["23785" as TypeId]: "low",
  ["23787" as TypeId]: "low",
  ["23789" as TypeId]: "low",
  ["23791" as TypeId]: "low",
  ["23793" as TypeId]: "low",
  ["23834" as TypeId]: "high",
  ["23836" as TypeId]: "high",
  ["23838" as TypeId]: "high",
  ["23840" as TypeId]: "high",
  ["23842" as TypeId]: "high",
  ["23844" as TypeId]: "high",
  ["23846" as TypeId]: "high",
  ["23848" as TypeId]: "high",
  ["23850" as TypeId]: "high",
  ["25736" as TypeId]: "rig",
  ["25888" as TypeId]: "rig",
  ["25890" as TypeId]: "rig",
  ["25892" as TypeId]: "rig",
  ["25894" as TypeId]: "rig",
  ["25900" as TypeId]: "rig",
  ["25906" as TypeId]: "rig",
  ["25970" as TypeId]: "rig",
  ["25972" as TypeId]: "rig",
  ["25974" as TypeId]: "rig",
  ["25998" as TypeId]: "rig",
  ["26000" as TypeId]: "rig",
  ["26002" as TypeId]: "rig",
  ["26038" as TypeId]: "rig",
  ["26040" as TypeId]: "rig",
  ["26042" as TypeId]: "rig",
  ["26058" as TypeId]: "rig",
  ["26060" as TypeId]: "rig",
  ["26066" as TypeId]: "rig",
  ["26068" as TypeId]: "rig",
  ["26070" as TypeId]: "rig",
  ["26076" as TypeId]: "rig",
  ["26078" as TypeId]: "rig",
  ["26080" as TypeId]: "rig",
  ["26082" as TypeId]: "rig",
  ["26084" as TypeId]: "rig",
  ["26086" as TypeId]: "rig",
  ["26088" as TypeId]: "rig",
  ["26090" as TypeId]: "rig",
  ["26286" as TypeId]: "rig",
  ["26288" as TypeId]: "rig",
  ["26290" as TypeId]: "rig",
  ["26292" as TypeId]: "rig",
  ["26298" as TypeId]: "rig",
  ["26302" as TypeId]: "rig",
  ["26310" as TypeId]: "rig",
  ["26312" as TypeId]: "rig",
  ["26318" as TypeId]: "rig",
  ["26320" as TypeId]: "rig",
  ["26322" as TypeId]: "rig",
  ["26386" as TypeId]: "rig",
  ["26388" as TypeId]: "rig",
  ["26390" as TypeId]: "rig",
  ["26400" as TypeId]: "rig",
  ["26402" as TypeId]: "rig",
  ["26404" as TypeId]: "rig",
  ["26428" as TypeId]: "rig",
  ["26432" as TypeId]: "rig",
  ["26434" as TypeId]: "rig",
  ["26436" as TypeId]: "rig",
  ["26438" as TypeId]: "rig",
  ["26440" as TypeId]: "rig",
  ["26442" as TypeId]: "rig",
  ["26444" as TypeId]: "rig",
  ["26446" as TypeId]: "rig",
  ["26448" as TypeId]: "rig",
  ["26450" as TypeId]: "rig",
  ["26452" as TypeId]: "rig",
  ["27068" as TypeId]: "rig",
  ["28514" as TypeId]: "mid",
  ["28518" as TypeId]: "mid",
  ["28744" as TypeId]: "mid",
  ["28746" as TypeId]: "mid",
  ["28778" as TypeId]: "low",
  ["28780" as TypeId]: "low",
  ["28782" as TypeId]: "low",
  ["28784" as TypeId]: "low",
  ["28786" as TypeId]: "low",
  ["30328" as TypeId]: "mid",
  ["30987" as TypeId]: "rig",
  ["30993" as TypeId]: "rig",
  ["30997" as TypeId]: "rig",
  ["30999" as TypeId]: "rig",
  ["31001" as TypeId]: "rig",
  ["31003" as TypeId]: "rig",
  ["31005" as TypeId]: "rig",
  ["31007" as TypeId]: "rig",
  ["31009" as TypeId]: "rig",
  ["31011" as TypeId]: "rig",
  ["31013" as TypeId]: "rig",
  ["31015" as TypeId]: "rig",
  ["31017" as TypeId]: "rig",
  ["31019" as TypeId]: "rig",
  ["31021" as TypeId]: "rig",
  ["31023" as TypeId]: "rig",
  ["31025" as TypeId]: "rig",
  ["31027" as TypeId]: "rig",
  ["31029" as TypeId]: "rig",
  ["31031" as TypeId]: "rig",
  ["31033" as TypeId]: "rig",
  ["31035" as TypeId]: "rig",
  ["31037" as TypeId]: "rig",
  ["31039" as TypeId]: "rig",
  ["31041" as TypeId]: "rig",
  ["31043" as TypeId]: "rig",
  ["31055" as TypeId]: "rig",
  ["31057" as TypeId]: "rig",
  ["31059" as TypeId]: "rig",
  ["31061" as TypeId]: "rig",
  ["31073" as TypeId]: "rig",
  ["31075" as TypeId]: "rig",
  ["31077" as TypeId]: "rig",
  ["31079" as TypeId]: "rig",
  ["31081" as TypeId]: "rig",
  ["31105" as TypeId]: "rig",
  ["31107" as TypeId]: "rig",
  ["31109" as TypeId]: "rig",
  ["31111" as TypeId]: "rig",
  ["31113" as TypeId]: "rig",
  ["31115" as TypeId]: "rig",
  ["31153" as TypeId]: "rig",
  ["31155" as TypeId]: "rig",
  ["31157" as TypeId]: "rig",
  ["31159" as TypeId]: "rig",
  ["31161" as TypeId]: "rig",
  ["31163" as TypeId]: "rig",
  ["31165" as TypeId]: "rig",
  ["31167" as TypeId]: "rig",
  ["31169" as TypeId]: "rig",
  ["31171" as TypeId]: "rig",
  ["31173" as TypeId]: "rig",
  ["31175" as TypeId]: "rig",
  ["31177" as TypeId]: "rig",
  ["31179" as TypeId]: "rig",
  ["31181" as TypeId]: "rig",
  ["31183" as TypeId]: "rig",
  ["31185" as TypeId]: "rig",
  ["31187" as TypeId]: "rig",
  ["31189" as TypeId]: "rig",
  ["31191" as TypeId]: "rig",
  ["31193" as TypeId]: "rig",
  ["31195" as TypeId]: "rig",
  ["31197" as TypeId]: "rig",
  ["31199" as TypeId]: "rig",
  ["31430" as TypeId]: "rig",
  ["31432" as TypeId]: "rig",
  ["31434" as TypeId]: "rig",
  ["31436" as TypeId]: "rig",
  ["31438" as TypeId]: "rig",
  ["31440" as TypeId]: "rig",
  ["31478" as TypeId]: "rig",
  ["31480" as TypeId]: "rig",
  ["31482" as TypeId]: "rig",
  ["31484" as TypeId]: "rig",
  ["31486" as TypeId]: "rig",
  ["31488" as TypeId]: "rig",
  ["31490" as TypeId]: "rig",
  ["31492" as TypeId]: "rig",
  ["31494" as TypeId]: "rig",
  ["31496" as TypeId]: "rig",
  ["31498" as TypeId]: "rig",
  ["31500" as TypeId]: "rig",
  ["31514" as TypeId]: "rig",
  ["31516" as TypeId]: "rig",
  ["31518" as TypeId]: "rig",
  ["31520" as TypeId]: "rig",
  ["31522" as TypeId]: "rig",
  ["31524" as TypeId]: "rig",
  ["31562" as TypeId]: "rig",
  ["31564" as TypeId]: "rig",
  ["31566" as TypeId]: "rig",
  ["31568" as TypeId]: "rig",
  ["31570" as TypeId]: "rig",
  ["31572" as TypeId]: "rig",
  ["31574" as TypeId]: "rig",
  ["31576" as TypeId]: "rig",
  ["31578" as TypeId]: "rig",
  ["31580" as TypeId]: "rig",
  ["31582" as TypeId]: "rig",
  ["31584" as TypeId]: "rig",
  ["31656" as TypeId]: "rig",
  ["31658" as TypeId]: "rig",
  ["31660" as TypeId]: "rig",
  ["31662" as TypeId]: "rig",
  ["31664" as TypeId]: "rig",
  ["31666" as TypeId]: "rig",
  ["31692" as TypeId]: "rig",
  ["31694" as TypeId]: "rig",
  ["31696" as TypeId]: "rig",
  ["31698" as TypeId]: "rig",
  ["31700" as TypeId]: "rig",
  ["31702" as TypeId]: "rig",
  ["31704" as TypeId]: "rig",
  ["31706" as TypeId]: "rig",
  ["31708" as TypeId]: "rig",
  ["31710" as TypeId]: "rig",
  ["31712" as TypeId]: "rig",
  ["31714" as TypeId]: "rig",
  ["31716" as TypeId]: "rig",
  ["31718" as TypeId]: "rig",
  ["31720" as TypeId]: "rig",
  ["31722" as TypeId]: "rig",
  ["31724" as TypeId]: "rig",
  ["31726" as TypeId]: "rig",
  ["31728" as TypeId]: "rig",
  ["31730" as TypeId]: "rig",
  ["31732" as TypeId]: "rig",
  ["31734" as TypeId]: "rig",
  ["31736" as TypeId]: "rig",
  ["31738" as TypeId]: "rig",
  ["31740" as TypeId]: "rig",
  ["31742" as TypeId]: "rig",
  ["31744" as TypeId]: "rig",
  ["31746" as TypeId]: "rig",
  ["31748" as TypeId]: "rig",
  ["31750" as TypeId]: "rig",
  ["31752" as TypeId]: "rig",
  ["31754" as TypeId]: "rig",
  ["31756" as TypeId]: "rig",
  ["31758" as TypeId]: "rig",
  ["31760" as TypeId]: "rig",
  ["31762" as TypeId]: "rig",
  ["31764" as TypeId]: "rig",
  ["31766" as TypeId]: "rig",
  ["31768" as TypeId]: "rig",
  ["31770" as TypeId]: "rig",
  ["31772" as TypeId]: "rig",
  ["31774" as TypeId]: "rig",
  ["31776" as TypeId]: "rig",
  ["31778" as TypeId]: "rig",
  ["31780" as TypeId]: "rig",
  ["31782" as TypeId]: "rig",
  ["31784" as TypeId]: "rig",
  ["31786" as TypeId]: "rig",
  ["31788" as TypeId]: "rig",
  ["31790" as TypeId]: "rig",
  ["31792" as TypeId]: "rig",
  ["31794" as TypeId]: "rig",
  ["31796" as TypeId]: "rig",
  ["31798" as TypeId]: "rig",
  ["31800" as TypeId]: "rig",
  ["31802" as TypeId]: "rig",
  ["31804" as TypeId]: "rig",
  ["31810" as TypeId]: "rig",
  ["31812" as TypeId]: "rig",
  ["31814" as TypeId]: "rig",
  ["31816" as TypeId]: "rig",
  ["31818" as TypeId]: "rig",
  ["31820" as TypeId]: "rig",
  ["31822" as TypeId]: "rig",
  ["31824" as TypeId]: "rig",
  ["31826" as TypeId]: "rig",
  ["31896" as TypeId]: "low",
  ["31898" as TypeId]: "low",
  ["31900" as TypeId]: "low",
  ["31902" as TypeId]: "low",
  ["31904" as TypeId]: "low",
  ["31906" as TypeId]: "low",
  ["31908" as TypeId]: "low",
  ["31910" as TypeId]: "low",
  ["31916" as TypeId]: "low",
  ["31918" as TypeId]: "low",
  ["31922" as TypeId]: "mid",
  ["31924" as TypeId]: "mid",
  ["31926" as TypeId]: "mid",
  ["31928" as TypeId]: "mid",
  ["31930" as TypeId]: "mid",
  ["31932" as TypeId]: "mid",
  ["34266" as TypeId]: "rig",
  ["34268" as TypeId]: "rig",
  ["34272" as TypeId]: "high",
  ["34274" as TypeId]: "high",
  ["34276" as TypeId]: "high",
  ["34278" as TypeId]: "high",
  ["34280" as TypeId]: "high",
  ["34282" as TypeId]: "high",
  ["34284" as TypeId]: "high",
  ["34286" as TypeId]: "high",
  ["34288" as TypeId]: "high",
  ["34306" as TypeId]: "rig",
  ["34308" as TypeId]: "rig",
  ["34481" as TypeId]: "low",
  ["34483" as TypeId]: "low",
  ["34485" as TypeId]: "low",
  ["34487" as TypeId]: "low",
  ["35656" as TypeId]: "mid",
  ["35657" as TypeId]: "mid",
  ["35658" as TypeId]: "mid",
  ["35659" as TypeId]: "mid",
  ["35660" as TypeId]: "mid",
  ["35661" as TypeId]: "mid",
  ["35662" as TypeId]: "mid",
  ["37289" as TypeId]: "high",
  ["37290" as TypeId]: "high",
  ["37291" as TypeId]: "high",
  ["37296" as TypeId]: "high",
  ["37297" as TypeId]: "high",
  ["37298" as TypeId]: "high",
  ["37299" as TypeId]: "high",
  ["37300" as TypeId]: "high",
  ["37301" as TypeId]: "high",
  ["37302" as TypeId]: "high",
  ["37303" as TypeId]: "high",
  ["37304" as TypeId]: "high",
  ["37305" as TypeId]: "high",
  ["37306" as TypeId]: "high",
  ["37307" as TypeId]: "high",
  ["40348" as TypeId]: "low",
  ["40349" as TypeId]: "low",
  ["40350" as TypeId]: "low",
  ["40351" as TypeId]: "low",
  ["40354" as TypeId]: "mid",
  ["40355" as TypeId]: "mid",
  ["40356" as TypeId]: "mid",
  ["40357" as TypeId]: "mid",
  ["40750" as TypeId]: "mid",
  ["40752" as TypeId]: "mid",
  ["40754" as TypeId]: "mid",
  ["40756" as TypeId]: "mid",
  ["40758" as TypeId]: "mid",
  ["40762" as TypeId]: "mid",
  ["40764" as TypeId]: "mid",
  ["41038" as TypeId]: "mid",
  ["41040" as TypeId]: "mid",
  ["41054" as TypeId]: "mid",
  ["41055" as TypeId]: "mid",
  ["41056" as TypeId]: "mid",
  ["41057" as TypeId]: "mid",
  ["41058" as TypeId]: "mid",
  ["41059" as TypeId]: "mid",
  ["41061" as TypeId]: "mid",
  ["41063" as TypeId]: "high",
  ["41064" as TypeId]: "high",
  ["41065" as TypeId]: "high",
  ["41066" as TypeId]: "high",
  ["41067" as TypeId]: "high",
  ["41076" as TypeId]: "high",
  ["41077" as TypeId]: "high",
  ["41078" as TypeId]: "high",
  ["41079" as TypeId]: "high",
  ["41080" as TypeId]: "high",
  ["41081" as TypeId]: "high",
  ["41082" as TypeId]: "high",
  ["41083" as TypeId]: "high",
  ["41099" as TypeId]: "high",
  ["41100" as TypeId]: "high",
  ["41101" as TypeId]: "high",
  ["41102" as TypeId]: "high",
  ["41103" as TypeId]: "high",
  ["41104" as TypeId]: "high",
  ["41114" as TypeId]: "high",
  ["41115" as TypeId]: "high",
  ["41116" as TypeId]: "high",
  ["41117" as TypeId]: "high",
  ["41118" as TypeId]: "high",
  ["41119" as TypeId]: "high",
  ["41126" as TypeId]: "high",
  ["41127" as TypeId]: "high",
  ["41128" as TypeId]: "high",
  ["41129" as TypeId]: "high",
  ["41130" as TypeId]: "high",
  ["41138" as TypeId]: "high",
  ["41139" as TypeId]: "high",
  ["41140" as TypeId]: "high",
  ["41141" as TypeId]: "high",
  ["41142" as TypeId]: "high",
  ["41150" as TypeId]: "high",
  ["41151" as TypeId]: "high",
  ["41152" as TypeId]: "high",
  ["41153" as TypeId]: "high",
  ["41154" as TypeId]: "high",
  ["41156" as TypeId]: "high",
  ["41157" as TypeId]: "high",
  ["41158" as TypeId]: "high",
  ["41159" as TypeId]: "high",
  ["41160" as TypeId]: "high",
  ["41236" as TypeId]: "mid",
  ["41237" as TypeId]: "mid",
  ["41238" as TypeId]: "mid",
  ["41239" as TypeId]: "mid",
  ["41240" as TypeId]: "mid",
  ["41241" as TypeId]: "mid",
  ["41249" as TypeId]: "mid",
  ["41250" as TypeId]: "mid",
  ["41251" as TypeId]: "mid",
  ["41252" as TypeId]: "mid",
  ["41253" as TypeId]: "mid",
  ["41254" as TypeId]: "mid",
  ["41255" as TypeId]: "mid",
  ["41456" as TypeId]: "low",
  ["41457" as TypeId]: "low",
  ["41458" as TypeId]: "low",
  ["41459" as TypeId]: "mid",
  ["41460" as TypeId]: "mid",
  ["41461" as TypeId]: "mid",
  ["41462" as TypeId]: "mid",
  ["47408" as TypeId]: "mid",
  ["47740" as TypeId]: "mid",
  ["47745" as TypeId]: "mid",
  ["47749" as TypeId]: "mid",
  ["47753" as TypeId]: "mid",
  ["47757" as TypeId]: "mid",
  ["56305" as TypeId]: "mid",
  ["56306" as TypeId]: "mid",
  ["84743" as TypeId]: "mid",
  ["84962" as TypeId]: "mid",
  ["84963" as TypeId]: "mid",
  ["84964" as TypeId]: "mid",
  ["84965" as TypeId]: "mid",
  ["84966" as TypeId]: "mid",
  ["84967" as TypeId]: "mid",
  ["84968" as TypeId]: "mid",
  ["84969" as TypeId]: "mid",
  ["85008" as TypeId]: "high",
  ["85009" as TypeId]: "high",
  ["85010" as TypeId]: "high",
  ["85011" as TypeId]: "high",
  ["85012" as TypeId]: "high",
  ["85013" as TypeId]: "high",
  ["85014" as TypeId]: "high",
  ["85015" as TypeId]: "high",
  ["85025" as TypeId]: "mid",
  ["85026" as TypeId]: "mid",
  ["85031" as TypeId]: "mid",
  ["85032" as TypeId]: "mid",
  ["92454" as TypeId]: "low",
  ["93913" as TypeId]: "low",
  ["95556" as TypeId]: "low",
} as const;
