export type ModuleSlot = "high" | "mid" | "low" | "rig";

export const MODULE_SLOTS: Readonly<Record<string, ModuleSlot>> = {
  "'Abatis' 100mm Steel Plates": "low",
  "'Arquebus' Heavy Beam Laser I": "high",
  "'Bailey' 1600mm Steel Plates": "low",
  "'Ballista' Tachyon Beam Laser I": "high",
  "'Barbican' 800mm Steel Plates": "low",
  "'Basic' Inertial Stabilizers": "low",
  "'Basic' Nanofiber Internal Structure": "low",
  "'Basic' Overdrive Injector System": "low",
  "'Basic' Reinforced Bulkheads": "low",
  "'Basic' Tracking Enhancer": "low",
  "'Bastion' 400mm Steel Plates": "low",
  "'Catapult' Mega Beam Laser I": "high",
  "'Chainmail' 200mm Steel Plates": "low",
  "'Citadella' 100mm Steel Plates": "low",
  "'Corporate' Light Electron Blaster I": "high",
  "'Crossbow' Focused Medium Beam Laser I": "high",
  "'Dealer' Light Ion Blaster I": "high",
  "'Felon' Ion Blaster Cannon I": "high",
  "'Gauntlet' Small Focused Beam Laser I": "high",
  "'Halberd' Mega Pulse Laser I": "high",
  "'Hooligan' Heavy Ion Blaster I": "high",
  "'Hustler' Heavy Neutron Blaster I": "high",
  "'Investor' Tracking Disruptor I": "mid",
  "'Joust' Heavy Pulse Laser I": "high",
  "'Longbow' Small Focused Pulse Laser I": "high",
  "'Mace' Dual Light Beam Laser I": "high",
  "'Marketeer' Tracking Computer": "mid",
  "'Racket' Light Neutron Blaster I": "high",
  "'Slither' Heavy Electron Blaster I": "high",
  "'Swindler' Electron Blaster Cannon I": "high",
  "'Underhand' Neutron Blaster Cannon I": "high",
  "10000MN Abyssal Afterburner": "mid",
  "10000MN Afterburner I": "mid",
  "10000MN Afterburner II": "mid",
  "10000MN Monopropellant Enduring Afterburner": "mid",
  "10000MN Y-S8 Compact Afterburner": "mid",
  "100MN Abyssal Afterburner": "mid",
  "100MN Afterburner I": "mid",
  "100MN Afterburner II": "mid",
  "100MN Analog Booster Afterburner": "mid",
  "100MN Monopropellant Enduring Afterburner": "mid",
  "100MN Y-S8 Compact Afterburner": "mid",
  "100mm Crystalline Carbonide Restrained Plates": "low",
  "100mm Rolled Tungsten Compact Plates": "low",
  "100mm Steel Plates I": "low",
  "100mm Steel Plates II": "low",
  "10MN Abyssal Afterburner": "mid",
  "10MN Afterburner I": "mid",
  "10MN Afterburner II": "mid",
  "10MN Analog Booster Afterburner": "mid",
  "10MN Monopropellant Enduring Afterburner": "mid",
  "10MN Y-S8 Compact Afterburner": "mid",
  "1200mm Artillery Cannon I": "high",
  "1200mm Artillery Cannon II": "high",
  "1200mm Heavy 'Jolt' Artillery I": "high",
  "1200mm Heavy 'Scout' Artillery I": "high",
  "1200mm Heavy Carbine Howitzer I": "high",
  "1200mm Heavy Gallium Cannon": "high",
  "1200mm Heavy Prototype Siege Cannon": "high",
  "125mm 'Scout' Accelerator Cannon": "high",
  "125mm Carbide Railgun I": "high",
  "125mm Compressed Coil Gun I": "high",
  "125mm Gatling AutoCannon I": "high",
  "125mm Gatling AutoCannon II": "high",
  "125mm Light 'Scout' Autocannon I": "high",
  "125mm Light Carbine Repeating Cannon I": "high",
  "125mm Light Gallium Machine Gun": "high",
  "125mm Light Prototype Automatic Cannon": "high",
  "125mm Prototype Gauss Gun": "high",
  "125mm Railgun I": "high",
  "125mm Railgun II": "high",
  "1400mm 'Jolt' Artillery I": "high",
  "1400mm 'Scout' Artillery I": "high",
  "1400mm Carbine Howitzer I": "high",
  "1400mm Gallium Cannon": "high",
  "1400mm Howitzer Artillery I": "high",
  "1400mm Howitzer Artillery II": "high",
  "1400mm Prototype Siege Cannon": "high",
  "150mm 'Musket' Railgun": "high",
  "150mm 'Scout' Accelerator Cannon": "high",
  "150mm Carbide Railgun I": "high",
  "150mm Compressed Coil Gun I": "high",
  "150mm Light 'Scout' Autocannon I": "high",
  "150mm Light AutoCannon I": "high",
  "150mm Light AutoCannon II": "high",
  "150mm Light Carbine Repeating Cannon I": "high",
  "150mm Light Gallium Machine Gun": "high",
  "150mm Light Prototype Automatic Cannon": "high",
  "150mm Prototype Gauss Gun": "high",
  "150mm Railgun I": "high",
  "150mm Railgun II": "high",
  "1600mm Crystalline Carbonide Restrained Plates": "low",
  "1600mm Rolled Tungsten Compact Plates": "low",
  "1600mm Steel Plates I": "low",
  "1600mm Steel Plates II": "low",
  "1MN Abyssal Afterburner": "mid",
  "1MN Afterburner I": "mid",
  "1MN Afterburner II": "mid",
  "1MN Analog Booster Afterburner": "mid",
  "1MN Civilian Afterburner": "mid",
  "1MN Monopropellant Enduring Afterburner": "mid",
  "1MN Y-S8 Compact Afterburner": "mid",
  "200mm 'Scout' Accelerator Cannon": "high",
  "200mm AutoCannon I": "high",
  "200mm AutoCannon II": "high",
  "200mm Carbide Railgun I": "high",
  "200mm Compressed Coil Gun I": "high",
  "200mm Crystalline Carbonide Restrained Plates": "low",
  "200mm Light 'Jolt' Autocannon I": "high",
  "200mm Light 'Scout' Autocannon I": "high",
  "200mm Light Carbine Repeating Cannon I": "high",
  "200mm Light Gallium Machine Gun": "high",
  "200mm Light Prototype Automatic Cannon": "high",
  "200mm Prototype Gauss Gun": "high",
  "200mm Railgun I": "high",
  "200mm Railgun II": "high",
  "200mm Rolled Tungsten Compact Plates": "low",
  "200mm Steel Plates I": "low",
  "200mm Steel Plates II": "low",
  "220mm Medium 'Scout' Autocannon I": "high",
  "220mm Medium Carbine Repeating Cannon I": "high",
  "220mm Medium Gallium Machine Gun": "high",
  "220mm Medium Prototype Automatic Cannon": "high",
  "220mm Vulcan AutoCannon I": "high",
  "220mm Vulcan AutoCannon II": "high",
  "25000mm Crystalline Carbonide Restrained Plates": "low",
  "25000mm Rolled Tungsten Compact Plates": "low",
  "25000mm Steel Plates I": "low",
  "25000mm Steel Plates II": "low",
  "250mm 'Flintlock' Railgun": "high",
  "250mm 'Scout' Accelerator Cannon": "high",
  "250mm Carbide Railgun I": "high",
  "250mm Compressed Coil Gun I": "high",
  "250mm Light 'Jolt' Artillery I": "high",
  "250mm Light 'Scout' Artillery I": "high",
  "250mm Light Artillery Cannon I": "high",
  "250mm Light Artillery Cannon II": "high",
  "250mm Light Carbine Howitzer I": "high",
  "250mm Light Gallium Cannon": "high",
  "250mm Light Prototype Siege Cannon": "high",
  "250mm Prototype Gauss Gun": "high",
  "250mm Railgun I": "high",
  "250mm Railgun II": "high",
  "280mm 'Jolt' Artillery I": "high",
  "280mm 'Scout' Artillery I": "high",
  "280mm Carbine Howitzer I": "high",
  "280mm Gallium Cannon": "high",
  "280mm Howitzer Artillery I": "high",
  "280mm Howitzer Artillery II": "high",
  "280mm Prototype Siege Cannon": "high",
  "350mm 'Scout' Accelerator Cannon": "high",
  "350mm Carbide Railgun I": "high",
  "350mm Compressed Coil Gun I": "high",
  "350mm Prototype Gauss Gun": "high",
  "350mm Railgun I": "high",
  "350mm Railgun II": "high",
  "400mm Crystalline Carbonide Restrained Plates": "low",
  "400mm Rolled Tungsten Compact Plates": "low",
  "400mm Steel Plates I": "low",
  "400mm Steel Plates II": "low",
  "425mm 'Popper' Railgun": "high",
  "425mm 'Scout' Accelerator Cannon": "high",
  "425mm AutoCannon I": "high",
  "425mm AutoCannon II": "high",
  "425mm Carbide Railgun I": "high",
  "425mm Compressed Coil Gun I": "high",
  "425mm Medium 'Jolt' Autocannon I": "high",
  "425mm Medium 'Scout' Autocannon I": "high",
  "425mm Medium Carbine Repeating Cannon I": "high",
  "425mm Medium Gallium Machine Gun": "high",
  "425mm Medium Prototype Automatic Cannon": "high",
  "425mm Prototype Gauss Gun": "high",
  "425mm Railgun I": "high",
  "425mm Railgun II": "high",
  "50000MN Abyssal Microwarpdrive": "mid",
  "50000MN Cold-Gas Enduring Microwarpdrive": "mid",
  "50000MN Microwarpdrive I": "mid",
  "50000MN Microwarpdrive II": "mid",
  "50000MN Quad LiF Restrained Microwarpdrive": "mid",
  "50000MN Y-T8 Compact Microwarpdrive": "mid",
  "500MN Abyssal Microwarpdrive": "mid",
  "500MN Cold-Gas Enduring Microwarpdrive": "mid",
  "500MN Digital Booster Microwarpdrive": "mid",
  "500MN Microwarpdrive I": "mid",
  "500MN Microwarpdrive II": "mid",
  "500MN Quad LiF Restrained Microwarpdrive": "mid",
  "500MN Y-T8 Compact Microwarpdrive": "mid",
  "50MN Abyssal Microwarpdrive": "mid",
  "50MN Cold-Gas Enduring Microwarpdrive": "mid",
  "50MN Digital Booster Microwarpdrive": "mid",
  "50MN Microwarpdrive I": "mid",
  "50MN Microwarpdrive II": "mid",
  "50MN Quad LiF Restrained Microwarpdrive": "mid",
  "50MN Y-T8 Compact Microwarpdrive": "mid",
  "5MN Abyssal Microwarpdrive": "mid",
  "5MN Cold-Gas Enduring Microwarpdrive": "mid",
  "5MN Digital Booster Microwarpdrive": "mid",
  "5MN Microwarpdrive I": "mid",
  "5MN Microwarpdrive II": "mid",
  "5MN Quad LiF Restrained Microwarpdrive": "mid",
  "5MN Y-T8 Compact Microwarpdrive": "mid",
  "650mm Artillery Cannon I": "high",
  "650mm Artillery Cannon II": "high",
  "650mm Medium 'Jolt' Artillery I": "high",
  "650mm Medium 'Scout' Artillery I": "high",
  "650mm Medium Carbine Howitzer I": "high",
  "650mm Medium Gallium Cannon": "high",
  "650mm Medium Prototype Siege Cannon": "high",
  "720mm 'Jolt' Artillery I": "high",
  "720mm 'Scout' Artillery I": "high",
  "720mm Carbine Howitzer I": "high",
  "720mm Gallium Cannon": "high",
  "720mm Howitzer Artillery I": "high",
  "720mm Howitzer Artillery II": "high",
  "720mm Prototype Siege Cannon": "high",
  "75mm 'Scout' Accelerator Cannon": "high",
  "75mm Carbide Railgun I": "high",
  "75mm Compressed Coil Gun I": "high",
  "75mm Gatling Rail I": "high",
  "75mm Gatling Rail II": "high",
  "75mm Prototype Gauss Gun": "high",
  "800mm Crystalline Carbonide Restrained Plates": "low",
  "800mm Heavy 'Jolt' Repeating Cannon I": "high",
  "800mm Heavy 'Scout' Repeating Cannon I": "high",
  "800mm Heavy Carbine Repeating Cannon I": "high",
  "800mm Heavy Gallium Repeating Cannon": "high",
  "800mm Heavy Prototype Automatic Cannon": "high",
  "800mm Repeating Cannon I": "high",
  "800mm Repeating Cannon II": "high",
  "800mm Rolled Tungsten Compact Plates": "low",
  "800mm Steel Plates I": "low",
  "800mm Steel Plates II": "low",
  "Afocal Precise Dual Giga Beam Laser": "high",
  "Afocal Precise Dual Giga Pulse Laser": "high",
  "Afocal Precise Quad Mega Pulse Laser": "high",
  "Ahremen's Modified Dual Heavy Pulse Laser": "high",
  "Ahremen's Modified Mega Pulse Laser": "high",
  "Ammatar Navy Dual Heavy Beam Laser": "high",
  "Ammatar Navy Dual Heavy Pulse Laser": "high",
  "Ammatar Navy Dual Light Beam Laser": "high",
  "Ammatar Navy Dual Light Pulse Laser": "high",
  "Ammatar Navy Focused Medium Beam Laser": "high",
  "Ammatar Navy Focused Medium Pulse Laser": "high",
  "Ammatar Navy Gatling Pulse Laser": "high",
  "Ammatar Navy Heavy Beam Laser": "high",
  "Ammatar Navy Heavy Pulse Laser": "high",
  "Ammatar Navy Mega Beam Laser": "high",
  "Ammatar Navy Mega Pulse Laser": "high",
  "Ammatar Navy Quad Beam Laser": "high",
  "Ammatar Navy Small Focused Beam Laser": "high",
  "Ammatar Navy Small Focused Pulse Laser": "high",
  "Ammatar Navy Tachyon Beam Laser": "high",
  "Ample Gallium Quad 800mm Repeating Cannon": "high",
  "Anode Electron Particle Cannon I": "high",
  "Anode Ion Particle Cannon I": "high",
  "Anode Light Electron Particle Cannon I": "high",
  "Anode Light Ion Particle Cannon I": "high",
  "Anode Light Neutron Particle Cannon I": "high",
  "Anode Mega Electron Particle Cannon I": "high",
  "Anode Mega Ion Particle Cannon I": "high",
  "Anode Mega Neutron Particle Cannon I": "high",
  "Anode Neutron Particle Cannon I": "high",
  "Anode Scoped Dual Giga Beam Laser": "high",
  "Anode Scoped Dual Giga Pulse Laser": "high",
  "Anode Scoped Ion Siege Blaster": "high",
  "Anode Scoped Quad Mega Pulse Laser": "high",
  "Anode Scoped Triple Neutron Blaster Cannon": "high",
  "Asine's Modified 1MN Afterburner": "mid",
  "Asine's Modified 5MN Microwarpdrive": "mid",
  "Asine's Modified Light Neutron Blaster": "high",
  "Baker Nunn Enduring Tracking Disruptor I": "mid",
  "Balmer Series Compact Tracking Disruptor I": "mid",
  "Brokara's Modified Dual Heavy Pulse Laser": "high",
  "Brokara's Modified Mega Pulse Laser": "high",
  "Brynn's Modified 100MN Afterburner": "mid",
  "Brynn's Modified 350mm Railgun": "high",
  "Brynn's Modified 425mm Railgun": "high",
  "Brynn's Modified 500MN Microwarpdrive": "mid",
  "Brynn's Modified Dual 250mm Railgun": "high",
  "Brynn's Modified Tracking Computer": "mid",
  "CONCORD 25000mm Steel Plates": "low",
  "CONCORD Capital Shield Extender": "mid",
  "CONCORD Dual 1000mm Railgun": "high",
  "CONCORD Dual Giga Beam Laser": "high",
  "CONCORD Dual Giga Pulse Laser": "high",
  "CONCORD Hexa 2500mm Repeating Cannon": "high",
  "CONCORD Ion Siege Blaster": "high",
  "CONCORD Quad 3500mm Siege Artillery": "high",
  "Caldari Navy 125mm Railgun": "high",
  "Caldari Navy 150mm Railgun": "high",
  "Caldari Navy 200mm Railgun": "high",
  "Caldari Navy 250mm Railgun": "high",
  "Caldari Navy 350mm Railgun": "high",
  "Caldari Navy 425mm Railgun": "high",
  "Caldari Navy 75mm Railgun": "high",
  "Caldari Navy Dual 150mm Railgun": "high",
  "Caldari Navy Dual 250mm Railgun": "high",
  "Caldari Navy Large Shield Extender": "mid",
  "Caldari Navy Medium Shield Extender": "mid",
  "Caldari Navy Small Shield Extender": "mid",
  "Caldari Navy Stasis Webifier": "mid",
  "Capital Auxiliary Thrusters I": "rig",
  "Capital Auxiliary Thrusters II": "rig",
  "Capital Azeotropic Restrained Shield Extender": "mid",
  "Capital Core Defense Capacitor Safeguard I": "rig",
  "Capital Core Defense Capacitor Safeguard II": "rig",
  "Capital Core Defense Charge Economizer I": "rig",
  "Capital Core Defense Charge Economizer II": "rig",
  "Capital Core Defense Field Extender I": "rig",
  "Capital Core Defense Field Extender II": "rig",
  "Capital Core Defense Field Purger I": "rig",
  "Capital Core Defense Field Purger II": "rig",
  "Capital Core Defense Operational Solidifier I": "rig",
  "Capital Core Defense Operational Solidifier II": "rig",
  "Capital EM Armor Reinforcer I": "rig",
  "Capital EM Armor Reinforcer II": "rig",
  "Capital EM Shield Reinforcer I": "rig",
  "Capital EM Shield Reinforcer II": "rig",
  "Capital Energy Ambit Extension I": "rig",
  "Capital Energy Ambit Extension II": "rig",
  "Capital Energy Locus Coordinator I": "rig",
  "Capital Energy Locus Coordinator II": "rig",
  "Capital Energy Metastasis Adjuster I": "rig",
  "Capital Energy Metastasis Adjuster II": "rig",
  "Capital Explosive Armor Reinforcer I": "rig",
  "Capital Explosive Armor Reinforcer II": "rig",
  "Capital Explosive Shield Reinforcer I": "rig",
  "Capital Explosive Shield Reinforcer II": "rig",
  "Capital F-S9 Regolith Compact Shield Extender": "mid",
  "Capital Higgs Anchor I": "rig",
  "Capital Hybrid Ambit Extension I": "rig",
  "Capital Hybrid Ambit Extension II": "rig",
  "Capital Hybrid Locus Coordinator I": "rig",
  "Capital Hybrid Locus Coordinator II": "rig",
  "Capital Hybrid Metastasis Adjuster I": "rig",
  "Capital Hybrid Metastasis Adjuster II": "rig",
  "Capital Hyperspatial Velocity Optimizer I": "rig",
  "Capital Hyperspatial Velocity Optimizer II": "rig",
  "Capital Kinetic Armor Reinforcer I": "rig",
  "Capital Kinetic Armor Reinforcer II": "rig",
  "Capital Kinetic Shield Reinforcer I": "rig",
  "Capital Kinetic Shield Reinforcer II": "rig",
  "Capital Low Friction Nozzle Joints I": "rig",
  "Capital Low Friction Nozzle Joints II": "rig",
  "Capital Polycarbon Engine Housing I": "rig",
  "Capital Polycarbon Engine Housing II": "rig",
  "Capital Projectile Ambit Extension I": "rig",
  "Capital Projectile Ambit Extension II": "rig",
  "Capital Projectile Locus Coordinator I": "rig",
  "Capital Projectile Locus Coordinator II": "rig",
  "Capital Projectile Metastasis Adjuster I": "rig",
  "Capital Projectile Metastasis Adjuster II": "rig",
  "Capital Remote Repair Augmentor I": "rig",
  "Capital Remote Repair Augmentor II": "rig",
  "Capital Shield Extender I": "mid",
  "Capital Shield Extender II": "mid",
  "Capital Thermal Armor Reinforcer I": "rig",
  "Capital Thermal Armor Reinforcer II": "rig",
  "Capital Thermal Shield Reinforcer I": "rig",
  "Capital Thermal Shield Reinforcer II": "rig",
  "Capital Trimark Armor Pump I": "rig",
  "Capital Trimark Armor Pump II": "rig",
  "Capital Warp Core Optimizer I": "rig",
  "Capital Warp Core Optimizer II": "rig",
  "Carbide Compact Dual 1000mm Railgun": "high",
  "Carbide Compact Quad 3500mm Siege Artillery": "high",
  "Carbine Compact Hexa 2500mm Repeating Cannon": "high",
  "Chelm's Modified Dual Heavy Beam Laser": "high",
  "Chelm's Modified Mega Beam Laser": "high",
  "Chelm's Modified Tachyon Beam Laser": "high",
  "Civilian Stasis Webifier": "mid",
  "Compact Carbine Quad 800mm Repeating Cannon": "high",
  "Compressed Enduring Dual 1000mm Railgun": "high",
  "Core A-Type 100MN Afterburner": "mid",
  "Core A-Type 500MN Microwarpdrive": "mid",
  "Core B-Type 100MN Afterburner": "mid",
  "Core B-Type 500MN Microwarpdrive": "mid",
  "Core C-Type 100MN Afterburner": "mid",
  "Core C-Type 500MN Microwarpdrive": "mid",
  "Core X-Type 100MN Afterburner": "mid",
  "Core X-Type 500MN Microwarpdrive": "mid",
  "Coreli A-Type 1MN Afterburner": "mid",
  "Coreli A-Type 5MN Microwarpdrive": "mid",
  "Coreli B-Type 1MN Afterburner": "mid",
  "Coreli B-Type 5MN Microwarpdrive": "mid",
  "Coreli C-Type 1MN Afterburner": "mid",
  "Coreli C-Type 5MN Microwarpdrive": "mid",
  "Corelum A-Type 10MN Afterburner": "mid",
  "Corelum A-Type 50MN Microwarpdrive": "mid",
  "Corelum B-Type 10MN Afterburner": "mid",
  "Corelum B-Type 50MN Microwarpdrive": "mid",
  "Corelum C-Type 10MN Afterburner": "mid",
  "Corelum C-Type 50MN Microwarpdrive": "mid",
  "Cormack's Modified 100MN Afterburner": "mid",
  "Cormack's Modified 500MN Microwarpdrive": "mid",
  "Cormack's Modified Electron Blaster Cannon": "high",
  "Cormack's Modified Ion Blaster Cannon": "high",
  "Cormack's Modified Neutron Blaster Cannon": "high",
  "Cormack's Modified Tracking Computer": "mid",
  "DDO Scoped Tracking Disruptor I": "mid",
  "Dark Blood 25000mm Steel Plates": "low",
  "Dark Blood Dual Giga Beam Laser": "high",
  "Dark Blood Dual Giga Pulse Laser": "high",
  "Dark Blood Dual Heavy Beam Laser": "high",
  "Dark Blood Dual Heavy Pulse Laser": "high",
  "Dark Blood Dual Light Beam Laser": "high",
  "Dark Blood Dual Light Pulse Laser": "high",
  "Dark Blood Focused Medium Beam Laser": "high",
  "Dark Blood Focused Medium Pulse Laser": "high",
  "Dark Blood Gatling Pulse Laser": "high",
  "Dark Blood Heavy Beam Laser": "high",
  "Dark Blood Heavy Pulse Laser": "high",
  "Dark Blood Mega Beam Laser": "high",
  "Dark Blood Mega Pulse Laser": "high",
  "Dark Blood Quad Beam Laser": "high",
  "Dark Blood Quad Mega Pulse Laser": "high",
  "Dark Blood Small Focused Beam Laser": "high",
  "Dark Blood Small Focused Pulse Laser": "high",
  "Dark Blood Stasis Webifier": "mid",
  "Dark Blood Tachyon Beam Laser": "high",
  "Domination 10000MN Afterburner": "mid",
  "Domination 100MN Afterburner": "mid",
  "Domination 10MN Afterburner": "mid",
  "Domination 1200mm Artillery": "high",
  "Domination 125mm Autocannon": "high",
  "Domination 1400mm Howitzer Artillery": "high",
  "Domination 150mm Autocannon": "high",
  "Domination 1MN Afterburner": "mid",
  "Domination 200mm Autocannon": "high",
  "Domination 220mm Autocannon": "high",
  "Domination 250mm Artillery": "high",
  "Domination 280mm Howitzer Artillery": "high",
  "Domination 425mm Autocannon": "high",
  "Domination 50000MN Microwarpdrive": "mid",
  "Domination 500MN Microwarpdrive": "mid",
  "Domination 50MN Microwarpdrive": "mid",
  "Domination 5MN Microwarpdrive": "mid",
  "Domination 650mm Artillery": "high",
  "Domination 720mm Howitzer Artillery": "high",
  "Domination 800mm Repeating Cannon": "high",
  "Domination Capital Shield Extender": "mid",
  "Domination Dual 180mm Autocannon": "high",
  "Domination Dual 425mm Autocannon": "high",
  "Domination Dual 650mm Repeating Cannon": "high",
  "Domination Hexa 2500mm Repeating Cannon": "high",
  "Domination Inertial Stabilizers": "low",
  "Domination Nanofiber Structure": "low",
  "Domination Overdrive Injector": "low",
  "Domination Quad 3500mm Siege Artillery": "high",
  "Domination Quad 800mm Repeating Cannon": "high",
  "Domination Stasis Webifier": "mid",
  "Domination Tracking Enhancer": "low",
  "Draclira's Modified Dual Heavy Beam Laser": "high",
  "Draclira's Modified Mega Beam Laser": "high",
  "Draclira's Modified Tachyon Beam Laser": "high",
  "Dread Guristas 125mm Railgun": "high",
  "Dread Guristas 150mm Railgun": "high",
  "Dread Guristas 200mm Railgun": "high",
  "Dread Guristas 250mm Railgun": "high",
  "Dread Guristas 350mm Railgun": "high",
  "Dread Guristas 425mm Railgun": "high",
  "Dread Guristas 75mm Railgun": "high",
  "Dread Guristas Capital Shield Extender": "mid",
  "Dread Guristas Dual 150mm Railgun": "high",
  "Dread Guristas Dual 250mm Railgun": "high",
  "Dread Guristas Stasis Webifier": "mid",
  "Dual 1000mm Railgun I": "high",
  "Dual 1000mm Railgun II": "high",
  "Dual 150mm 'Scout' Accelerator Cannon": "high",
  "Dual 150mm Carbide Railgun I": "high",
  "Dual 150mm Compressed Coil Gun I": "high",
  "Dual 150mm Prototype Gauss Gun": "high",
  "Dual 150mm Railgun I": "high",
  "Dual 150mm Railgun II": "high",
  "Dual 180mm 'Scout' Autocannon I": "high",
  "Dual 180mm AutoCannon I": "high",
  "Dual 180mm AutoCannon II": "high",
  "Dual 180mm Carbine Repeating Cannon I": "high",
  "Dual 180mm Gallium Machine Gun": "high",
  "Dual 180mm Prototype Automatic Cannon": "high",
  "Dual 250mm 'Scout' Accelerator Cannon": "high",
  "Dual 250mm Carbide Railgun I": "high",
  "Dual 250mm Compressed Coil Gun I": "high",
  "Dual 250mm Prototype Gauss Gun": "high",
  "Dual 250mm Railgun I": "high",
  "Dual 250mm Railgun II": "high",
  "Dual 425mm 'Scout' Autocannon I": "high",
  "Dual 425mm AutoCannon I": "high",
  "Dual 425mm AutoCannon II": "high",
  "Dual 425mm Carbine Repeating Cannon I": "high",
  "Dual 425mm Gallium Machine Gun": "high",
  "Dual 425mm Prototype Automatic Cannon": "high",
  "Dual 650mm 'Scout' Repeating Cannon I": "high",
  "Dual 650mm Carbine Repeating Cannon I": "high",
  "Dual 650mm Gallium Repeating Cannon": "high",
  "Dual 650mm Prototype Automatic Cannon": "high",
  "Dual 650mm Repeating Cannon I": "high",
  "Dual 650mm Repeating Cannon II": "high",
  "Dual Afocal Heavy Laser I": "high",
  "Dual Afocal Light Laser I": "high",
  "Dual Afocal Pulse Laser I": "high",
  "Dual Anode Heavy Particle Stream I": "high",
  "Dual Anode Light Particle Stream I": "high",
  "Dual Anode Pulse Particle Stream I": "high",
  "Dual Giga Beam Laser I": "high",
  "Dual Giga Beam Laser II": "high",
  "Dual Giga Pulse Laser I": "high",
  "Dual Giga Pulse Laser II": "high",
  "Dual Heavy Afocal Pulse Laser I": "high",
  "Dual Heavy Anode Pulse Particle Stream I": "high",
  "Dual Heavy Beam Laser I": "high",
  "Dual Heavy Beam Laser II": "high",
  "Dual Heavy Modal Pulse Laser I": "high",
  "Dual Heavy Modulated Pulse Energy Beam I": "high",
  "Dual Heavy Pulse Laser I": "high",
  "Dual Heavy Pulse Laser II": "high",
  "Dual Light Beam Laser I": "high",
  "Dual Light Beam Laser II": "high",
  "Dual Light Pulse Laser I": "high",
  "Dual Light Pulse Laser II": "high",
  "Dual Modal Heavy Laser I": "high",
  "Dual Modal Light Laser I": "high",
  "Dual Modal Pulse Laser I": "high",
  "Dual Modulated Heavy Energy Beam I": "high",
  "Dual Modulated Light Energy Beam I": "high",
  "Dual Modulated Pulse Energy Beam I": "high",
  "Electron Blaster Cannon I": "high",
  "Electron Blaster Cannon II": "high",
  "Estamel's Modified 350mm Railgun": "high",
  "Estamel's Modified 425mm Railgun": "high",
  "Estamel's Modified Dual 250mm Railgun": "high",
  "F-12 Enduring Tracking Computer": "mid",
  "Federation Navy 100MN Afterburner": "mid",
  "Federation Navy 100mm Steel Plates": "low",
  "Federation Navy 10MN Afterburner": "mid",
  "Federation Navy 125mm Railgun": "high",
  "Federation Navy 150mm Railgun": "high",
  "Federation Navy 1600mm Steel Plates": "low",
  "Federation Navy 1MN Afterburner": "mid",
  "Federation Navy 200mm Railgun": "high",
  "Federation Navy 200mm Steel Plates": "low",
  "Federation Navy 250mm Railgun": "high",
  "Federation Navy 350mm Railgun": "high",
  "Federation Navy 400mm Steel Plates": "low",
  "Federation Navy 425mm Railgun": "high",
  "Federation Navy 500MN Microwarpdrive": "mid",
  "Federation Navy 50MN Microwarpdrive": "mid",
  "Federation Navy 5MN Microwarpdrive": "mid",
  "Federation Navy 75mm Railgun": "high",
  "Federation Navy 800mm Steel Plates": "low",
  "Federation Navy Dual 150mm Railgun": "high",
  "Federation Navy Dual 250mm Railgun": "high",
  "Federation Navy Electron Blaster Cannon": "high",
  "Federation Navy Heavy Electron Blaster": "high",
  "Federation Navy Heavy Ion Blaster": "high",
  "Federation Navy Heavy Neutron Blaster": "high",
  "Federation Navy Ion Blaster Cannon": "high",
  "Federation Navy Light Electron Blaster": "high",
  "Federation Navy Light Ion Blaster": "high",
  "Federation Navy Light Neutron Blaster": "high",
  "Federation Navy Neutron Blaster Cannon": "high",
  "Federation Navy Stasis Webifier": "mid",
  "Federation Navy Tracking Computer": "mid",
  "Fleeting Compact Stasis Webifier": "mid",
  "Focused Afocal Medium Laser I": "high",
  "Focused Afocal Pulse Laser I": "high",
  "Focused Anode Medium Particle Stream I": "high",
  "Focused Anode Pulse Particle Stream I": "high",
  "Focused Medium Beam Laser I": "high",
  "Focused Medium Beam Laser II": "high",
  "Focused Medium Pulse Laser I": "high",
  "Focused Medium Pulse Laser II": "high",
  "Focused Modal Medium Laser I": "high",
  "Focused Modal Pulse Laser I": "high",
  "Focused Modulated Medium Energy Beam I": "high",
  "Focused Modulated Pulse Energy Beam I": "high",
  "Fourier Compact Tracking Enhancer": "low",
  "Gallium Ample Hexa 2500mm Repeating Cannon": "high",
  "Gallium Ample Quad 3500mm Siege Artillery": "high",
  "Gara's Modified 10MN Afterburner": "mid",
  "Gara's Modified 50MN Microwarpdrive": "mid",
  "Gara's Modified Heavy Neutron Blaster": "high",
  "Gatling Afocal Laser I": "high",
  "Gatling Anode Particle Stream I": "high",
  "Gatling Modal Laser I": "high",
  "Gatling Modulated Energy Beam I": "high",
  "Gatling Pulse Laser I": "high",
  "Gatling Pulse Laser II": "high",
  "Gist A-Type 100MN Afterburner": "mid",
  "Gist A-Type 500MN Microwarpdrive": "mid",
  "Gist B-Type 100MN Afterburner": "mid",
  "Gist B-Type 500MN Microwarpdrive": "mid",
  "Gist C-Type 100MN Afterburner": "mid",
  "Gist C-Type 500MN Microwarpdrive": "mid",
  "Gist X-Type 100MN Afterburner": "mid",
  "Gist X-Type 500MN Microwarpdrive": "mid",
  "Gistii A-Type 1MN Afterburner": "mid",
  "Gistii A-Type 5MN Microwarpdrive": "mid",
  "Gistii B-Type 1MN Afterburner": "mid",
  "Gistii B-Type 5MN Microwarpdrive": "mid",
  "Gistii C-Type 1MN Afterburner": "mid",
  "Gistii C-Type 5MN Microwarpdrive": "mid",
  "Gistum A-Type 10MN Afterburner": "mid",
  "Gistum A-Type 50MN Microwarpdrive": "mid",
  "Gistum B-Type 10MN Afterburner": "mid",
  "Gistum B-Type 50MN Microwarpdrive": "mid",
  "Gistum C-Type 10MN Afterburner": "mid",
  "Gistum C-Type 50MN Microwarpdrive": "mid",
  "Gotan's Modified 100MN Afterburner": "mid",
  "Gotan's Modified 500MN Microwarpdrive": "mid",
  "Gotan's Modified 800mm Repeating Cannon": "high",
  "Gotan's Modified Dual 425mm AutoCannon": "high",
  "Gotan's Modified Dual 650mm Repeating Cannon": "high",
  "Gotan's Modified Stasis Webifier": "mid",
  "Gotan's Modified Tracking Enhancer": "low",
  "Hakim's Modified 100MN Afterburner": "mid",
  "Hakim's Modified 1200mm Artillery Cannon": "high",
  "Hakim's Modified 1400mm Howitzer Artillery": "high",
  "Hakim's Modified 500MN Microwarpdrive": "mid",
  "Hakim's Modified Stasis Webifier": "mid",
  "Hakim's Modified Tracking Enhancer": "low",
  "Heavy Afocal Laser I": "high",
  "Heavy Afocal Pulse Laser I": "high",
  "Heavy Anode Particle Stream I": "high",
  "Heavy Anode Pulse Particle Stream I": "high",
  "Heavy Beam Laser I": "high",
  "Heavy Beam Laser II": "high",
  "Heavy Electron Blaster I": "high",
  "Heavy Electron Blaster II": "high",
  "Heavy Ion Blaster I": "high",
  "Heavy Ion Blaster II": "high",
  "Heavy Modal Laser I": "high",
  "Heavy Modal Pulse Laser I": "high",
  "Heavy Modulated Energy Beam I": "high",
  "Heavy Modulated Pulse Energy Beam I": "high",
  "Heavy Neutron Blaster I": "high",
  "Heavy Neutron Blaster II": "high",
  "Heavy Pulse Laser I": "high",
  "Heavy Pulse Laser II": "high",
  "Hexa 2500mm Repeating Cannon I": "high",
  "Hexa 2500mm Repeating Cannon II": "high",
  "Imperial Navy 'Atonement' Tracking Enhancer": "low",
  "Imperial Navy 100mm Steel Plates": "low",
  "Imperial Navy 1600mm Steel Plates": "low",
  "Imperial Navy 200mm Steel Plates": "low",
  "Imperial Navy 400mm Steel Plates": "low",
  "Imperial Navy 800mm Steel Plates": "low",
  "Imperial Navy Dual Heavy Beam Laser": "high",
  "Imperial Navy Dual Heavy Pulse Laser": "high",
  "Imperial Navy Dual Light Beam Laser": "high",
  "Imperial Navy Dual Light Pulse Laser": "high",
  "Imperial Navy Focused Medium Beam Laser": "high",
  "Imperial Navy Focused Medium Pulse Laser": "high",
  "Imperial Navy Gatling Pulse Laser": "high",
  "Imperial Navy Heavy Beam Laser": "high",
  "Imperial Navy Heavy Pulse Laser": "high",
  "Imperial Navy Mega Beam Laser": "high",
  "Imperial Navy Mega Pulse Laser": "high",
  "Imperial Navy Quad Beam Laser": "high",
  "Imperial Navy Small Focused Beam Laser": "high",
  "Imperial Navy Small Focused Pulse Laser": "high",
  "Imperial Navy Tachyon Beam Laser": "high",
  "Inertial Stabilizers I": "low",
  "Inertial Stabilizers II": "low",
  "Ion Blaster Cannon I": "high",
  "Ion Blaster Cannon II": "high",
  "Ion Siege Blaster I": "high",
  "Ion Siege Blaster II": "high",
  "Kaikka's Modified 350mm Railgun": "high",
  "Kaikka's Modified 425mm Railgun": "high",
  "Kaikka's Modified Dual 250mm Railgun": "high",
  "Khanid Navy Stasis Webifier": "mid",
  "Large 'Sheriff' Shield Extender": "mid",
  "Large Auxiliary Thrusters I": "rig",
  "Large Auxiliary Thrusters II": "rig",
  "Large Azeotropic Restrained Shield Extender": "mid",
  "Large Core Defense Capacitor Safeguard I": "rig",
  "Large Core Defense Capacitor Safeguard II": "rig",
  "Large Core Defense Charge Economizer I": "rig",
  "Large Core Defense Charge Economizer II": "rig",
  "Large Core Defense Field Extender I": "rig",
  "Large Core Defense Field Extender II": "rig",
  "Large Core Defense Field Purger I": "rig",
  "Large Core Defense Field Purger II": "rig",
  "Large Core Defense Operational Solidifier I": "rig",
  "Large Core Defense Operational Solidifier II": "rig",
  "Large EM Armor Reinforcer I": "rig",
  "Large EM Armor Reinforcer II": "rig",
  "Large EM Shield Reinforcer I": "rig",
  "Large EM Shield Reinforcer II": "rig",
  "Large Energy Ambit Extension I": "rig",
  "Large Energy Ambit Extension II": "rig",
  "Large Energy Locus Coordinator I": "rig",
  "Large Energy Locus Coordinator II": "rig",
  "Large Energy Metastasis Adjuster I": "rig",
  "Large Energy Metastasis Adjuster II": "rig",
  "Large Explosive Armor Reinforcer I": "rig",
  "Large Explosive Armor Reinforcer II": "rig",
  "Large Explosive Shield Reinforcer I": "rig",
  "Large Explosive Shield Reinforcer II": "rig",
  "Large F-S9 Regolith Compact Shield Extender": "mid",
  "Large Higgs Anchor I": "rig",
  "Large Hybrid Ambit Extension I": "rig",
  "Large Hybrid Ambit Extension II": "rig",
  "Large Hybrid Locus Coordinator I": "rig",
  "Large Hybrid Locus Coordinator II": "rig",
  "Large Hybrid Metastasis Adjuster I": "rig",
  "Large Hybrid Metastasis Adjuster II": "rig",
  "Large Hyperspatial Velocity Optimizer I": "rig",
  "Large Hyperspatial Velocity Optimizer II": "rig",
  "Large Kinetic Armor Reinforcer I": "rig",
  "Large Kinetic Armor Reinforcer II": "rig",
  "Large Kinetic Shield Reinforcer I": "rig",
  "Large Kinetic Shield Reinforcer II": "rig",
  "Large Low Friction Nozzle Joints I": "rig",
  "Large Low Friction Nozzle Joints II": "rig",
  "Large Polycarbon Engine Housing I": "rig",
  "Large Polycarbon Engine Housing II": "rig",
  "Large Projectile Ambit Extension I": "rig",
  "Large Projectile Ambit Extension II": "rig",
  "Large Projectile Locus Coordinator I": "rig",
  "Large Projectile Locus Coordinator II": "rig",
  "Large Projectile Metastasis Adjuster I": "rig",
  "Large Projectile Metastasis Adjuster II": "rig",
  "Large Remote Repair Augmentor I": "rig",
  "Large Remote Repair Augmentor II": "rig",
  "Large Shield Extender I": "mid",
  "Large Shield Extender II": "mid",
  "Large Thermal Armor Reinforcer I": "rig",
  "Large Thermal Armor Reinforcer II": "rig",
  "Large Thermal Shield Reinforcer I": "rig",
  "Large Thermal Shield Reinforcer II": "rig",
  "Large Trimark Armor Pump I": "rig",
  "Large Trimark Armor Pump II": "rig",
  "Large Warp Core Optimizer I": "rig",
  "Large Warp Core Optimizer II": "rig",
  "Light Electron Blaster I": "high",
  "Light Electron Blaster II": "high",
  "Light Ion Blaster I": "high",
  "Light Ion Blaster II": "high",
  "Light Neutron Blaster I": "high",
  "Light Neutron Blaster II": "high",
  "Limited Electron Blaster Cannon I": "high",
  "Limited Electron Blaster I": "high",
  "Limited Ion Blaster I": "high",
  "Limited Light Electron Blaster I": "high",
  "Limited Light Ion Blaster I": "high",
  "Limited Light Neutron Blaster I": "high",
  "Limited Mega Ion Blaster I": "high",
  "Limited Mega Neutron Blaster I": "high",
  "Limited Neutron Blaster I": "high",
  "Limited Precise Ion Siege Blaster": "high",
  "Limited Precise Triple Neutron Blaster Cannon": "high",
  "Lorharyth’s Modified Inertial Stabilizer": "low",
  "Makra's Modified Small Focused Pulse Laser": "high",
  "Mark I Compact Reinforced Bulkheads": "low",
  "Medium 'Canyon' Shield Extender": "mid",
  "Medium Auxiliary Thrusters I": "rig",
  "Medium Auxiliary Thrusters II": "rig",
  "Medium Azeotropic Restrained Shield Extender": "mid",
  "Medium Core Defense Capacitor Safeguard I": "rig",
  "Medium Core Defense Capacitor Safeguard II": "rig",
  "Medium Core Defense Charge Economizer I": "rig",
  "Medium Core Defense Charge Economizer II": "rig",
  "Medium Core Defense Field Extender I": "rig",
  "Medium Core Defense Field Extender II": "rig",
  "Medium Core Defense Field Purger I": "rig",
  "Medium Core Defense Field Purger II": "rig",
  "Medium Core Defense Operational Solidifier I": "rig",
  "Medium Core Defense Operational Solidifier II": "rig",
  "Medium EM Armor Reinforcer I": "rig",
  "Medium EM Armor Reinforcer II": "rig",
  "Medium EM Shield Reinforcer I": "rig",
  "Medium EM Shield Reinforcer II": "rig",
  "Medium Energy Ambit Extension I": "rig",
  "Medium Energy Ambit Extension II": "rig",
  "Medium Energy Locus Coordinator I": "rig",
  "Medium Energy Locus Coordinator II": "rig",
  "Medium Energy Metastasis Adjuster I": "rig",
  "Medium Energy Metastasis Adjuster II": "rig",
  "Medium Explosive Armor Reinforcer I": "rig",
  "Medium Explosive Armor Reinforcer II": "rig",
  "Medium Explosive Shield Reinforcer I": "rig",
  "Medium Explosive Shield Reinforcer II": "rig",
  "Medium F-S9 Regolith Compact Shield Extender": "mid",
  "Medium Higgs Anchor I": "rig",
  "Medium Hybrid Ambit Extension I": "rig",
  "Medium Hybrid Ambit Extension II": "rig",
  "Medium Hybrid Locus Coordinator I": "rig",
  "Medium Hybrid Locus Coordinator II": "rig",
  "Medium Hybrid Metastasis Adjuster I": "rig",
  "Medium Hybrid Metastasis Adjuster II": "rig",
  "Medium Hyperspatial Velocity Optimizer I": "rig",
  "Medium Hyperspatial Velocity Optimizer II": "rig",
  "Medium Kinetic Armor Reinforcer I": "rig",
  "Medium Kinetic Armor Reinforcer II": "rig",
  "Medium Kinetic Shield Reinforcer I": "rig",
  "Medium Kinetic Shield Reinforcer II": "rig",
  "Medium Low Friction Nozzle Joints I": "rig",
  "Medium Low Friction Nozzle Joints II": "rig",
  "Medium Polycarbon Engine Housing I": "rig",
  "Medium Polycarbon Engine Housing II": "rig",
  "Medium Projectile Ambit Extension I": "rig",
  "Medium Projectile Ambit Extension II": "rig",
  "Medium Projectile Locus Coordinator I": "rig",
  "Medium Projectile Locus Coordinator II": "rig",
  "Medium Projectile Metastasis Adjuster I": "rig",
  "Medium Projectile Metastasis Adjuster II": "rig",
  "Medium Remote Repair Augmentor I": "rig",
  "Medium Remote Repair Augmentor II": "rig",
  "Medium Shield Extender I": "mid",
  "Medium Shield Extender II": "mid",
  "Medium Thermal Armor Reinforcer I": "rig",
  "Medium Thermal Armor Reinforcer II": "rig",
  "Medium Thermal Shield Reinforcer I": "rig",
  "Medium Thermal Shield Reinforcer II": "rig",
  "Medium Trimark Armor Pump I": "rig",
  "Medium Trimark Armor Pump II": "rig",
  "Medium Warp Core Optimizer I": "rig",
  "Medium Warp Core Optimizer II": "rig",
  "Mega Afocal Laser I": "high",
  "Mega Afocal Pulse Laser I": "high",
  "Mega Anode Particle Stream I": "high",
  "Mega Anode Pulse Particle Stream I": "high",
  "Mega Beam Laser I": "high",
  "Mega Beam Laser II": "high",
  "Mega Modal Laser I": "high",
  "Mega Modal Pulse Laser I": "high",
  "Mega Modulated Energy Beam I": "high",
  "Mega Modulated Pulse Energy Beam I": "high",
  "Mega Pulse Laser I": "high",
  "Mega Pulse Laser II": "high",
  "Mizuro's Modified 100MN Afterburner": "mid",
  "Mizuro's Modified 500MN Microwarpdrive": "mid",
  "Mizuro's Modified 800mm Repeating Cannon": "high",
  "Mizuro's Modified Dual 425mm AutoCannon": "high",
  "Mizuro's Modified Dual 650mm Repeating Cannon": "high",
  "Mizuro's Modified Stasis Webifier": "mid",
  "Mizuro's Modified Tracking Enhancer": "low",
  "Modal Electron Particle Accelerator I": "high",
  "Modal Enduring Dual Giga Beam Laser": "high",
  "Modal Enduring Dual Giga Pulse Laser": "high",
  "Modal Enduring Ion Siege Blaster": "high",
  "Modal Enduring Quad Mega Pulse Laser": "high",
  "Modal Enduring Triple Neutron Blaster Cannon": "high",
  "Modal Ion Particle Accelerator I": "high",
  "Modal Light Electron Particle Accelerator I": "high",
  "Modal Light Ion Particle Accelerator I": "high",
  "Modal Light Neutron Particle Accelerator I": "high",
  "Modal Mega Electron Particle Accelerator I": "high",
  "Modal Mega Ion Particle Accelerator I": "high",
  "Modal Mega Neutron Particle Accelerator I": "high",
  "Modal Neutron Particle Accelerator I": "high",
  "Modulated Compact Dual Giga Beam Laser": "high",
  "Modulated Compact Dual Giga Pulse Laser": "high",
  "Modulated Compact Quad Mega Pulse Laser": "high",
  "Nanofiber Internal Structure I": "low",
  "Nanofiber Internal Structure II": "low",
  "Neutron Blaster Cannon I": "high",
  "Neutron Blaster Cannon II": "high",
  "Nija's Modified 10MN Afterburner": "mid",
  "Nija's Modified Heavy Pulse Laser": "high",
  "ORE Reinforced Bulkheads": "low",
  "Optical Compact Tracking Computer": "mid",
  "Overdrive Injector System I": "low",
  "Overdrive Injector System II": "low",
  "Polarized 200mm AutoCannon": "high",
  "Polarized 425mm AutoCannon": "high",
  "Polarized 800mm Repeating Cannon": "high",
  "Polarized Heavy Neutron Blaster": "high",
  "Polarized Heavy Pulse Laser": "high",
  "Polarized Light Neutron Blaster": "high",
  "Polarized Mega Pulse Laser": "high",
  "Polarized Neutron Blaster Cannon": "high",
  "Polarized Small Focused Pulse Laser": "high",
  "Prototype Precise Dual 1000mm Railgun": "high",
  "Prototype Precise Hexa 2500mm Repeating Cannon": "high",
  "Prototype Precise Quad 3500mm Siege Artillery": "high",
  "Prototype Precise Quad 800mm Repeating Cannon": "high",
  "Quad 3500mm Siege Artillery I": "high",
  "Quad 3500mm Siege Artillery II": "high",
  "Quad 800mm Repeating Cannon I": "high",
  "Quad 800mm Repeating Cannon II": "high",
  "Quad Afocal Light Laser I": "high",
  "Quad Anode Light Particle Stream I": "high",
  "Quad Light Beam Laser I": "high",
  "Quad Light Beam Laser II": "high",
  "Quad Mega Pulse Laser I": "high",
  "Quad Mega Pulse Laser II": "high",
  "Quad Modal Light Laser I": "high",
  "Quad Modulated Light Energy Beam I": "high",
  "Ramaku's Modified 1MN Afterburner": "mid",
  "Ramaku's Modified 200mm AutoCannon": "high",
  "Ramaku's Modified 5MN Microwarpdrive": "mid",
  "Raysere's Modified Dual Heavy Beam Laser": "high",
  "Raysere's Modified Mega Beam Laser": "high",
  "Raysere's Modified Tachyon Beam Laser": "high",
  "Regulated Compact Ion Siege Blaster": "high",
  "Regulated Compact Triple Neutron Blaster Cannon": "high",
  "Regulated Electron Phase Cannon I": "high",
  "Regulated Ion Phase Cannon I": "high",
  "Regulated Light Electron Phase Cannon I": "high",
  "Regulated Light Ion Phase Cannon I": "high",
  "Regulated Light Neutron Phase Cannon I": "high",
  "Regulated Mega Electron Phase Cannon I": "high",
  "Regulated Mega Ion Phase Cannon I": "high",
  "Regulated Mega Neutron Phase Cannon I": "high",
  "Regulated Neutron Phase Cannon I": "high",
  "Reinforced Bulkheads I": "low",
  "Reinforced Bulkheads II": "low",
  "Republic Fleet 100MN Afterburner": "mid",
  "Republic Fleet 10MN Afterburner": "mid",
  "Republic Fleet 1200mm Artillery": "high",
  "Republic Fleet 125mm Autocannon": "high",
  "Republic Fleet 1400mm Howitzer Artillery": "high",
  "Republic Fleet 150mm Autocannon": "high",
  "Republic Fleet 1MN Afterburner": "mid",
  "Republic Fleet 200mm Autocannon": "high",
  "Republic Fleet 220mm Autocannon": "high",
  "Republic Fleet 250mm Artillery": "high",
  "Republic Fleet 280mm Howitzer Artillery": "high",
  "Republic Fleet 425mm Autocannon": "high",
  "Republic Fleet 500MN Microwarpdrive": "mid",
  "Republic Fleet 50MN Microwarpdrive": "mid",
  "Republic Fleet 5MN Microwarpdrive": "mid",
  "Republic Fleet 650mm Artillery": "high",
  "Republic Fleet 720mm Howitzer Artillery": "high",
  "Republic Fleet 800mm Repeating Cannon": "high",
  "Republic Fleet Dual 180mm Autocannon": "high",
  "Republic Fleet Dual 425mm Autocannon": "high",
  "Republic Fleet Dual 650mm Repeating Cannon": "high",
  "Republic Fleet Large Shield Extender": "mid",
  "Republic Fleet Medium Shield Extender": "mid",
  "Republic Fleet Nanofiber Structure": "low",
  "Republic Fleet Overdrive Injector": "low",
  "Republic Fleet Small Shield Extender": "mid",
  "Republic Fleet Stasis Webifier": "mid",
  "Republic Fleet Tracking Enhancer": "low",
  "Roden’s Modified Nanofiber Internal Structure": "low",
  "Ryhad's Modified Heavy Pulse Laser": "high",
  "Scout Scoped Dual 1000mm Railgun": "high",
  "Scout Scoped Hexa 2500mm Repeating Cannon": "high",
  "Scout Scoped Quad 3500mm Siege Artillery": "high",
  "Scout Scoped Quad 800mm Repeating Cannon": "high",
  "Selynne's Modified Dual Heavy Beam Laser": "high",
  "Selynne's Modified Mega Beam Laser": "high",
  "Selynne's Modified Tachyon Beam Laser": "high",
  "Setele's Modified 100MN Afterburner": "mid",
  "Setele's Modified 350mm Railgun": "high",
  "Setele's Modified 425mm Railgun": "high",
  "Setele's Modified 500MN Microwarpdrive": "mid",
  "Setele's Modified Dual 250mm Railgun": "high",
  "Setele's Modified Tracking Computer": "mid",
  "Shadow Serpentis 10000MN Afterburner": "mid",
  "Shadow Serpentis 100MN Afterburner": "mid",
  "Shadow Serpentis 10MN Afterburner": "mid",
  "Shadow Serpentis 125mm Railgun": "high",
  "Shadow Serpentis 150mm Railgun": "high",
  "Shadow Serpentis 1MN Afterburner": "mid",
  "Shadow Serpentis 200mm Railgun": "high",
  "Shadow Serpentis 25000mm Steel Plates": "low",
  "Shadow Serpentis 250mm Railgun": "high",
  "Shadow Serpentis 350mm Railgun": "high",
  "Shadow Serpentis 425mm Railgun": "high",
  "Shadow Serpentis 50000MN Microwarpdrive": "mid",
  "Shadow Serpentis 500MN Microwarpdrive": "mid",
  "Shadow Serpentis 50MN Microwarpdrive": "mid",
  "Shadow Serpentis 5MN Microwarpdrive": "mid",
  "Shadow Serpentis 75mm Railgun": "high",
  "Shadow Serpentis Dual 1000mm Railgun": "high",
  "Shadow Serpentis Dual 150mm Railgun": "high",
  "Shadow Serpentis Dual 250mm Railgun": "high",
  "Shadow Serpentis Electron Blaster Cannon": "high",
  "Shadow Serpentis Heavy Electron Blaster": "high",
  "Shadow Serpentis Heavy Ion Blaster": "high",
  "Shadow Serpentis Heavy Neutron Blaster": "high",
  "Shadow Serpentis Inertial Stabilizers": "low",
  "Shadow Serpentis Ion Blaster Cannon": "high",
  "Shadow Serpentis Ion Siege Blaster": "high",
  "Shadow Serpentis Light Electron Blaster": "high",
  "Shadow Serpentis Light Ion Blaster": "high",
  "Shadow Serpentis Light Neutron Blaster": "high",
  "Shadow Serpentis Neutron Blaster Cannon": "high",
  "Shadow Serpentis Stasis Webifier": "mid",
  "Shadow Serpentis Tracking Computer": "mid",
  "Shadow Serpentis Triple Neutron Blaster Cannon": "high",
  "Sila's Modified 10MN Afterburner": "mid",
  "Sila's Modified 425mm Autocannon": "high",
  "Sila's Modified 50MN Microwarpdrive": "mid",
  "Small 'Wolf' Shield Extender": "mid",
  "Small Auxiliary Thrusters I": "rig",
  "Small Auxiliary Thrusters II": "rig",
  "Small Core Defense Capacitor Safeguard I": "rig",
  "Small Core Defense Capacitor Safeguard II": "rig",
  "Small Core Defense Charge Economizer I": "rig",
  "Small Core Defense Charge Economizer II": "rig",
  "Small Core Defense Field Extender I": "rig",
  "Small Core Defense Field Extender II": "rig",
  "Small Core Defense Field Purger I": "rig",
  "Small Core Defense Field Purger II": "rig",
  "Small Core Defense Operational Solidifier I": "rig",
  "Small Core Defense Operational Solidifier II": "rig",
  "Small EM Armor Reinforcer I": "rig",
  "Small EM Armor Reinforcer II": "rig",
  "Small EM Shield Reinforcer I": "rig",
  "Small EM Shield Reinforcer II": "rig",
  "Small Energy Ambit Extension I": "rig",
  "Small Energy Ambit Extension II": "rig",
  "Small Energy Locus Coordinator I": "rig",
  "Small Energy Locus Coordinator II": "rig",
  "Small Energy Metastasis Adjuster I": "rig",
  "Small Energy Metastasis Adjuster II": "rig",
  "Small Explosive Armor Reinforcer I": "rig",
  "Small Explosive Armor Reinforcer II": "rig",
  "Small Explosive Shield Reinforcer I": "rig",
  "Small Explosive Shield Reinforcer II": "rig",
  "Small F-S9 Regolith Compact Shield Extender": "mid",
  "Small Focused Afocal Laser I": "high",
  "Small Focused Afocal Pulse Laser I": "high",
  "Small Focused Anode Particle Stream I": "high",
  "Small Focused Anode Pulse Particle Stream I": "high",
  "Small Focused Beam Laser I": "high",
  "Small Focused Beam Laser II": "high",
  "Small Focused Modal Laser I": "high",
  "Small Focused Modal Pulse Laser I": "high",
  "Small Focused Modulated Energy Beam I": "high",
  "Small Focused Modulated Pulse Energy Beam I": "high",
  "Small Focused Pulse Laser I": "high",
  "Small Focused Pulse Laser II": "high",
  "Small Higgs Anchor I": "rig",
  "Small Hybrid Ambit Extension I": "rig",
  "Small Hybrid Ambit Extension II": "rig",
  "Small Hybrid Locus Coordinator I": "rig",
  "Small Hybrid Locus Coordinator II": "rig",
  "Small Hybrid Metastasis Adjuster I": "rig",
  "Small Hybrid Metastasis Adjuster II": "rig",
  "Small Hyperspatial Velocity Optimizer I": "rig",
  "Small Hyperspatial Velocity Optimizer II": "rig",
  "Small Kinetic Armor Reinforcer I": "rig",
  "Small Kinetic Armor Reinforcer II": "rig",
  "Small Kinetic Shield Reinforcer I": "rig",
  "Small Kinetic Shield Reinforcer II": "rig",
  "Small Low Friction Nozzle Joints I": "rig",
  "Small Low Friction Nozzle Joints II": "rig",
  "Small Polycarbon Engine Housing I": "rig",
  "Small Polycarbon Engine Housing II": "rig",
  "Small Projectile Ambit Extension I": "rig",
  "Small Projectile Ambit Extension II": "rig",
  "Small Projectile Locus Coordinator I": "rig",
  "Small Projectile Locus Coordinator II": "rig",
  "Small Projectile Metastasis Adjuster I": "rig",
  "Small Projectile Metastasis Adjuster II": "rig",
  "Small Remote Repair Augmentor I": "rig",
  "Small Remote Repair Augmentor II": "rig",
  "Small Shield Extender I": "mid",
  "Small Shield Extender II": "mid",
  "Small Thermal Armor Reinforcer I": "rig",
  "Small Thermal Armor Reinforcer II": "rig",
  "Small Thermal Shield Reinforcer I": "rig",
  "Small Thermal Shield Reinforcer II": "rig",
  "Small Trimark Armor Pump I": "rig",
  "Small Trimark Armor Pump II": "rig",
  "Small Warp Core Optimizer I": "rig",
  "Small Warp Core Optimizer II": "rig",
  "Stasis Webifier I": "mid",
  "Stasis Webifier II": "mid",
  "Syndicate 100mm Steel Plates": "low",
  "Syndicate 1600mm Steel Plates": "low",
  "Syndicate 200mm Steel Plates": "low",
  "Syndicate 400mm Steel Plates": "low",
  "Syndicate 800mm Steel Plates": "low",
  "Syndicate Reinforced Bulkheads": "low",
  "Synthetic Hull Conversion Inertial Stabilizers": "low",
  "Synthetic Hull Conversion Nanofiber Structure": "low",
  "Synthetic Hull Conversion Overdrive Injector": "low",
  "Synthetic Hull Conversion Reinforced Bulkheads": "low",
  "Tachyon Afocal Laser I": "high",
  "Tachyon Anode Particle Stream I": "high",
  "Tachyon Beam Laser I": "high",
  "Tachyon Beam Laser II": "high",
  "Tachyon Modal Laser I": "high",
  "Tachyon Modulated Energy Beam I": "high",
  "Tairei's Modified Dual Heavy Pulse Laser": "high",
  "Tairei's Modified Mega Pulse Laser": "high",
  "Thukker Large Shield Extender": "mid",
  "Thukker Medium Shield Extender": "mid",
  "Tobias' Modified 100MN Afterburner": "mid",
  "Tobias' Modified 1200mm Artillery Cannon": "high",
  "Tobias' Modified 1400mm Howitzer Artillery": "high",
  "Tobias' Modified 500MN Microwarpdrive": "mid",
  "Tobias' Modified Stasis Webifier": "mid",
  "Tobias' Modified Tracking Enhancer": "low",
  "Tracking Computer I": "mid",
  "Tracking Computer II": "mid",
  "Tracking Disruptor I": "mid",
  "Tracking Disruptor II": "mid",
  "Tracking Enhancer I": "low",
  "Tracking Enhancer II": "low",
  "Triple Neutron Blaster Cannon I": "high",
  "Triple Neutron Blaster Cannon II": "high",
  "True Sansha 10MN Afterburner": "mid",
  "True Sansha 1MN Afterburner": "mid",
  "True Sansha Capital Shield Extender": "mid",
  "True Sansha Dual Giga Beam Laser": "high",
  "True Sansha Dual Giga Pulse Laser": "high",
  "True Sansha Dual Heavy Beam Laser": "high",
  "True Sansha Dual Heavy Pulse Laser": "high",
  "True Sansha Dual Light Beam Laser": "high",
  "True Sansha Dual Light Pulse Laser": "high",
  "True Sansha Focused Medium Beam Laser": "high",
  "True Sansha Focused Medium Pulse Laser": "high",
  "True Sansha Gatling Pulse Laser": "high",
  "True Sansha Heavy Beam Laser": "high",
  "True Sansha Heavy Pulse Laser": "high",
  "True Sansha Mega Beam Laser": "high",
  "True Sansha Mega Pulse Laser": "high",
  "True Sansha Quad Beam Laser": "high",
  "True Sansha Quad Mega Pulse Laser": "high",
  "True Sansha Small Focused Beam Laser": "high",
  "True Sansha Small Focused Pulse Laser": "high",
  "True Sansha Stasis Webifier": "mid",
  "True Sansha Tachyon Beam Laser": "high",
  "Tuvan's Modified 100MN Afterburner": "mid",
  "Tuvan's Modified 500MN Microwarpdrive": "mid",
  "Tuvan's Modified Electron Blaster Cannon": "high",
  "Tuvan's Modified Ion Blaster Cannon": "high",
  "Tuvan's Modified Neutron Blaster Cannon": "high",
  "Tuvan's Modified Tracking Computer": "mid",
  "Type-D Restrained Inertial Stabilizers": "low",
  "Type-D Restrained Nanofiber Structure": "low",
  "Type-D Restrained Overdrive Injector": "low",
  "Type-D Restrained Reinforced Bulkheads": "low",
  "Usaras' Modified 1MN Afterburner": "mid",
  "Usaras' Modified Small Focused Pulse Laser": "high",
  "Vepas' Modified 350mm Railgun": "high",
  "Vepas' Modified 425mm Railgun": "high",
  "Vepas' Modified Dual 250mm Railgun": "high",
  "Vizan's Modified Dual Heavy Pulse Laser": "high",
  "Vizan's Modified Mega Pulse Laser": "high",
  "X5 Enduring Stasis Webifier": "mid",
} as const;
