import type { PropulsionId, PropulsionModule } from "./types";

export const PROPULSION_MODULES: readonly PropulsionModule[] = [
  {
    id: "ab-1mn",
    kind: "afterburner",
    sizeTier: "small",
    label: "1MN Afterburner I",
    thrust: 1.5e6,
    massAddition: 500_000,
    speedBonus: 1.15,
    sigBloom: 0,
    activeMassMultiplier: 1,
  },
  {
    id: "mwd-5mn",
    kind: "microwarpdrive",
    sizeTier: "small",
    label: "5MN Microwarpdrive I",
    thrust: 1.5e6,
    massAddition: 500_000,
    speedBonus: 5,
    sigBloom: 5,
    activeMassMultiplier: 5,
  },
  {
    id: "ab-10mn",
    kind: "afterburner",
    sizeTier: "medium",
    label: "10MN Afterburner I",
    thrust: 15e6,
    massAddition: 5_000_000,
    speedBonus: 1.15,
    sigBloom: 0,
    activeMassMultiplier: 1,
  },
  {
    id: "mwd-50mn",
    kind: "microwarpdrive",
    sizeTier: "medium",
    label: "50MN Microwarpdrive I",
    thrust: 15e6,
    massAddition: 5_000_000,
    speedBonus: 5,
    sigBloom: 5,
    activeMassMultiplier: 5,
  },
  {
    id: "ab-100mn",
    kind: "afterburner",
    sizeTier: "large",
    label: "100MN Afterburner I",
    thrust: 150e6,
    massAddition: 50_000_000,
    speedBonus: 1.15,
    sigBloom: 0,
    activeMassMultiplier: 1,
  },
  {
    id: "mwd-500mn",
    kind: "microwarpdrive",
    sizeTier: "large",
    label: "500MN Microwarpdrive I",
    thrust: 150e6,
    massAddition: 50_000_000,
    speedBonus: 5,
    sigBloom: 5,
    activeMassMultiplier: 5,
  },
  {
    id: "ab-10000mn",
    kind: "afterburner",
    sizeTier: "capital",
    label: "10000MN Afterburner I",
    thrust: 1.5e9,
    massAddition: 500_000_000,
    speedBonus: 1.15,
    sigBloom: 0,
    activeMassMultiplier: 1,
  },
  {
    id: "mwd-50000mn",
    kind: "microwarpdrive",
    sizeTier: "capital",
    label: "50000MN Microwarpdrive I",
    thrust: 1.5e9,
    massAddition: 500_000_000,
    speedBonus: 5,
    sigBloom: 5,
    activeMassMultiplier: 5,
  },
] as const;

export function isPropulsionId(value: unknown): value is PropulsionId {
  return typeof value === "string" && PROPULSION_MODULES.some((module) => module.id === value);
}
