import type { HullTier } from "./types";

export const HULL_TIERS: Record<string, HullTier | null> = {
  "Assault Frigates": "small",
  "Black Ops": "large",
  "Capital Industrial Ships": "large",
  "Carriers": "capital",
  "Command Carriers": "capital",
  "Command Destroyers": "small",
  "Command Ships": "medium",
  "Corvettes": "small",
  "Covert Ops": "small",
  "Dreadnoughts": "capital",
  "EDENCOM Battleships": "large",
  "EDENCOM Cruisers": "medium",
  "EDENCOM Frigates": "small",
  "Electronic Attack Frigates": "small",
  "Exhumers": "medium",
  "Expedition Command Ships": "medium",
  "Expedition Frigates": "small",
  "Faction Battlecruisers": "medium",
  "Faction Battleships": "large",
  "Faction Cruisers": "medium",
  "Faction Destroyers": "small",
  "Faction Dreadnoughts": "capital",
  "Faction Frigates": "small",
  "Faction Heavy Drone": "small",
  "Flag Cruiser": "medium",
  "Force Auxiliaries": "capital",
  "Freighters": "large",
  "Haulers": "medium",
  "Heavy Assault Cruisers": "medium",
  "Heavy Interdiction Cruisers": "medium",
  "Industrial Command Ships": "large",
  "Interceptors": "small",
  "Interdictors": "small",
  "Jump Freighters": "large",
  "Lancer Dreadnoughts": "capital",
  "Logistics Cruisers": "medium",
  "Logistics Frigates": "small",
  "Marauders": "large",
  "Mining Barges": "medium",
  "Pirate Faction Battlecruisers": "medium",
  "Pirate Faction Battleships": "large",
  "Pirate Faction Cruisers": "medium",
  "Pirate Faction Destroyers": "small",
  "Pirate Faction Dreadnoughts": "capital",
  "Pirate Faction Force Auxiliaries": "capital",
  "Pirate Faction Frigates": "small",
  "Pirate Faction Supercarriers": "capital",
  "Pirate Faction Titans": "capital",
  "Precursor Battlecruisers": "medium",
  "Precursor Battleships": "large",
  "Precursor Cruisers": "medium",
  "Precursor Destroyers": "small",
  "Precursor Dreadnoughts": "capital",
  "Precursor Frigates": "small",
  "Recon Ships": "medium",
  "Shuttles": null,
  "Special Edition Assault Frigates": "small",
  "Special Edition Battlecruisers": "medium",
  "Special Edition Battleships": "large",
  "Special Edition Black Ops": "large",
  "Special Edition Corvettes": "small",
  "Special Edition Covert Ops": "small",
  "Special Edition Cruisers": "medium",
  "Special Edition Destroyers": "small",
  "Special Edition Electronic Attack Ships": "small",
  "Special Edition Frigates": "small",
  "Special Edition Heavy Assault Cruisers": "medium",
  "Special Edition Heavy Interdiction Cruisers": "medium",
  "Special Edition Industrial Ships": "medium",
  "Special Edition Interceptors": "small",
  "Special Edition Logistics Cruisers": "medium",
  "Special Edition Recon Ships": "medium",
  "Special Edition Ships": "medium",
  "Special Edition Ships Battleships": "large",
  "Special Edition Shuttles": null,
  "Special Edition Tactical Destroyers": "small",
  "Standard Battlecruisers": "medium",
  "Standard Battleships": "large",
  "Standard Cruisers": "medium",
  "Standard Destroyers": "small",
  "Standard Frigates": "small",
  "Strategic Cruisers": "medium",
  "Supercarriers": "capital",
  "Tactical Destroyers": "small",
  "Titans": "capital",
  "Transport Ships": "medium",
} as const;

function hullTierOf(hullType: string): HullTier | null {
  return HULL_TIERS[hullType] ?? null;
}

export { hullTierOf as _hullTierOf };
