import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { SHIP_PROFILES } from "../src/gamedata/shipProfiles/profiles";
import type { FactionId, HullTypeId, ShipId } from "../src/gamedata/ids";
import type { ShipNameLanguage } from "../src/gamedata/i18n";

export interface I18nProfile {
  readonly id: ShipId;
  readonly name: string;
  readonly faction: string;
  readonly factionId: FactionId;
  readonly hullType: string;
  readonly hullTypeId: HullTypeId;
}

interface I18nPack {
  readonly en: string;
  readonly zh: string;
  readonly ja: string;
}

const SHIP_NAMES_JSON = "data/ship-names-i18n.json";
const FACTION_NAMES_JSON = "data/faction-i18n.json";
const HULL_TYPE_NAMES_JSON = "data/hull-type-i18n.json";
const SHIP_PROFILES_JSON = "data/ship-profiles.json";

const SHIP_NAMES_OUTPUT = "src/gamedata/nameI18n/ship-names-i18n.ts";
const FACTION_NAMES_OUTPUT = "src/gamedata/nameI18n/faction-i18n.ts";
const HULL_TYPE_NAMES_OUTPUT = "src/gamedata/nameI18n/hull-types-i18n.ts";

function fallbackPack(en: string, pack?: Partial<I18nPack>): I18nPack {
  return {
    en,
    zh: pack?.zh?.trim() || en,
    ja: pack?.ja?.trim() || en,
  };
}

async function loadI18nPack(path: string): Promise<Readonly<Record<string, I18nPack>>> {
  const text = await readFile(path, "utf8");
  const parsed: Record<string, I18nPack> = JSON.parse(text);
  return parsed;
}

function requirePack(pack: Readonly<Record<string, I18nPack>>, key: string, en: string): I18nPack {
  const entry = pack[key];
  if (!entry) throw new Error(`Missing i18n entry for "${key}" (${en}).`);
  return fallbackPack(en, entry);
}

export function buildShipNameI18n(
  profiles: readonly I18nProfile[],
  pack: Readonly<Record<string, I18nPack>>,
): Record<ShipId, I18nPack> {
  const result: Record<ShipId, I18nPack> = {};
  for (const profile of profiles) {
    result[profile.id] = requirePack(pack, profile.name, profile.name);
  }
  return result;
}

export function buildFactionNameI18n(
  profiles: readonly I18nProfile[],
  pack: Readonly<Record<string, I18nPack>>,
): Record<FactionId, I18nPack> {
  const result: Record<FactionId, I18nPack> = {};
  const seen = new Set<FactionId>();
  for (const profile of profiles) {
    if (seen.has(profile.factionId)) continue;
    seen.add(profile.factionId);
    result[profile.factionId] = requirePack(pack, profile.faction, profile.faction);
  }
  return result;
}

function selectCanonicalHullType(hullTypes: readonly string[]): string {
  const standards = hullTypes.filter((h) => h.toLowerCase().startsWith("standard "));
  const candidates = standards.length > 0 ? standards : hullTypes;
  return candidates
    .slice()
    .sort((a, b) => a.length - b.length || a.localeCompare(b))[0];
}

export function buildHullTypeNameI18n(
  profiles: readonly I18nProfile[],
  pack: Readonly<Record<string, I18nPack>>,
): Record<HullTypeId, I18nPack> {
  const result: Record<HullTypeId, I18nPack> = {};
  const byId = new Map<HullTypeId, Set<string>>();

  for (const profile of profiles) {
    let set = byId.get(profile.hullTypeId);
    if (!set) {
      set = new Set<string>();
      byId.set(profile.hullTypeId, set);
    }
    set.add(profile.hullType);
  }

  for (const [hullTypeId, hullTypes] of byId.entries()) {
    const selected = selectCanonicalHullType(Array.from(hullTypes));
    result[hullTypeId] = requirePack(pack, selected, selected);
  }

  return result;
}

function buildSource(name: string, data: Record<string, I18nPack>): string {
  const header = `// Generated by scripts/generate-name-i18n.ts; do not edit manually.\n\n`;
  const type = `Readonly<Record<string, Readonly<Record<"en" | "zh" | "ja", string>>>>`;
  const entries = Object.entries(data)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, pack]) => {
      return `  ${JSON.stringify(id)}: {\n    en: ${JSON.stringify(pack.en)},\n    zh: ${JSON.stringify(pack.zh)},\n    ja: ${JSON.stringify(pack.ja)},\n  },`;
    });
  const body = entries.join("\n");
  return `${header}export const ${name}: ${type} = {\n${body}\n} as const;\n`;
}

async function writeIfChanged(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  const existing = await readFile(path, "utf8").catch(() => "");
  if (existing === content) {
    console.log(`${path} is up to date.`);
    return;
  }
  await writeFile(path, content);
  console.log(`Generated ${path}.`);
}

interface RawProfile {
  readonly name: string;
  readonly faction: string;
  readonly hullType: string;
}

async function loadI18nProfiles(): Promise<readonly I18nProfile[]> {
  const text = await readFile(SHIP_PROFILES_JSON, "utf8");
  const raw: RawProfile[] = JSON.parse(text);
  const sourceByName = new Map<string, RawProfile>(raw.map((r) => [r.name, r]));

  const profiles: I18nProfile[] = [];
  for (const profile of SHIP_PROFILES) {
    const source = sourceByName.get(profile.name);
    if (!source) throw new Error(`Missing source profile for "${profile.name}".`);
    profiles.push({
      id: profile.id,
      name: profile.name,
      faction: source.faction,
      factionId: profile.factionId,
      hullType: source.hullType,
      hullTypeId: profile.hullTypeId,
    });
  }
  return profiles;
}

export async function main(): Promise<void> {
  const [shipPack, factionPack, hullTypePack, profiles] = await Promise.all([
    loadI18nPack(SHIP_NAMES_JSON),
    loadI18nPack(FACTION_NAMES_JSON),
    loadI18nPack(HULL_TYPE_NAMES_JSON),
    loadI18nProfiles(),
  ]);

  const shipNames = buildShipNameI18n(profiles, shipPack);
  const factionNames = buildFactionNameI18n(profiles, factionPack);
  const hullTypeNames = buildHullTypeNameI18n(profiles, hullTypePack);

  await Promise.all([
    writeIfChanged(SHIP_NAMES_OUTPUT, buildSource("SHIP_NAMES", shipNames)),
    writeIfChanged(FACTION_NAMES_OUTPUT, buildSource("FACTION_NAMES", factionNames)),
    writeIfChanged(HULL_TYPE_NAMES_OUTPUT, buildSource("HULL_TYPE_NAMES", hullTypeNames)),
  ]);
}

if (import.meta.main) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
