import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { ShipProfile } from "../src/ships";

interface RawProfile {
  readonly name: string;
  readonly faction: string;
  readonly hullType: string;
  readonly navigation: Readonly<Record<string, string>>;
  readonly structure: Readonly<Record<string, string>>;
  readonly targeting: Readonly<Record<string, string>>;
}

const DATA_PATH = "data/ship-profiles.json";
const OUTPUT_PATH = "src/gamedata/shipProfiles/profiles.ts";

function parseNumber(input: string): number {
  const match = input.match(/[\d,.]+(?:\.\d+)?/);
  if (!match) throw new Error(`Cannot parse number from "${input}"`);
  const cleaned = match[0].replaceAll(",", "");
  const value = Number(cleaned);
  if (Number.isNaN(value)) throw new Error(`Cannot parse number from "${input}"`);
  return value;
}

function hasObject(value: unknown, key: string): Record<string, unknown> {
  if (!value || typeof value !== "object") throw new Error(`Entry is not an object`);
  const record = value as Record<string, unknown>;
  const child = record[key];
  if (!child || typeof child !== "object") throw new Error(`Missing ${key}`);
  return child as Record<string, unknown>;
}

function hasString(value: Record<string, unknown>, key: string, context: string): string {
  const field = value[key];
  if (typeof field !== "string") throw new Error(`${context}: missing or invalid ${key}`);
  return field;
}

function parseProfile(raw: unknown, index: number): ShipProfile {
  if (!raw || typeof raw !== "object") throw new Error(`Entry ${index} is not an object`);
  const record = raw as Record<string, unknown>;

  const name = hasString(record, "name", `Entry ${index}`);
  if (name.length === 0) throw new Error(`Entry ${index} has an empty name`);
  const faction = hasString(record, "faction", name);
  const hullType = hasString(record, "hullType", name);

  const navigation = hasObject(raw, "navigation");
  const structure = hasObject(raw, "structure");
  const targeting = hasObject(raw, "targeting");

  return {
    name,
    faction,
    hullType,
    mass: parseNumber(hasString(structure, "mass", name)),
    inertiaModifier: parseNumber(hasString(navigation, "inertiaModifier", name)),
    baseSpeed: parseNumber(hasString(navigation, "maxVelocity", name)),
    sigRadius: parseNumber(hasString(targeting, "sigRadius", name)),
  };
}

function buildSource(profiles: readonly ShipProfile[]): string {
  const lines: string[] = [
    "// Generated by scripts/generate-ship-profiles.ts; do not edit manually.",
    'import type { ShipProfile } from "../../ships";',
    "",
    "export const SHIP_PROFILES: readonly ShipProfile[] = [",
  ];

  for (const p of profiles) {
    lines.push("  {");
    lines.push(`    name: ${JSON.stringify(p.name)},`);
    lines.push(`    faction: ${JSON.stringify(p.faction)},`);
    lines.push(`    hullType: ${JSON.stringify(p.hullType)},`);
    lines.push(`    mass: ${p.mass},`);
    lines.push(`    inertiaModifier: ${p.inertiaModifier},`);
    lines.push(`    baseSpeed: ${p.baseSpeed},`);
    lines.push(`    sigRadius: ${p.sigRadius},`);
    lines.push("  },");
  }

  lines.push("] as const;");
  lines.push("");
  return lines.join("\n");
}

async function main(): Promise<void> {
  const file = Bun.file(DATA_PATH);
  const raw = await file.json();
  if (!Array.isArray(raw)) throw new Error(`${DATA_PATH} does not contain an array`);

  const profiles: ShipProfile[] = [];
  for (let i = 0; i < raw.length; i++) {
    profiles.push(parseProfile(raw[i], i));
  }

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, buildSource(profiles));
  console.log(`Generated ${OUTPUT_PATH} with ${profiles.length} profiles.`);
}

if (import.meta.main) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
