#!/usr/bin/env bun
import { existsSync } from "node:fs";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import * as process from "node:process";
import { MODULE_SLOT_CATALOG } from "../src/gamedata/moduleSlots";
import { moduleLines, parseEft } from "../src/fitting/eft";

const SDE_DIR = process.argv[2] ?? join(homedir(), "workspace", "Pyfa", "staticdata", "fsd_built");
const FITTINGS_DIR = "data/ship-fittings";
const ICONS_DIR = "data/ship-modules/icons";
const OUTPUT_PATH = "src/ui/icons/droneIconIds.ts";

interface SdeGroup {
  readonly categoryID: number;
}

interface SdeType {
  readonly groupID: number;
  readonly "typeName_en-us"?: string;
  readonly name?: { readonly en?: string };
}

async function main(): Promise<void> {
  const groups = JSON.parse(await readFile(join(SDE_DIR, "groups.0.json"), "utf8")) as Record<string, SdeGroup>;
  const droneGroupIds = new Set<string>();
  for (const [gid, group] of Object.entries(groups)) {
    if (group.categoryID === 18) droneGroupIds.add(gid);
  }

  const typeFiles = (await readdir(SDE_DIR))
    .filter((file) => file.startsWith("types.") && file.endsWith(".json"))
    .sort();
  const typeByName: Record<string, number> = {};
  for (const file of typeFiles) {
    const types = JSON.parse(await readFile(join(SDE_DIR, file), "utf8")) as Record<string, SdeType>;
    for (const [tid, type] of Object.entries(types)) {
      if (!droneGroupIds.has(String(type.groupID))) continue;
      const name = type["typeName_en-us"] ?? type.name?.en;
      if (name) typeByName[name] = Number(tid);
    }
  }

  const entries = await readdir(FITTINGS_DIR, { recursive: true, withFileTypes: true });
  const usedDrones = new Set<string>();
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".txt")) continue;
    const text = await readFile(join(entry.parentPath, entry.name), "utf8");
    const parsed = parseEft(text, MODULE_SLOT_CATALOG);
    if (!parsed) continue;
    for (const item of [...parsed.drones, ...parsed.cargo]) {
      if (item.name in typeByName) usedDrones.add(item.name);
    }
  }

  const mapping: Record<string, number> = {};
  const missing: string[] = [];
  for (const name of Array.from(usedDrones).sort()) {
    const typeId = typeByName[name];
    const outPath = join(ICONS_DIR, `${typeId}@1x.png`);
    if (!existsSync(outPath)) {
      const url = `https://images.evetech.net/types/${typeId}/icon`;
      try {
        const resp = await fetch(url);
        if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
        await Bun.write(outPath, await resp.blob());
      } catch (error) {
        missing.push(name);
        continue;
      }
    }
    mapping[name] = typeId;
  }

  if (missing.length > 0) {
    console.warn(`Failed to download icons for ${missing.length} drones: ${missing.join(", ")}`);
  }

  const lines = Object.keys(mapping)
    .sort()
    .map((name) => `  ${JSON.stringify(name)}: ${mapping[name]},`);
  const content =
    "// Generated by scripts/sync-drone-icons.ts from the EVE Online SDE and images.evetech.net. Do not edit by hand.\n\n" +
    `export const DRONE_TYPE_IDS: Readonly<Record<string, number>> = {\n${lines.join("\n")}\n} as const;\n`;
  await writeFile(OUTPUT_PATH, content, "utf8");
  console.log(`Wrote ${OUTPUT_PATH} with ${lines.length} drones.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
