// Generated by scripts/generate-name-i18n.ts; do not edit manually.

export const FACTION_NAMES: Readonly<Record<string, Readonly<Record<"en" | "zh" | "ja", string>>>> = {
  "amarr": {
    en: "Amarr",
    zh: "艾玛",
    ja: "アマー",
  },
  "amarr-empire": {
    en: "Amarr Empire",
    zh: "艾玛帝国",
    ja: "アマー帝国",
  },
  "angel-cartel": {
    en: "Angel Cartel",
    zh: "天使集团",
    ja: "エンジェルカルテル",
  },
  "blood-raiders": {
    en: "Blood Raiders",
    zh: "血袭者",
    ja: "ブラッドレイダー",
  },
  "caldari-state": {
    en: "Caldari State",
    zh: "加达里",
    ja: "カルダリ連合",
  },
  "concord": {
    en: "CONCORD",
    zh: "统合部",
    ja: "コンコード",
  },
  "deathless-circle": {
    en: "Deathless Circle",
    zh: "死亡之神集团",
    ja: "デスリスサークル",
  },
  "edencom": {
    en: "EDENCOM",
    zh: "伊甸联合防御阵线",
    ja: "エデンコム",
  },
  "gallente-federation": {
    en: "Gallente Federation",
    zh: "盖伦特",
    ja: "ガレンテ連邦",
  },
  "guristas": {
    en: "Guristas",
    zh: "古斯塔斯",
    ja: "ガリスタス海賊団",
  },
  "intaki-syndicate": {
    en: "Intaki Syndicate",
    zh: "印塔基联合",
    ja: "インタキ・シンジケート",
  },
  "interbus": {
    en: "InterBus",
    zh: "星际快捷客运联合体",
    ja: "インターバス",
  },
  "jovian-directorate": {
    en: "Jovian Directorate",
    zh: "朱庇特",
    ja: "ジョービ",
  },
  "minmatar-republic": {
    en: "Minmatar Republic",
    zh: "米玛塔尔",
    ja: "ミンマター共和国",
  },
  "mordus-legion": {
    en: "Mordu's Legion",
    zh: "莫德团",
    ja: "モーダス部隊",
  },
  "outer-ring-excavations": {
    en: "Outer Ring Excavations",
    zh: "外空联合矿业集团",
    ja: "アウターリング発掘調査",
  },
  "sanshas-nation": {
    en: "Sansha's Nation",
    zh: "萨沙共和国",
    ja: "サンシャ国",
  },
  "serpentis": {
    en: "Serpentis",
    zh: "天蛇",
    ja: "サーペンティス",
  },
  "sisters-of-eve": {
    en: "Sisters of EVE",
    zh: "EVE姐妹共济会",
    ja: "サーブラントシスターズ・オブ・イーブ",
  },
  "society-of-conscious-thought": {
    en: "Society of Conscious Thought",
    zh: "真理会",
    ja: "真理会",
  },
  "triglavian-collective": {
    en: "Triglavian Collective",
    zh: "特里格拉维安联合体",
    ja: "トリグラヴィアン集合体",
  },
  "upwell": {
    en: "Upwell",
    zh: "昇威",
    ja: "アップウェル",
  },
} as const;
