// Generated by scripts/generate-name-i18n.ts; do not edit manually.

export const HULL_TYPE_NAMES: Readonly<Record<string, Readonly<Record<"en" | "zh" | "ja", string>>>> = {
  "1022": {
    en: "Special Edition Frigates",
    zh: "护卫舰",
    ja: "フリゲート",
  },
  "1201": {
    en: "Standard Battlecruisers",
    zh: "战斗战列巡洋舰",
    ja: "戦闘巡洋戦艦",
  },
  "1202": {
    en: "Transport Ships",
    zh: "深层空间运输舰",
    ja: "深宇宙用特化型輸送艦",
  },
  "1283": {
    en: "Expedition Frigates",
    zh: "勘探护卫舰",
    ja: "長距離フリゲート",
  },
  "1305": {
    en: "Tactical Destroyers",
    zh: "战术驱逐舰",
    ja: "戦術駆逐艦",
  },
  "1527": {
    en: "Logistics Frigates",
    zh: "后勤护卫舰",
    ja: "支援型フリゲート",
  },
  "1534": {
    en: "Command Destroyers",
    zh: "指挥驱逐舰",
    ja: "指揮型駆逐艦",
  },
  "1538": {
    en: "Force Auxiliaries",
    zh: "战力辅助舰",
    ja: "軍事力補強",
  },
  "1972": {
    en: "Flag Cruiser",
    zh: "战地巡洋舰",
    ja: "指揮巡洋艦",
  },
  "237": {
    en: "Corvettes",
    zh: "轻型护卫舰",
    ja: "コルベット艦",
  },
  "25": {
    en: "Standard Frigates",
    zh: "护卫舰",
    ja: "フリゲート",
  },
  "26": {
    en: "Standard Cruisers",
    zh: "巡洋舰",
    ja: "巡洋艦",
  },
  "27": {
    en: "Standard Battleships",
    zh: "战列舰",
    ja: "戦艦",
  },
  "28": {
    en: "Haulers",
    zh: "运载舰",
    ja: "ハウラー",
  },
  "30": {
    en: "Titans",
    zh: "泰坦",
    ja: "タイタン",
  },
  "31": {
    en: "Shuttles",
    zh: "穿梭机",
    ja: "シャトル",
  },
  "324": {
    en: "Assault Frigates",
    zh: "突击护卫舰",
    ja: "強襲型フリゲート",
  },
  "358": {
    en: "Heavy Assault Cruisers",
    zh: "重型突击巡洋舰",
    ja: "強襲型巡洋艦",
  },
  "380": {
    en: "Transport Ships",
    zh: "深层空间运输舰",
    ja: "深宇宙用特化型輸送艦",
  },
  "419": {
    en: "Standard Battlecruisers",
    zh: "战斗战列巡洋舰",
    ja: "戦闘巡洋戦艦",
  },
  "420": {
    en: "Standard Destroyers",
    zh: "驱逐舰",
    ja: "駆逐艦",
  },
  "4594": {
    en: "Lancer Dreadnoughts",
    zh: "枪骑兵级无畏舰",
    ja: "ランサー攻城艦",
  },
  "463": {
    en: "Mining Barges",
    zh: "采矿驳船",
    ja: "採掘艦",
  },
  "485": {
    en: "Dreadnoughts",
    zh: "无畏舰",
    ja: "攻城艦",
  },
  "4902": {
    en: "Expedition Command Ships",
    zh: "远征指挥舰",
    ja: "指揮型探査船",
  },
  "5087": {
    en: "Special Edition Cruisers",
    zh: "特别版游艇",
    ja: "特別版ヨット",
  },
  "5120": {
    en: "Command Carriers",
    zh: "指挥航母",
    ja: "指揮型艦載機母艦",
  },
  "513": {
    en: "Freighters",
    zh: "货舰",
    ja: "超大型輸送艦",
  },
  "540": {
    en: "Command Ships",
    zh: "指挥舰",
    ja: "指揮型巡洋戦艦",
  },
  "541": {
    en: "Interdictors",
    zh: "拦截舰",
    ja: "ワープ妨害型駆逐艦",
  },
  "543": {
    en: "Exhumers",
    zh: "采掘者",
    ja: "特化型採掘艦",
  },
  "547": {
    en: "Carriers",
    zh: "航空母舰",
    ja: "艦載機母艦",
  },
  "659": {
    en: "Supercarriers",
    zh: "超级航母",
    ja: "大型艦載機母艦",
  },
  "830": {
    en: "Covert Ops",
    zh: "隐形特勤舰",
    ja: "隠密行動艦",
  },
  "831": {
    en: "Interceptors",
    zh: "截击舰",
    ja: "要撃型フリゲート",
  },
  "832": {
    en: "Logistics Cruisers",
    zh: "后勤舰",
    ja: "支援型巡洋艦",
  },
  "833": {
    en: "Recon Ships",
    zh: "力场侦察舰",
    ja: "軍事偵察船",
  },
  "834": {
    en: "Covert Ops",
    zh: "隐形特勤舰",
    ja: "隠密行動艦",
  },
  "883": {
    en: "Capital Industrial Ships",
    zh: "旗舰级工业舰",
    ja: "採掘支援母艦",
  },
  "893": {
    en: "Electronic Attack Frigates",
    zh: "电子攻击舰",
    ja: "電子攻撃船",
  },
  "894": {
    en: "Heavy Interdiction Cruisers",
    zh: "重型拦截巡洋舰",
    ja: "ワープ妨害型巡洋艦",
  },
  "898": {
    en: "Black Ops",
    zh: "黑隐特勤舰",
    ja: "秘密工作艦",
  },
  "900": {
    en: "Marauders",
    zh: "掠夺舰",
    ja: "襲撃型戦艦",
  },
  "902": {
    en: "Jump Freighters",
    zh: "战略货舰",
    ja: "ジャンプドライブ搭載型輸送艦",
  },
  "906": {
    en: "Recon Ships",
    zh: "力场侦察舰",
    ja: "軍事偵察船",
  },
  "941": {
    en: "Industrial Command Ships",
    zh: "工业指挥舰",
    ja: "指揮型輸送艦",
  },
  "963": {
    en: "Strategic Cruisers",
    zh: "战略巡洋舰",
    ja: "戦略的巡洋艦",
  },
  "legacy-electronic-attack-frigates": {
    en: "Electronic Attack Frigates",
    zh: "电子攻击舰",
    ja: "電子攻撃船",
  },
  "legacy-faction-heavy-drone": {
    en: "Faction Heavy Drone",
    zh: "战斗无人机",
    ja: "戦闘用ドローン",
  },
  "legacy-haulers": {
    en: "Haulers",
    zh: "运载舰",
    ja: "ハウラー",
  },
  "legacy-pirate-faction-cruisers": {
    en: "Pirate Faction Cruisers",
    zh: "巡洋舰",
    ja: "巡洋艦",
  },
  "legacy-recon-ships": {
    en: "Recon Ships",
    zh: "力场侦察舰",
    ja: "軍事偵察船",
  },
  "legacy-standard-battleships": {
    en: "Standard Battleships",
    zh: "战列舰",
    ja: "戦艦",
  },
  "legacy-standard-cruisers": {
    en: "Standard Cruisers",
    zh: "巡洋舰",
    ja: "巡洋艦",
  },
  "legacy-standard-frigates": {
    en: "Standard Frigates",
    zh: "护卫舰",
    ja: "フリゲート",
  },
} as const;
