// Generated by scripts/generate-name-i18n.ts; do not edit manually.

export const SHIP_NAMES: Readonly<Record<string, Readonly<Record<"en" | "zh" | "ja", string>>>> = {
  "11011": {
    en: "Guardian-Vexor",
    zh: "狂怒守卫者级",
    ja: "ガーディアンベクサー",
  },
  "11129": {
    en: "Gallente Shuttle",
    zh: "盖伦特穿梭机",
    ja: "ガレンテシャトル",
  },
  "11132": {
    en: "Minmatar Shuttle",
    zh: "米玛塔尔穿梭机",
    ja: "ミンマターシャトル",
  },
  "11134": {
    en: "Amarr Shuttle",
    zh: "艾玛穿梭机",
    ja: "アマーシャトル",
  },
  "11172": {
    en: "Helios",
    zh: "太阳神级",
    ja: "ヘリオス",
  },
  "11174": {
    en: "Keres",
    zh: "克勒斯级",
    ja: "ケレス",
  },
  "11176": {
    en: "Crow",
    zh: "黑鸦级",
    ja: "クロウ",
  },
  "11178": {
    en: "Raptor",
    zh: "猛禽级",
    ja: "ラプター",
  },
  "11182": {
    en: "Cheetah",
    zh: "猎豹级",
    ja: "チーター",
  },
  "11184": {
    en: "Crusader",
    zh: "十字军级",
    ja: "クルセイダー",
  },
  "11186": {
    en: "Malediction",
    zh: "咒灭级",
    ja: "メルディクション",
  },
  "11188": {
    en: "Anathema",
    zh: "咒逐级",
    ja: "アナシマ",
  },
  "11190": {
    en: "Sentinel",
    zh: "哨兵级",
    ja: "センチネル",
  },
  "11192": {
    en: "Buzzard",
    zh: "秃鹰级",
    ja: "バザード",
  },
  "11194": {
    en: "Kitsune",
    zh: "狐妖级",
    ja: "キツネ",
  },
  "11196": {
    en: "Claw",
    zh: "利爪级",
    ja: "クロー",
  },
  "11198": {
    en: "Stiletto",
    zh: "短剑级",
    ja: "スティレット",
  },
  "11200": {
    en: "Taranis",
    zh: "塔纳尼斯级",
    ja: "タラニス",
  },
  "11202": {
    en: "Ares",
    zh: "阿瑞斯级",
    ja: "エリーズ",
  },
  "11365": {
    en: "Vengeance",
    zh: "复仇级",
    ja: "ベンジェンス",
  },
  "11371": {
    en: "Wolf",
    zh: "猎狼级",
    ja: "ウルフ",
  },
  "11377": {
    en: "Nemesis",
    zh: "纳美西斯级",
    ja: "ネメシス",
  },
  "11379": {
    en: "Hawk",
    zh: "战鹰级",
    ja: "ホーク",
  },
  "11381": {
    en: "Harpy",
    zh: "女妖级",
    ja: "ハーピー",
  },
  "11387": {
    en: "Hyena",
    zh: "土狼级",
    ja: "ハイエナ",
  },
  "11393": {
    en: "Retribution",
    zh: "审判者级",
    ja: "レトリビューション",
  },
  "11400": {
    en: "Jaguar",
    zh: "美洲虎级",
    ja: "ジャガー",
  },
  "11567": {
    en: "Avatar",
    zh: "神使级",
    ja: "アバター",
  },
  "11936": {
    en: "Apocalypse Imperial Issue",
    zh: "灾难级帝国型",
    ja: "アポカリプス帝国仕様",
  },
  "11938": {
    en: "Armageddon Imperial Issue",
    zh: "末日沙场级帝国型",
    ja: "アルマゲドン帝国仕様",
  },
  "11940": {
    en: "Gold Magnate",
    zh: "黄金富豪级",
    ja: "ゴールドマグニート",
  },
  "11942": {
    en: "Silver Magnate",
    zh: "白银富豪级",
    ja: "シルバーマグニート",
  },
  "11957": {
    en: "Falcon",
    zh: "战隼级",
    ja: "ファルコン",
  },
  "11959": {
    en: "Rook",
    zh: "白嘴鸦级",
    ja: "ルーク",
  },
  "11961": {
    en: "Huginn",
    zh: "休津级",
    ja: "フギン",
  },
  "11963": {
    en: "Rapier",
    zh: "长剑级",
    ja: "レイピア",
  },
  "11965": {
    en: "Pilgrim",
    zh: "朝圣级",
    ja: "ピルグリム",
  },
  "11969": {
    en: "Arazu",
    zh: "埃拉兹级",
    ja: "アラズ",
  },
  "11971": {
    en: "Lachesis",
    zh: "拉克希斯级",
    ja: "ラケシス",
  },
  "11978": {
    en: "Scimitar",
    zh: "曲剑级",
    ja: "シミター",
  },
  "11985": {
    en: "Basilisk",
    zh: "皇冠蜥级",
    ja: "バシリスク",
  },
  "11987": {
    en: "Guardian",
    zh: "守卫级",
    ja: "ガーディアン",
  },
  "11989": {
    en: "Oneiros",
    zh: "奥内罗斯级",
    ja: "オネイロス",
  },
  "11993": {
    en: "Cerberus",
    zh: "希尔博拉斯级",
    ja: "ケルベロス",
  },
  "11995": {
    en: "Onyx",
    zh: "奥尼克斯级",
    ja: "オニキス",
  },
  "11999": {
    en: "Vagabond",
    zh: "流浪级",
    ja: "バガボンド",
  },
  "12003": {
    en: "Zealot",
    zh: "狂热级",
    ja: "ゼレット",
  },
  "12005": {
    en: "Ishtar",
    zh: "伊什塔级",
    ja: "イシュタル",
  },
  "12011": {
    en: "Eagle",
    zh: "银鹰级",
    ja: "イーグル",
  },
  "12013": {
    en: "Broadsword",
    zh: "阔刀级",
    ja: "ブロードソード",
  },
  "12015": {
    en: "Muninn",
    zh: "缪宁级",
    ja: "ムニン",
  },
  "12017": {
    en: "Devoter",
    zh: "奉献级",
    ja: "ディボーター",
  },
  "12019": {
    en: "Sacrilege",
    zh: "渎圣级",
    ja: "サクリッジ",
  },
  "12021": {
    en: "Phobos",
    zh: "伏波斯级",
    ja: "フォボス",
  },
  "12023": {
    en: "Deimos",
    zh: "戴默斯级",
    ja: "デイモス",
  },
  "12032": {
    en: "Manticore",
    zh: "蝎尾怪级",
    ja: "マンティコア",
  },
  "12034": {
    en: "Hound",
    zh: "猎犬级",
    ja: "ハウンド",
  },
  "12038": {
    en: "Purifier",
    zh: "净化级",
    ja: "ピュリファイヤー",
  },
  "12042": {
    en: "Ishkur",
    zh: "伊什库尔级",
    ja: "イシュカー",
  },
  "12044": {
    en: "Enyo",
    zh: "恩尤级",
    ja: "エンヨ",
  },
  "12729": {
    en: "Crane",
    zh: "天鹤级",
    ja: "クレーン",
  },
  "12731": {
    en: "Bustard",
    zh: "大鸨级",
    ja: "バスタード",
  },
  "12733": {
    en: "Prorator",
    zh: "分裂级",
    ja: "プロレーター",
  },
  "12735": {
    en: "Prowler",
    zh: "徘徊者级",
    ja: "プラウラー",
  },
  "12743": {
    en: "Viator",
    zh: "旅行者级",
    ja: "ビアトール",
  },
  "12745": {
    en: "Occator",
    zh: "奥卡托级",
    ja: "オカター",
  },
  "12747": {
    en: "Mastodon",
    zh: "巨象级",
    ja: "マストドン",
  },
  "12753": {
    en: "Impel",
    zh: "激进级",
    ja: "インペル",
  },
  "13202": {
    en: "Megathron Federate Issue",
    zh: "万王宝座级联邦型",
    ja: "メガソロン連合軍仕様",
  },
  "16227": {
    en: "Ferox",
    zh: "猛鲑级",
    ja: "フェロックス",
  },
  "16229": {
    en: "Brutix",
    zh: "布鲁提克斯级",
    ja: "ブルティクス",
  },
  "16231": {
    en: "Cyclone",
    zh: "飓风级",
    ja: "サイクロン",
  },
  "16233": {
    en: "Prophecy",
    zh: "先知级",
    ja: "プロフェシー",
  },
  "16236": {
    en: "Coercer",
    zh: "强制者级",
    ja: "コウアーサー",
  },
  "16238": {
    en: "Cormorant",
    zh: "海燕级",
    ja: "コーモラント",
  },
  "16240": {
    en: "Catalyst",
    zh: "促进级",
    ja: "カタリスト",
  },
  "16242": {
    en: "Thrasher",
    zh: "长尾鲛级",
    ja: "シュラッシャー",
  },
  "17476": {
    en: "Covetor",
    zh: "妄想级",
    ja: "コベトアー",
  },
  "17478": {
    en: "Retriever",
    zh: "回旋者级",
    ja: "レトリーバー",
  },
  "17480": {
    en: "Procurer",
    zh: "猎获级",
    ja: "プロキュアラー",
  },
  "17619": {
    en: "Caldari Navy Hookbill",
    zh: "加达里海军霍克比尔级",
    ja: "カルダリ海軍仕様フックビル",
  },
  "17634": {
    en: "Caracal Navy Issue",
    zh: "狞獾级海军型",
    ja: "カラカル海軍仕様",
  },
  "17636": {
    en: "Raven Navy Issue",
    zh: "乌鸦级海军型",
    ja: "レイブン海軍仕様",
  },
  "17703": {
    en: "Imperial Navy Slicer",
    zh: "帝国海军切割机级",
    ja: "帝国海軍仕様スライサー",
  },
  "17709": {
    en: "Omen Navy Issue",
    zh: "启示级海军型",
    ja: "オーメン海軍仕様",
  },
  "17713": {
    en: "Stabber Fleet Issue",
    zh: "刺客级舰队型",
    ja: "スタッバー海軍仕様",
  },
  "17715": {
    en: "Gila",
    zh: "毒蜥级",
    ja: "ギラ",
  },
  "17718": {
    en: "Phantasm",
    zh: "幽灵级",
    ja: "ファンタズム",
  },
  "17720": {
    en: "Cynabal",
    zh: "塞纳波级",
    ja: "サイノバル",
  },
  "17722": {
    en: "Vigilant",
    zh: "警惕级",
    ja: "ヴィジラント",
  },
  "17726": {
    en: "Apocalypse Navy Issue",
    zh: "灾难级海军型",
    ja: "アポカリプス海軍仕様",
  },
  "17728": {
    en: "Megathron Navy Issue",
    zh: "万王宝座级海军型",
    ja: "メガソロン海軍仕様",
  },
  "17732": {
    en: "Tempest Fleet Issue",
    zh: "狂暴级舰队型",
    ja: "テンペスト海軍仕様",
  },
  "17736": {
    en: "Nightmare",
    zh: "噩梦级",
    ja: "ナイトメア",
  },
  "17738": {
    en: "Machariel",
    zh: "马克瑞级",
    ja: "マカリエル",
  },
  "17740": {
    en: "Vindicator",
    zh: "复仇者级",
    ja: "ビンディケイター",
  },
  "17812": {
    en: "Republic Fleet Firetail",
    zh: "共和舰队火尾鸡级",
    ja: "共和国海軍仕様ファイアテイル",
  },
  "17841": {
    en: "Federation Navy Comet",
    zh: "联邦海军彗星级",
    ja: "連邦海軍仕様コメット",
  },
  "17843": {
    en: "Vexor Navy Issue",
    zh: "狂怒者级海军型",
    ja: "ベクサー海軍仕様",
  },
  "17918": {
    en: "Rattlesnake",
    zh: "响尾蛇级",
    ja: "ラトルスネーク",
  },
  "17920": {
    en: "Bhaalgorn",
    zh: "巴戈龙级",
    ja: "バールゴーン",
  },
  "17922": {
    en: "Ashimmu",
    zh: "阿什姆级",
    ja: "アシッムー",
  },
  "17924": {
    en: "Succubus",
    zh: "魔女级",
    ja: "サキュバス",
  },
  "17926": {
    en: "Cruor",
    zh: "凝血级",
    ja: "クルール",
  },
  "17928": {
    en: "Daredevil",
    zh: "夜魔侠级",
    ja: "デアデビル",
  },
  "17930": {
    en: "Worm",
    zh: "潜龙级",
    ja: "ワーム",
  },
  "17932": {
    en: "Dramiel",
    zh: "德拉米尔级",
    ja: "ドラミエル",
  },
  "1944": {
    en: "Bestower",
    zh: "恩赐者级",
    ja: "ビストワー",
  },
  "19720": {
    en: "Revelation",
    zh: "神示级",
    ja: "レベレーション",
  },
  "19722": {
    en: "Naglfar",
    zh: "纳迦法级",
    ja: "ナグルファー",
  },
  "19724": {
    en: "Moros",
    zh: "莫洛级",
    ja: "モロス",
  },
  "19726": {
    en: "Phoenix",
    zh: "凤凰级",
    ja: "フェニックス",
  },
  "19744": {
    en: "Sigil",
    zh: "魔符级",
    ja: "サイジル",
  },
  "2006": {
    en: "Omen",
    zh: "启示级",
    ja: "オーメン",
  },
  "20125": {
    en: "Curse",
    zh: "诅咒级",
    ja: "カース",
  },
  "20183": {
    en: "Providence",
    zh: "普罗维登斯级",
    ja: "プロビデンス",
  },
  "20185": {
    en: "Charon",
    zh: "渡神级",
    ja: "カロン",
  },
  "20187": {
    en: "Obelisk",
    zh: "方尖塔级",
    ja: "オベリスク",
  },
  "20189": {
    en: "Fenrir",
    zh: "芬利厄级",
    ja: "フェンリル",
  },
  "2078": {
    en: "Zephyr",
    zh: "微风级",
    ja: "ゼファー",
  },
  "21097": {
    en: "Goru's Shuttle",
    zh: "高鲁的穿梭机",
    ja: "ゴルシャトル",
  },
  "2161": {
    en: "Crucifier",
    zh: "磨难级",
    ja: "クルセファー",
  },
  "21628": {
    en: "Guristas Shuttle",
    zh: "古斯塔斯穿梭机",
    ja: "ガリスタスシャトル",
  },
  "22428": {
    en: "Redeemer",
    zh: "救世级",
    ja: "リディーマー",
  },
  "22430": {
    en: "Sin",
    zh: "罪恶级",
    ja: "シン",
  },
  "22436": {
    en: "Widow",
    zh: "寡妇级",
    ja: "ウィドウ",
  },
  "22440": {
    en: "Panther",
    zh: "黑豹级",
    ja: "パンサー",
  },
  "22442": {
    en: "Eos",
    zh: "曙光女神级",
    ja: "エオス",
  },
  "22444": {
    en: "Sleipnir",
    zh: "斯雷普尼级",
    ja: "スレイプニル",
  },
  "22446": {
    en: "Vulture",
    zh: "兀鹫级",
    ja: "ボーチャー",
  },
  "22448": {
    en: "Absolution",
    zh: "救赎级",
    ja: "アブソリューション",
  },
  "22452": {
    en: "Heretic",
    zh: "异端级",
    ja: "ヘレティック",
  },
  "22456": {
    en: "Sabre",
    zh: "剑齿虎级",
    ja: "セイバー",
  },
  "22460": {
    en: "Eris",
    zh: "厄里斯级",
    ja: "エリス",
  },
  "22464": {
    en: "Flycatcher",
    zh: "飞燕级",
    ja: "フライキャッチャー",
  },
  "22466": {
    en: "Astarte",
    zh: "阿施塔特级",
    ja: "アスタルト",
  },
  "22468": {
    en: "Claymore",
    zh: "月刃级",
    ja: "クレイモア",
  },
  "22470": {
    en: "Nighthawk",
    zh: "夜鹰级",
    ja: "ナイトホーク",
  },
  "22474": {
    en: "Damnation",
    zh: "永灭级",
    ja: "ダムネーション",
  },
  "22544": {
    en: "Hulk",
    zh: "霍克级",
    ja: "ハルク",
  },
  "22546": {
    en: "Skiff",
    zh: "轻舟级",
    ja: "スキフ",
  },
  "22548": {
    en: "Mackinaw",
    zh: "麦基诺级",
    ja: "マッキノー",
  },
  "22852": {
    en: "Hel",
    zh: "冥府级",
    ja: "ヘル",
  },
  "23757": {
    en: "Archon",
    zh: "执政官级",
    ja: "アーコン",
  },
  "23773": {
    en: "Ragnarok",
    zh: "拉格纳洛克级",
    ja: "ラグナロク",
  },
  "23911": {
    en: "Thanatos",
    zh: "绝念级",
    ja: "タナトス",
  },
  "23913": {
    en: "Nyx",
    zh: "夜神级",
    ja: "ニクス",
  },
  "23915": {
    en: "Chimera",
    zh: "奇美拉级",
    ja: "キメラ",
  },
  "23917": {
    en: "Wyvern",
    zh: "飞龙级",
    ja: "ワイバーン",
  },
  "23919": {
    en: "Aeon",
    zh: "万古级",
    ja: "イーオン",
  },
  "24483": {
    en: "Nidhoggur",
    zh: "尼铎格尔级",
    ja: "ニドフッグラー",
  },
  "24688": {
    en: "Rokh",
    zh: "鹏鲲级",
    ja: "ローク",
  },
  "24690": {
    en: "Hyperion",
    zh: "亥伯龙神级",
    ja: "ハイペリオン",
  },
  "24692": {
    en: "Abaddon",
    zh: "地狱天使级",
    ja: "アバドン",
  },
  "24694": {
    en: "Maelstrom",
    zh: "死亡漩涡级",
    ja: "メイルストローム",
  },
  "24696": {
    en: "Harbinger",
    zh: "先驱者级",
    ja: "ハービンジャー",
  },
  "24698": {
    en: "Drake",
    zh: "幼龙级",
    ja: "ドレイク",
  },
  "24700": {
    en: "Myrmidon",
    zh: "弥洱米顿级",
    ja: "ミュルミドン",
  },
  "24702": {
    en: "Hurricane",
    zh: "暴风级",
    ja: "ハリケーン",
  },
  "26840": {
    en: "Raven State Issue",
    zh: "乌鸦级政府型",
    ja: "レイブン連合仕様",
  },
  "26842": {
    en: "Tempest Tribal Issue",
    zh: "狂暴级部族型",
    ja: "テンペスト連盟仕様",
  },
  "27299": {
    en: "Civilian Amarr Shuttle",
    zh: "民用艾玛穿梭机",
    ja: "民間人仕様アマーシャトル",
  },
  "27301": {
    en: "Civilian Caldari Shuttle",
    zh: "民用加达里穿梭机",
    ja: "民間人仕様カルダリシャトル",
  },
  "27303": {
    en: "Civilian Gallente Shuttle",
    zh: "民用盖伦特穿梭机",
    ja: "民間人仕様ガレンテのシャトル",
  },
  "27305": {
    en: "Civilian Minmatar Shuttle",
    zh: "民用米玛塔尔穿梭机",
    ja: "民間人仕様ミンマターシャトル",
  },
  "2834": {
    en: "Utu",
    zh: "乌图级",
    ja: "ウツ",
  },
  "28352": {
    en: "Rorqual",
    zh: "长须鲸级",
    ja: "ロークアル",
  },
  "2836": {
    en: "Adrestia",
    zh: "复仇女神级",
    ja: "アドラステア",
  },
  "28606": {
    en: "Orca",
    zh: "逆戟鲸级",
    ja: "オルカ",
  },
  "2863": {
    en: "Primae",
    zh: "元始级",
    ja: "プライム",
  },
  "28659": {
    en: "Paladin",
    zh: "帕拉丁级",
    ja: "パラディン",
  },
  "28661": {
    en: "Kronos",
    zh: "克洛诺斯级",
    ja: "クロノス",
  },
  "28665": {
    en: "Vargur",
    zh: "恶狼级",
    ja: "ヴァーガー",
  },
  "28710": {
    en: "Golem",
    zh: "魔像级",
    ja: "ゴーレム",
  },
  "28844": {
    en: "Rhea",
    zh: "奥鸟级",
    ja: "レハ",
  },
  "28846": {
    en: "Nomad",
    zh: "游牧者级",
    ja: "ノマッド",
  },
  "28848": {
    en: "Anshar",
    zh: "安莎尔级",
    ja: "アンシャー",
  },
  "28850": {
    en: "Ark",
    zh: "方舟级",
    ja: "アーク",
  },
  "29248": {
    en: "Magnate",
    zh: "富豪级",
    ja: "マグニート",
  },
  "29266": {
    en: "Apotheosis",
    zh: "神圣穿梭机",
    ja: "アポシオシス",
  },
  "29336": {
    en: "Scythe Fleet Issue",
    zh: "镰刀级舰队型",
    ja: "サイス海軍仕様",
  },
  "29337": {
    en: "Augoror Navy Issue",
    zh: "奥格诺级海军型",
    ja: "オーゴロー海軍仕様",
  },
  "29340": {
    en: "Osprey Navy Issue",
    zh: "鱼鹰级海军型",
    ja: "オスプレイ海軍仕様",
  },
  "29344": {
    en: "Exequror Navy Issue",
    zh: "送葬者级海军型",
    ja: "イクセキュラー海軍仕様",
  },
  "2998": {
    en: "Noctis",
    zh: "黑夜级",
    ja: "ノクティス",
  },
  "29984": {
    en: "Tengu",
    zh: "金鹏级",
    ja: "テング",
  },
  "29986": {
    en: "Legion",
    zh: "圣卒级",
    ja: "レギオン",
  },
  "29988": {
    en: "Proteus",
    zh: "海神级",
    ja: "プロテウス",
  },
  "29990": {
    en: "Loki",
    zh: "洛基级",
    ja: "ロキ",
  },
  "30842": {
    en: "InterBus Shuttle",
    zh: "星际捷运穿梭机",
    ja: "インターバスのシャトル",
  },
  "32207": {
    en: "Freki",
    zh: "暴狼级",
    ja: "フレキ",
  },
  "32209": {
    en: "Mimir",
    zh: "弥米尔级",
    ja: "ミミール",
  },
  "32305": {
    en: "Armageddon Navy Issue",
    zh: "末日沙场级海军型",
    ja: "アルマゲドン海軍仕様",
  },
  "32307": {
    en: "Dominix Navy Issue",
    zh: "多米尼克斯级海军型",
    ja: "ドミニックス海軍仕様",
  },
  "32309": {
    en: "Scorpion Navy Issue",
    zh: "毒蝎级海军型",
    ja: "スコーピオン海軍仕様",
  },
  "32311": {
    en: "Typhoon Fleet Issue",
    zh: "台风级舰队型",
    ja: "タイフーン海軍仕様",
  },
  "32788": {
    en: "Cambion",
    zh: "魔裔级",
    ja: "カンビオン",
  },
  "32790": {
    en: "Etana",
    zh: "伊塔那级",
    ja: "エターナ",
  },
  "32811": {
    en: "Miasmos Amastris Edition",
    zh: "米亚莫斯级阿玛斯翠丝版",
    ja: "ミアスモスアマストリス仕様",
  },
  "32840": {
    en: "InterBus Catalyst",
    zh: "星际捷运促进级",
    ja: "インターバス仕様カタリスト",
  },
  "32842": {
    en: "Intaki Syndicate Catalyst",
    zh: "印塔基联合财团促进级",
    ja: "インタキシンジケート仕様カタリスト",
  },
  "32844": {
    en: "Inner Zone Shipping Catalyst",
    zh: "短途物流促进级",
    ja: "インナーゾーン運送仕様カタリスト",
  },
  "32846": {
    en: "Quafe Catalyst",
    zh: "酷菲促进级",
    ja: "クァフェ仕様カタリスト",
  },
  "32848": {
    en: "Aliastra Catalyst",
    zh: "埃拉斯多集团促进级",
    ja: "アリアストラ仕様カタリスト",
  },
  "32872": {
    en: "Algos",
    zh: "阿尔格斯级",
    ja: "アルゴス",
  },
  "32874": {
    en: "Dragoon",
    zh: "龙骑兵级",
    ja: "ドラグーン",
  },
  "32876": {
    en: "Corax",
    zh: "渡鸦级",
    ja: "コラックス",
  },
  "32878": {
    en: "Talwar",
    zh: "弯刀级",
    ja: "タルワー",
  },
  "32880": {
    en: "Venture",
    zh: "冲锋者级",
    ja: "ベンチャー",
  },
  "32983": {
    en: "Sukuuvestaa Heron",
    zh: "斯库维塔苍鹭级",
    ja: "スクーベスタ仕様ヘロン",
  },
  "32985": {
    en: "Inner Zone Shipping Imicus",
    zh: "短途物流伊米卡斯级",
    ja: "インナーゾーン運送仕様イミュカス",
  },
  "32987": {
    en: "Sarum Magnate",
    zh: "萨拉姆富豪级",
    ja: "サルム仕様マグニート",
  },
  "32989": {
    en: "Vherokior Probe",
    zh: "维洛奇亚探索级",
    ja: "ヴェロキュオール仕様プローブ",
  },
  "33079": {
    en: "Hematos",
    zh: "未来人类级",
    ja: "ヘマトス",
  },
  "33081": {
    en: "Taipan",
    zh: "毒蛇级",
    ja: "タイパン",
  },
  "33083": {
    en: "Violator",
    zh: "违逆者级",
    ja: "バイオレイター",
  },
  "33099": {
    en: "Nefantar Thrasher",
    zh: "内凡达长尾鲛级",
    ja: "ネファンター仕様シュラッシャー",
  },
  "33151": {
    en: "Brutix Navy Issue",
    zh: "布鲁提克斯级海军型",
    ja: "ブルティクス海軍仕様",
  },
  "33153": {
    en: "Drake Navy Issue",
    zh: "幼龙级海军型",
    ja: "ドレイク海軍仕様",
  },
  "33155": {
    en: "Harbinger Navy Issue",
    zh: "先驱者级海军型",
    ja: "ハービンジャー海軍仕様",
  },
  "33157": {
    en: "Hurricane Fleet Issue",
    zh: "暴风级舰队型",
    ja: "ハリケーン海軍仕様",
  },
  "33190": {
    en: "Tash-Murkon Magnate",
    zh: "塔什蒙贡富豪级",
    ja: "タッシュ-ムーコンマグニート",
  },
  "33395": {
    en: "Moracha",
    zh: "莫拉查级",
    ja: "モラチャ",
  },
  "33397": {
    en: "Chremoas",
    zh: "克雷默斯级",
    ja: "クレモアス",
  },
  "33468": {
    en: "Astero",
    zh: "阿斯特罗级",
    ja: "アステロ",
  },
  "33470": {
    en: "Stratios",
    zh: "斯特修斯级",
    ja: "ストラティオス",
  },
  "33472": {
    en: "Nestor",
    zh: "涅斯托级",
    ja: "ネストル",
  },
  "33513": {
    en: "Leopard",
    zh: "美洲豹级",
    ja: "レパード",
  },
  "33553": {
    en: "Stratios Emergency Responder",
    zh: "斯特修斯级应急反应型",
    ja: "急派型ストラティオス",
  },
  "33673": {
    en: "Whiptail",
    zh: "长尾蜥级",
    ja: "ウィップテイル",
  },
  "33675": {
    en: "Chameleon",
    zh: "变色龙级",
    ja: "カメレオン",
  },
  "33697": {
    en: "Prospect",
    zh: "掘金者级",
    ja: "プロスペクト",
  },
  "33816": {
    en: "Garmur",
    zh: "加姆级",
    ja: "ガルム",
  },
  "33818": {
    en: "Orthrus",
    zh: "奥苏斯级",
    ja: "オーソラス",
  },
  "33820": {
    en: "Barghest",
    zh: "巴盖斯级",
    ja: "バーゲスト",
  },
  "34151": {
    en: "Rattlesnake Victory Edition",
    zh: "响尾蛇级胜利版",
    ja: "ラトルスネーク・ビクトリーエディション",
  },
  "34317": {
    en: "Confessor",
    zh: "忏悔者级",
    ja: "コンフェッサー",
  },
  "34328": {
    en: "Bowhead",
    zh: "弓头鲸级",
    ja: "バウヘッド",
  },
  "34496": {
    en: "Council Diplomatic Shuttle",
    zh: "议会外交穿梭机",
    ja: "議会所有の外交用シャトル",
  },
  "34562": {
    en: "Svipul",
    zh: "斯威普级",
    ja: "スヴィプル",
  },
  "34590": {
    en: "Victorieux Luxury Yacht",
    zh: "凯旋奢华游艇",
    ja: "ヴィクトリュース級高級ヨット",
  },
  "34828": {
    en: "Jackdaw",
    zh: "寒鸦级",
    ja: "ジャックドー",
  },
  "3514": {
    en: "Revenant",
    zh: "归魂者级",
    ja: "レベナント",
  },
  "3516": {
    en: "Malice",
    zh: "恶意级",
    ja: "マライス",
  },
  "3518": {
    en: "Vangel",
    zh: "传道者级",
    ja: "ヴァンジェル",
  },
  "3532": {
    en: "Echelon",
    zh: "梯队级",
    ja: "エシュロン",
  },
  "35683": {
    en: "Hecate",
    zh: "赫卡特级",
    ja: "ヘカテ",
  },
  "35779": {
    en: "Imp",
    zh: "小鬼级",
    ja: "インプ",
  },
  "35781": {
    en: "Fiend",
    zh: "恶魔级",
    ja: "フィーンド",
  },
  "37135": {
    en: "Endurance",
    zh: "永恒者级",
    ja: "エンデュランス",
  },
  "37453": {
    en: "Crucifier Navy Issue",
    zh: "磨难级海军型",
    ja: "クルセファー海軍版",
  },
  "37454": {
    en: "Vigil Fleet Issue",
    zh: "守夜者级舰队型",
    ja: "ヴィジリ フリート版",
  },
  "37455": {
    en: "Griffin Navy Issue",
    zh: "狮鹫级海军型",
    ja: "グリフィン海軍版",
  },
  "37456": {
    en: "Maulus Navy Issue",
    zh: "毛鲁斯级海军型",
    ja: "マウルス海軍版",
  },
  "37457": {
    en: "Deacon",
    zh: "执事级",
    ja: "ディーコン",
  },
  "37458": {
    en: "Kirin",
    zh: "麒麟级",
    ja: "キリン",
  },
  "37459": {
    en: "Thalia",
    zh: "塔利亚级",
    ja: "タリア",
  },
  "37460": {
    en: "Scalpel",
    zh: "手术刀级",
    ja: "スカルペル",
  },
  "37480": {
    en: "Bifrost",
    zh: "天梯级",
    ja: "ビフレスト",
  },
  "37481": {
    en: "Pontifex",
    zh: "教皇级",
    ja: "ポンティフェックス",
  },
  "37482": {
    en: "Stork",
    zh: "鹳鸟级",
    ja: "ストーク",
  },
  "37483": {
    en: "Magus",
    zh: "占星级",
    ja: "メイガス",
  },
  "3756": {
    en: "Gnosis",
    zh: "灵感级",
    ja: "グノーシス",
  },
  "37604": {
    en: "Apostle",
    zh: "使徒级",
    ja: "アポスル",
  },
  "37605": {
    en: "Minokawa",
    zh: "龙鸟级",
    ja: "ミノカワ",
  },
  "37606": {
    en: "Lif",
    zh: "利夫级",
    ja: "Lif",
  },
  "37607": {
    en: "Ninazu",
    zh: "尼纳苏级",
    ja: "ニナズ",
  },
  "3764": {
    en: "Leviathan",
    zh: "勒维亚坦级",
    ja: "リバイアサン",
  },
  "3766": {
    en: "Vigil",
    zh: "守夜者级",
    ja: "ヴィジリ",
  },
  "4005": {
    en: "Scorpion Ishukone Watch",
    zh: "毒蝎级异株湖保安型",
    ja: "スコーピオンイシュコーネウォッチ",
  },
  "42124": {
    en: "Vehement",
    zh: "猛烈级",
    ja: "ヴィエメント",
  },
  "42125": {
    en: "Vendetta",
    zh: "仇恨级",
    ja: "ヴェンデッタ",
  },
  "42126": {
    en: "Vanquisher",
    zh: "征服者级",
    ja: "ヴァンキッシャー",
  },
  "42241": {
    en: "Molok",
    zh: "摩洛克级",
    ja: "モロク",
  },
  "42242": {
    en: "Dagon",
    zh: "大衮级",
    ja: "ダゴン",
  },
  "42243": {
    en: "Chemosh",
    zh: "基抹级",
    ja: "ケモシュ",
  },
  "42244": {
    en: "Porpoise",
    zh: "海豚级",
    ja: "ポーパス",
  },
  "42245": {
    en: "Rabisu",
    zh: "拉比苏级",
    ja: "ラビス",
  },
  "42246": {
    en: "Caedes",
    zh: "凯帝斯级",
    ja: "カエデス",
  },
  "42685": {
    en: "Sunesis",
    zh: "旭日级",
    ja: "スネシス",
  },
  "4302": {
    en: "Oracle",
    zh: "预言级",
    ja: "オラクル",
  },
  "4306": {
    en: "Naga",
    zh: "娜迦级",
    ja: "ナーガ",
  },
  "4308": {
    en: "Talos",
    zh: "塔洛斯级",
    ja: "タロス",
  },
  "4310": {
    en: "Tornado",
    zh: "龙卷风级",
    ja: "トルネード",
  },
  "4363": {
    en: "Miasmos Quafe Ultra Edition",
    zh: "米亚莫斯级酷菲特强版",
    ja: "ミアスモスクァフェウルトラ仕様",
  },
  "4388": {
    en: "Miasmos Quafe Ultramarine Edition",
    zh: "米亚莫斯级酷菲深蓝版",
    ja: "ミアスモスクァフェウルトラマリン仕様",
  },
  "44993": {
    en: "Pacifier",
    zh: "安抚者",
    ja: "パシファイアー",
  },
  "44995": {
    en: "Enforcer",
    zh: "执法者",
    ja: "エンフォーサー",
  },
  "44996": {
    en: "Marshal",
    zh: "元帅级",
    ja: "マーシャル",
  },
  "45530": {
    en: "Virtuoso",
    zh: "收藏家级",
    ja: "バーチュオソ",
  },
  "45531": {
    en: "Victor",
    zh: "胜利者级",
    ja: "ビクター",
  },
  "45534": {
    en: "Monitor",
    zh: "监视者级",
    ja: "モニター",
  },
  "45645": {
    en: "Loggerhead",
    zh: "赤龟级",
    ja: "ロガーヘッド",
  },
  "45647": {
    en: "Caiman",
    zh: "凯门鳄级",
    ja: "ケイマン",
  },
  "45649": {
    en: "Komodo",
    zh: "科莫多级",
    ja: "コモド",
  },
  "47269": {
    en: "Damavik",
    zh: "达玛维克级",
    ja: "ダマヴィク",
  },
  "47270": {
    en: "Vedmak",
    zh: "维德马克级",
    ja: "ヴェドマック",
  },
  "47271": {
    en: "Leshak",
    zh: "勒沙克级",
    ja: "レシャク",
  },
  "47466": {
    en: "Praxis",
    zh: "实践级",
    ja: "プラクシス",
  },
  "48635": {
    en: "Tiamat",
    zh: "提亚玛特级",
    ja: "ティアマット",
  },
  "48636": {
    en: "Hydra",
    zh: "九头蛇级",
    ja: "ハイドラ",
  },
  "49710": {
    en: "Kikimora",
    zh: "奇奇莫拉级",
    ja: "キキモラ",
  },
  "49711": {
    en: "Drekavac",
    zh: "德雷卡瓦级",
    ja: "ドレカヴァク",
  },
  "49712": {
    en: "Rodiva",
    zh: "洛迪瓦级",
    ja: "ロディバ",
  },
  "49713": {
    en: "Zarmazd",
    zh: "扎玛德级",
    ja: "ザルマズド",
  },
  "52250": {
    en: "Nergal",
    zh: "涅伽尔级",
    ja: "ネルガル",
  },
  "52252": {
    en: "Ikitursa",
    zh: "伊基图萨级",
    ja: "イキトゥルサ",
  },
  "52254": {
    en: "Draugur",
    zh: "德拉古级",
    ja: "ドラウグル",
  },
  "52907": {
    en: "Zirnitra",
    zh: "泽尼塔级",
    ja: "ジルニトラ",
  },
  "54731": {
    en: "Skybreaker",
    zh: "破天级",
    ja: "スカイブレイカー",
  },
  "54732": {
    en: "Stormbringer",
    zh: "唤风级",
    ja: "ストームブリンガー",
  },
  "54733": {
    en: "Thunderchild",
    zh: "雷裔级",
    ja: "サンダーチャイルド",
  },
  "582": {
    en: "Bantam",
    zh: "矮脚鸡级",
    ja: "バンタム",
  },
  "583": {
    en: "Condor",
    zh: "秃鹫级",
    ja: "コンドール",
  },
  "584": {
    en: "Griffin",
    zh: "狮鹫级",
    ja: "グリフィン",
  },
  "585": {
    en: "Slasher",
    zh: "伐木者级",
    ja: "スラッシャー",
  },
  "586": {
    en: "Probe",
    zh: "探索级",
    ja: "プローブ",
  },
  "587": {
    en: "Rifter",
    zh: "裂谷级",
    ja: "リフター",
  },
  "588": {
    en: "Reaper",
    zh: "死神号",
    ja: "リーパー",
  },
  "589": {
    en: "Executioner",
    zh: "刽子手级",
    ja: "エクスキューショナー",
  },
  "590": {
    en: "Inquisitor",
    zh: "检察官级",
    ja: "インクイジター",
  },
  "591": {
    en: "Tormentor",
    zh: "巨神兵级",
    ja: "トーメンター",
  },
  "592": {
    en: "Navitas",
    zh: "纳维达斯级",
    ja: "ナビタス",
  },
  "593": {
    en: "Tristan",
    zh: "特里斯坦级",
    ja: "トリスタン",
  },
  "594": {
    en: "Incursus",
    zh: "因卡萨斯级",
    ja: "インカーサス",
  },
  "596": {
    en: "Impairor",
    zh: "帝国号",
    ja: "インパロール",
  },
  "597": {
    en: "Punisher",
    zh: "惩罚者级",
    ja: "パニッシャー",
  },
  "598": {
    en: "Breacher",
    zh: "分裂者级",
    ja: "ブリーチャー",
  },
  "599": {
    en: "Burst",
    zh: "爆发级",
    ja: "バースト",
  },
  "601": {
    en: "Ibis",
    zh: "伊毕斯号",
    ja: "イビス",
  },
  "602": {
    en: "Kestrel",
    zh: "茶隼级",
    ja: "ケストレル",
  },
  "603": {
    en: "Merlin",
    zh: "小鹰级",
    ja: "マーリン",
  },
  "605": {
    en: "Heron",
    zh: "苍鹭级",
    ja: "ヘロン",
  },
  "606": {
    en: "Velator",
    zh: "维拉托尔号",
    ja: "ベラター",
  },
  "607": {
    en: "Imicus",
    zh: "伊米卡斯级",
    ja: "イミュカス",
  },
  "60764": {
    en: "Laelaps",
    zh: "猎獒级",
    ja: "ライラプス",
  },
  "60765": {
    en: "Raiju",
    zh: "雷兽级",
    ja: "ライジュウ",
  },
  "608": {
    en: "Atron",
    zh: "阿特龙级",
    ja: "アトロン",
  },
  "609": {
    en: "Maulus",
    zh: "毛鲁斯级",
    ja: "マウルス",
  },
  "615": {
    en: "Immolator",
    zh: "献祭者级",
    ja: "イモレイター",
  },
  "616": {
    en: "Medusa",
    zh: "美杜莎级",
    ja: "メドゥーサ",
  },
  "617": {
    en: "Echo",
    zh: "回声级",
    ja: "エコー",
  },
  "620": {
    en: "Osprey",
    zh: "鱼鹰级",
    ja: "オスプレイ",
  },
  "621": {
    en: "Caracal",
    zh: "狞獾级",
    ja: "カラカル",
  },
  "622": {
    en: "Stabber",
    zh: "刺客级",
    ja: "スタッバー",
  },
  "623": {
    en: "Moa",
    zh: "巨鸟级",
    ja: "モア",
  },
  "624": {
    en: "Maller",
    zh: "暴君级",
    ja: "モーラー",
  },
  "625": {
    en: "Augoror",
    zh: "奥格诺级",
    ja: "オーゴロー",
  },
  "626": {
    en: "Vexor",
    zh: "狂怒者级",
    ja: "ベクサー",
  },
  "627": {
    en: "Thorax",
    zh: "托勒克斯级",
    ja: "ソーラックス",
  },
  "628": {
    en: "Arbitrator",
    zh: "主宰级",
    ja: "アービトレイター",
  },
  "629": {
    en: "Rupture",
    zh: "断崖级",
    ja: "ラプチャー",
  },
  "630": {
    en: "Bellicose",
    zh: "挑战级",
    ja: "ベリコース",
  },
  "631": {
    en: "Scythe",
    zh: "镰刀级",
    ja: "サイス",
  },
  "632": {
    en: "Blackbird",
    zh: "黑鸟级",
    ja: "ブラックバード",
  },
  "633": {
    en: "Celestis",
    zh: "星空级",
    ja: "セレスティス",
  },
  "634": {
    en: "Exequror",
    zh: "送葬者级",
    ja: "イクセキュラー",
  },
  "635": {
    en: "Opux Luxury Yacht",
    zh: "奥普克斯级豪华游轮",
    ja: "オプックスラグジュアリーヨット",
  },
  "638": {
    en: "Raven",
    zh: "乌鸦级",
    ja: "レイブン",
  },
  "639": {
    en: "Tempest",
    zh: "狂暴级",
    ja: "テンペスト",
  },
  "640": {
    en: "Scorpion",
    zh: "毒蝎级",
    ja: "スコーピオン",
  },
  "64034": {
    en: "Boobook",
    zh: "鹰鸮级",
    ja: "ブーブック",
  },
  "641": {
    en: "Megathron",
    zh: "万王宝座级",
    ja: "メガソロン",
  },
  "642": {
    en: "Apocalypse",
    zh: "灾难级",
    ja: "アポカリプス",
  },
  "643": {
    en: "Armageddon",
    zh: "末日沙场级",
    ja: "アルマゲドン",
  },
  "644": {
    en: "Typhoon",
    zh: "台风级",
    ja: "タイフーン",
  },
  "645": {
    en: "Dominix",
    zh: "多米尼克斯级",
    ja: "ドミニックス",
  },
  "648": {
    en: "Badger",
    zh: "獾级",
    ja: "バッジャー",
  },
  "649": {
    en: "Tayra",
    zh: "狐鼬级",
    ja: "タイラ",
  },
  "650": {
    en: "Nereus",
    zh: "涅鲁斯级",
    ja: "ネレウス",
  },
  "651": {
    en: "Hoarder",
    zh: "囤积者级",
    ja: "ホーダー",
  },
  "652": {
    en: "Mammoth",
    zh: "猛犸级",
    ja: "マンモス",
  },
  "653": {
    en: "Wreathe",
    zh: "环绕级",
    ja: "ウレス",
  },
  "654": {
    en: "Kryos",
    zh: "克琉斯级",
    ja: "クリオス",
  },
  "655": {
    en: "Epithal",
    zh: "埃比斯级",
    ja: "エピタル",
  },
  "656": {
    en: "Miasmos",
    zh: "米亚莫斯级",
    ja: "ミアスモス",
  },
  "657": {
    en: "Iteron Mark V",
    zh: "伊特龙级MKV",
    ja: "イタロンマークV",
  },
  "671": {
    en: "Erebus",
    zh: "俄洛巴斯级",
    ja: "エレバス",
  },
  "672": {
    en: "Caldari Shuttle",
    zh: "加达里穿梭机",
    ja: "カルダリシャトル",
  },
  "72811": {
    en: "Cyclone Fleet Issue",
    zh: "飓风级舰队型",
    ja: "サイクロン海軍仕様",
  },
  "72812": {
    en: "Ferox Navy Issue",
    zh: "猛鲑级海军型",
    ja: "フェロックス海軍仕様",
  },
  "72869": {
    en: "Myrmidon Navy Issue",
    zh: "弥洱米顿级海军型",
    ja: "ミュルミドン海軍仕様",
  },
  "72872": {
    en: "Prophecy Navy Issue",
    zh: "先知级海军型",
    ja: "プロフェシー海軍仕様",
  },
  "72903": {
    en: "Probe Fleet Issue",
    zh: "探索级舰队型",
    ja: "プローブ海軍仕様",
  },
  "72904": {
    en: "Heron Navy Issue",
    zh: "苍鹭级海军型",
    ja: "ヘロン海軍仕様",
  },
  "72907": {
    en: "Magnate Navy Issue",
    zh: "富豪级海军型",
    ja: "マグニート海軍仕様",
  },
  "72913": {
    en: "Imicus Navy Issue",
    zh: "伊米卡斯级海军型",
    ja: "イミュカス海軍仕様",
  },
  "73787": {
    en: "Naglfar Fleet Issue",
    zh: "纳迦法级舰队型",
    ja: "ナグルファー海軍仕様",
  },
  "73789": {
    en: "Coercer Navy Issue",
    zh: "强制者级海军型",
    ja: "コウアーサー海軍仕様",
  },
  "73790": {
    en: "Revelation Navy Issue",
    zh: "神示级海军型",
    ja: "レベレーション海軍仕様",
  },
  "73792": {
    en: "Moros Navy Issue",
    zh: "莫洛级海军型",
    ja: "モロス海軍仕様",
  },
  "73793": {
    en: "Phoenix Navy Issue",
    zh: "凤凰级海军型",
    ja: "フェニックス海軍仕様",
  },
  "73794": {
    en: "Thrasher Fleet Issue",
    zh: "长尾鲛级舰队型",
    ja: "シュラッシャー海軍仕様",
  },
  "73795": {
    en: "Cormorant Navy Issue",
    zh: "海燕级海军型",
    ja: "コーモラント海軍仕様",
  },
  "73796": {
    en: "Catalyst Navy Issue",
    zh: "促进级海军型",
    ja: "カタリスト海軍仕様",
  },
  "74141": {
    en: "Geri",
    zh: "格里级",
    ja: "ゲリ",
  },
  "74316": {
    en: "Bestla",
    zh: "贝斯特拉",
    ja: "ベストラ",
  },
  "77114": {
    en: "Metamorphosis",
    zh: "变形级",
    ja: "メタモルフォーシス",
  },
  "77281": {
    en: "Hubris",
    zh: "狂徒",
    ja: "ヒューブリス",
  },
  "77283": {
    en: "Bane",
    zh: "破坏者",
    ja: "ベイン",
  },
  "77284": {
    en: "Karura",
    zh: "迦楼罗",
    ja: "カルラ",
  },
  "77288": {
    en: "Valravn",
    zh: "血鸦",
    ja: "ヴァルラウン",
  },
  "77726": {
    en: "Cybele",
    zh: "西布勒级",
    ja: "キュベレー",
  },
  "78333": {
    en: "Mekubal",
    zh: "梅库巴尔级",
    ja: "メクバル",
  },
  "78366": {
    en: "Alligator",
    zh: "短吻鳄级",
    ja: "アリゲーター",
  },
  "78367": {
    en: "Mamba",
    zh: "曼巴级",
    ja: "マンバ",
  },
  "78369": {
    en: "Khizriel",
    zh: "希兹里尔级",
    ja: "キズリエル",
  },
  "78414": {
    en: "Shapash",
    zh: "沙帕什级",
    ja: "シャパシュ",
  },
  "78576": {
    en: "Azariel",
    zh: "阿扎里尔级",
    ja: "アザリエル",
  },
  "81008": {
    en: "Squall",
    zh: "狂风级",
    ja: "スコール",
  },
  "81040": {
    en: "Avalanche",
    zh: "雪崩级",
    ja: "アヴァランチ",
  },
  "81046": {
    en: "Deluge",
    zh: "洪水级",
    ja: "デリュージ",
  },
  "81047": {
    en: "Torrent",
    zh: "湍流级",
    ja: "トーレント",
  },
  "85062": {
    en: "Sidewinder",
    zh: "侧进蛇级",
    ja: "サイドワインダー",
  },
  "85086": {
    en: "Cenotaph",
    zh: "纪念碑级",
    ja: "セノターフ",
  },
  "85087": {
    en: "Tholos",
    zh: "穹顶级",
    ja: "トロス",
  },
  "85229": {
    en: "Cobra",
    zh: "眼镜蛇级",
    ja: "コブラ",
  },
  "85236": {
    en: "Python",
    zh: "巨蟒",
    ja: "パイソン",
  },
  "87381": {
    en: "Sarathiel",
    zh: "萨拉希尔",
    ja: "サラティエル",
  },
  "88001": {
    en: "Babaroga",
    zh: "巴巴罗加号",
    ja: "ババロガ",
  },
  "89240": {
    en: "Pioneer",
    zh: "开拓者级",
    ja: "パイオニア",
  },
  "89607": {
    en: "Odysseus",
    zh: "奥德修斯级",
    ja: "オデュッセウス",
  },
  "89647": {
    en: "Pioneer Consortium Issue",
    zh: "开拓者级财团型",
    ja: "パイオニア・コンソーシアム仕様",
  },
  "89648": {
    en: "Venture Consortium Issue",
    zh: "冲锋者级财团型",
    ja: "ベンチャー・コンソーシアム仕様",
  },
  "89649": {
    en: "Outrider",
    zh: "先驱级",
    ja: "アウトライダー",
  },
  "89807": {
    en: "Anhinga",
    zh: "蛇鹈号",
    ja: "アンヒンガ",
  },
  "89808": {
    en: "Skua",
    zh: "贼鸥号",
    ja: "スクア",
  },
  "91174": {
    en: "Perseverance",
    zh: "坚毅者级",
    ja: "パーサヴィアランス",
  },
  "91775": {
    en: "Dragoon Navy Issue",
    zh: "龙骑兵级海军型",
    ja: "ドラグーン海軍仕様",
  },
  "91849": {
    en: "Algos Navy Issue",
    zh: "阿尔格斯级海军型",
    ja: "アルゴス海軍仕様",
  },
  "91857": {
    en: "Corax Navy Issue",
    zh: "渡鸦级海军型",
    ja: "コラックス海軍仕様",
  },
  "91858": {
    en: "Talwar Fleet Issue",
    zh: "弯刀级舰队型",
    ja: "タルワー海軍仕様",
  },
  "92282": {
    en: "Tenzin YC128 Campaign Bus",
    zh: "YC128年丹增竞选巴士",
    ja: "テンジンのYC128年選挙艦",
  },
  "92283": {
    en: "Moreau YC128 Campaign Bus",
    zh: "YC128年莫罗竞选巴士",
    ja: "モローのYC128年選挙艦",
  },
  "92284": {
    en: "Roden YC128 Campaign Bus",
    zh: "YC128年莱登竞选巴士",
    ja: "ローデンのYC128年選挙艦",
  },
  "92822": {
    en: "Salvation",
    zh: "救赎级",
    ja: "サルベーション",
  },
  "92823": {
    en: "Simurgh",
    zh: "西莫夫级",
    ja: "シムルグ",
  },
  "92824": {
    en: "Gaia",
    zh: "盖亚级",
    ja: "ガイア",
  },
  "92825": {
    en: "Ymir",
    zh: "伊米尔级",
    ja: "ユミル",
  },
  "legacy-eidolon": {
    en: "Eidolon",
    zh: "Eidolon",
    ja: "Eidolon",
  },
  "legacy-gecko": {
    en: "Gecko",
    zh: "壁虎级",
    ja: "ゲッコー",
  },
  "legacy-herald": {
    en: "Herald",
    zh: "Herald",
    ja: "Herald",
  },
  "legacy-ixion": {
    en: "Ixion",
    zh: "伊克西翁级",
    ja: "イクシオン",
  },
  "legacy-penitence": {
    en: "Penitence",
    zh: "Penitence",
    ja: "Penitence",
  },
  "legacy-phantom": {
    en: "Phantom",
    zh: "Phantom",
    ja: "Phantom",
  },
  "legacy-specter": {
    en: "Specter",
    zh: "Specter",
    ja: "Specter",
  },
  "legacy-visitant": {
    en: "Visitant",
    zh: "Visitant",
    ja: "Visitant",
  },
  "legacy-wraith": {
    en: "Wraith",
    zh: "Wraith",
    ja: "Wraith",
  },
} as const;
